// Palabras con las que alguien buscaría cada servicio (sinónimos, cómo se dice en Panamá, anglicismos de uso común).
// El buscador (js/buscador.mjs) las suma al nombre, la descripción y lo que incluye. Sin tildes ni mayúsculas.

export const PALABRAS = {
  R01: 'menu carta digital qr codigo escanear platos precios restaurante cafe fonda bar idiomas ingles turistas agotado',
  R02: 'pedir ordenar orden pedido mesa mesero mozo camarero llamar cuenta pagar pago propina dividir separar cuenta qr comensal ronda',
  R03: 'nfc etiqueta tag acercar telefono placa mesa contactless sin camara',
  R04: 'mapa mesas salon plano distribucion cuentas abiertas mesa ocupada libre cobrar caja facturar',
  R05: 'cocina pantalla kds comandas tickets chef pedidos cocinero estacion parrilla bar',
  R06: 'kiosco kiosko pantalla tactil touch autoservicio autopedido mostrador comida rapida fila',
  R07: 'delivery domicilio para llevar pedidos en linea sin comision apps pedidosya ubereats appetito repartidor',
  R08: 'reservas reservar mesa reservacion restaurante turno lista de espera',
  R09: 'menu pantallas televisor tv senalizacion digital menu board plato del dia',
  R10: 'temperatura nevera refrigerador congelador cuarto frio cadena de frio sensor alarma puerta abierta',
  R12: 'app delivery propia pedidosya ubereats uber eats appetito domicilio motorizados repartidores sucursales varios restaurantes collab marca propia sin comision app de pedidos',
  R13: 'pedidos whatsapp automaticos bot chatbot comanda cocina impresora automatico delivery domicilio tomar pedidos',
  R11: 'pos punto de venta caja registradora cajero cierre de caja ventas impresora tickets cajon codigo de barras',
  C01: 'contar personas contador clientes entran visitas trafico aforo conversion puerta afluencia',
  C02: 'mapa de calor heatmap recorrido pasillos zonas calientes permanencia exhibidor',
  C03: 'filas colas caja espera abrir otra caja aviso',
  C04: 'inventario conteo escanear rfid etiquetas existencias mercancia stock estantes',
  C05: 'robo perdidas hurto mermas camaras ia caja cajon bodega quien roba vigilancia inteligente',
  C06: 'tienda en linea ecommerce e-commerce vender por internet carrito shop online web de ventas',
  C07: 'etiquetas electronicas precios estante esl cambiar precios tinta electronica',
  C08: 'lealtad fidelizacion puntos sellos tarjeta cliente frecuente premios recompensas',
  C09: 'wifi wi-fi internet clientes portal cautivo registro hotspot',
  C10: '3d realidad aumentada ar producto modelo girar muebles visualizar',
  C11: 'whatsapp catalogo pedidos ventas por whatsapp vender por whatsapp enlace',
  S01: 'citas agenda agendar recordatorio recordar confirmar pacientes consultorio clinica doctor medico no show inasistencia turnos agente',
  S02: 'turnos sala de espera llamar paciente numero pantalla fila',
  S03: 'encuesta satisfaccion opinion resenas google calificacion despues de la cita',
  S04: 'videoconsulta telemedicina consulta en linea video zoom virtual',
  S05: 'expediente historia clinica historial paciente ficha medica',
  H01: 'reservas motor de reservas booking engine hotel cabanas hostal habitaciones directo sin comision deposito',
  H02: 'sincronizar calendario airbnb booking expedia ical doble reserva channel manager overbooking',
  H03: 'cerradura inteligente codigo puerta llave smart lock acceso huesped',
  H04: 'check-in registro huespedes formulario documento pasaporte firma',
  H05: 'consumo luz agua electricidad energia cabana medidor tanque fuga',
  H06: 'domotica casa inteligente luces aire acondicionado control remoto smart home alquiler',
  B01: 'recorrido 360 3d tour virtual propiedad apartamento casa bienes raices inmobiliaria matterport videojuego escaneo',
  B02: 'fotos fotografia profesional propiedad inmueble fotografo',
  B03: 'plano planos medidas metros cuadrados planta remodelar',
  B04: 'agente whatsapp inmobiliario prospectos leads calificar visitas bienes raices chatbot',
  B05: 'sitio web propiedades inmobiliaria portal listado fichas',
  B06: 'dron drone aereo tomas aereas terreno proyecto video',
  I01: 'sensores iot tablero monitoreo telemetria alertas planta temperatura energia',
  I02: 'gps rastreo flota vehiculos camiones motos repartidores ubicacion rutas tracking',
  I03: 'placas matriculas lpr anpr estacionamiento parking porton pluma camara',
  I04: 'control de acceso tarjeta qr puerta empleados visitas asistencia biometrico',
  I05: 'casco chaleco epp seguridad industrial camaras ia accidentes',
  I06: 'contador produccion linea banda sacos cajas piezas conteo turno',
  I07: 'vibracion motores bombas compresores mantenimiento predictivo falla temperatura',
  I08: 'bascula balanza peso pesaje camiones medidor conectado',
  I09: 'solar paneles energia consumo inversor ahorro electricidad',
  I10: 'dron inspeccion techos obra construccion avance terreno',
  T01: 'pagina web sitio web website landing presencia en internet dominio',
  T02: 'software a medida sistema programa desarrollo excel papel automatizar procesos aplicacion interna erp',
  T03: 'app aplicacion movil android iphone ios celular',
  T04: 'automatizacion automatizar tareas repetitivas copiar pegar reportes correos zapier make flujos',
  T05: 'chatbot bot asistente ia inteligencia artificial whatsapp responder mensajes atencion al cliente agente',
  T06: 'cotizador cotizaciones presupuestos proformas renglones inventario precios',
  T07: 'factura electronica facturacion dgi pac fiscal comprobante',
  T08: 'tablero dashboard reportes ventas indicadores kpi bi graficos',
  T09: 'pagos en linea cobrar yappy tarjeta enlace de pago link de pago pasarela tilopay ach',
  T10: 'red wifi internet cableado router access point oficina senal conexion',
  T11: 'camaras de seguridad cctv videovigilancia grabador dvr nvr ver desde el celular',
  T12: 'correo corporativo email dominio cuenta de correo profesional',
  T13: 'google maps perfil de negocio google my business resenas ubicacion aparecer en google seo local',
  T14: 'inventario compras existencias stock bodega proveedores reposicion erp',
  T15: 'crm clientes ventas seguimiento embudo vendedores prospectos',
  T16: 'portal clientes acceso usuarios pedidos facturas documentos estado',
  T17: 'firma electronica firmar documentos contratos digital',
  T18: 'respaldo backup copia de seguridad seguridad informatica virus contrasenas ciberseguridad',
  T19: 'soporte tecnico computadoras impresoras reparacion mantenimiento it informatica',
  T20: 'integracion api conectar sistemas sincronizar datos webhook',
  T21: 'ocr leer facturas documentos ia extraer datos pdf formularios digitalizar',
  T22: 'capacitacion curso taller ia chatgpt claude inteligencia artificial equipo entrenamiento',
  E01: 'matricula mensualidades colegio escuela academia cobro pagos padres morosidad',
  E02: 'asistencia estudiantes alumnos empleados marcar entrada qr tarjeta',
  E03: 'avisos padres circulares comunicados escuela whatsapp notificaciones',
  V01: 'turnos fila autolavado carwash lavado de autos taller aviso listo cola',
  V02: 'taller mecanico ordenes de trabajo presupuesto vehiculo placa reparacion',
  V03: 'barberia salon de belleza estilista peluqueria citas agenda unas spa',
};
