// Catálogo de servicios de alphateklab. De aquí salen la portada, las fichas y el cotizador
// (herramientas/generar.mjs escribe el HTML; las pruebas en pruebas/ validan este archivo).
//
// Reglas del contenido (ver CLAUDE.md):
// - precio: solo los que decidieron los socios. Todo lo demás va como null y se muestra «A cotizar».
// - demo: ruta relativa a una demo que existe en este repo o URL de otro repo de alphateklab.
// - instala: true si el servicio incluye ir al local a instalar algo físico.
// - aparte: costo que cobra un tercero y no alphateklab (p. ej. mensajes de WhatsApp), con su fuente en el informe.
// - visita: true si hay que ir a la propiedad (fotos, escaneo) aunque no se instale nada.

export const SECTORES = [
  { id: 'restaurantes', nombre: 'Restaurantes y cafés' },
  { id: 'comercio', nombre: 'Tiendas y comercio' },
  { id: 'salud', nombre: 'Clínicas y consultorios' },
  { id: 'hospedaje', nombre: 'Hospedaje y turismo' },
  { id: 'inmuebles', nombre: 'Bienes raíces' },
  { id: 'operacion', nombre: 'Bodegas, oficinas e industria' },
  { id: 'educacion', nombre: 'Escuelas y academias' },
  { id: 'servicios', nombre: 'Talleres, autolavados y salones' },
  { id: 'todos', nombre: 'Cualquier negocio' },
];

export const TIPOS = [
  { id: 'software', nombre: 'Software a medida', icono: 'code', foto: 'tipo-software', desc: 'Sistemas hechos para cómo trabaja tu negocio: inventario, clientes, agendas, cotizaciones.' },
  { id: 'web', nombre: 'Web y apps', icono: 'devices', foto: 'tipo-web', desc: 'Páginas, tiendas en línea y apps para Android y iPhone.' },
  { id: 'ia', nombre: 'Inteligencia artificial', icono: 'robot', foto: 'tipo-ia', desc: 'Asistentes que contestan por WhatsApp, lectura de documentos y automatizaciones.' },
  { id: 'vision', nombre: 'Cámaras y visión', icono: 'security-camera', foto: 'tipo-vision', desc: 'Cámaras que cuentan personas, leen placas y avisan lo que vale la pena revisar.' },
  { id: 'iot', nombre: 'Sensores e IoT', icono: 'broadcast', foto: 'tipo-iot', desc: 'Temperatura, energía, tanques, puertas y motores, con avisos al WhatsApp.' },
  { id: 'pantallas', nombre: 'Pantallas y kioscos', icono: 'monitor', foto: 'tipo-pantallas', desc: 'Pantallas táctiles de pedidos, de cocina, de turnos y menús en el local.' },
  { id: 'tresd', nombre: '3D y escaneo', icono: 'cube-focus', foto: 'tipo-tresd', desc: 'Recorridos 360 y 3D de propiedades, planos con medidas y tomas con dron.' },
  { id: 'pagos', nombre: 'Cobros y facturación', icono: 'credit-card', foto: 'tipo-pagos', desc: 'Pagos con Yappy y tarjeta, punto de venta y factura electrónica.' },
];

const MESA = 'https://jojomunoz.github.io/alphateklab-mesa/';
const RESERVAS = 'https://jojomunoz.github.io/alphateklab-reservas/';

export const SERVICIOS = [
  // ── Restaurantes y cafés ──────────────────────────────────────────────
  {
    id: 'R01',
    slug: 'menu-qr',
    nombre: 'Menú QR a la medida',
    corto: 'Menú QR',
    sectores: ['restaurantes'],
    tipos: ['web'],
    instala: false,
    para: 'Tu carta en el teléfono del cliente, con tus fotos, tus precios y en español e inglés, que cambias tú mismo cuando se acaba un plato.',
    incluye: [
      'Carta con categorías, fotos, alérgenos y precios con ITBMS',
      'Panel para cambiar platos, precios y «agotado» desde el celular',
      'Español e inglés',
      'QR impreso que apunta a una dirección tuya: no deja de funcionar si un día cambias de proveedor',
      'Pensado para acompañar la carta de papel, no para reemplazarla',
    ],
    equipo: [],
    precio: { texto: '$10 al mes', nota: 'precio de la carta sola; pedir y pagar desde la mesa es R02' },
    demo: MESA,
  },
  {
    id: 'R02',
    slug: 'pedir-y-pagar-desde-la-mesa',
    nombre: 'Pedir, llamar al mesero y pagar desde la mesa',
    corto: 'Pedir y pagar en la mesa',
    sectores: ['restaurantes'],
    tipos: ['web', 'pagos'],
    instala: true,
    para: 'El cliente escanea el QR de su mesa, pide, llama al mesero, pide la cuenta y paga con la propina que él elige, sin que nadie se la pregunte.',
    incluye: [
      'QR distinto por mesa: el sistema ya sabe qué mesa es',
      'Pedido que llega a la cocina o a la caja al instante',
      'Botones de «Llamar al mesero» y «Pedir la cuenta»',
      'Cuenta dividida en partes iguales o por plato',
      'Propina elegida por el cliente: 10, 15, 20 % u otra cifra',
    ],
    equipo: ['Placas de mesa con QR impreso', 'Tableta o pantalla en caja o cocina'],
    precio: null,
    demo: MESA,
  },
  {
    id: 'R03',
    slug: 'nfc-en-la-mesa',
    nombre: 'Etiqueta NFC en cada mesa',
    corto: 'NFC en la mesa',
    sectores: ['restaurantes', 'hospedaje'],
    tipos: ['pantallas'],
    instala: true,
    para: 'Además del QR, el cliente acerca el teléfono a la placa y se le abre la carta de su mesa, sin abrir la cámara.',
    incluye: ['Grabado de la dirección de cada mesa en su etiqueta', 'Placa con QR y NFC juntos', 'Bloqueo de escritura para que nadie la cambie'],
    equipo: ['Etiquetas NFC NTAG213 o NTAG215', 'Placas de acrílico o madera'],
    precio: null,
    demo: MESA + 'admin.html#nfc',
  },
  {
    id: 'R04',
    slug: 'mapa-de-mesas-y-cuentas',
    nombre: 'Mapa de mesas y cuentas por mesa',
    corto: 'Mapa de mesas',
    sectores: ['restaurantes'],
    tipos: ['software', 'pagos'],
    instala: false,
    para: 'El plano de tu salón en una pantalla: qué mesa está libre, cuál pidió, cuál llama al mesero y cuánto lleva cada cuenta, para cobrar y facturar desde ahí.',
    incluye: [
      'Editor del plano: mueves, giras y numeras las mesas',
      'Estado de cada mesa en vivo',
      'Cuenta abierta por mesa, con ITBMS desglosado',
      'Cierre de mesa y comprobante',
    ],
    equipo: ['Tableta o computadora en caja'],
    precio: null,
    demo: MESA + 'salon.html',
  },
  {
    id: 'R05',
    slug: 'pantalla-de-cocina',
    nombre: 'Pantalla de cocina',
    corto: 'Pantalla de cocina',
    sectores: ['restaurantes'],
    tipos: ['pantallas', 'software'],
    instala: true,
    para: 'Los pedidos llegan a una pantalla en la cocina con la hora en que entraron, separados por estación, y el cocinero los marca listos con un toque.',
    incluye: ['Comandas por estación (parrilla, fríos, bar)', 'Tiempo de cada comanda a la vista', 'Aviso a la caja o al mesero cuando sale el plato'],
    equipo: ['Pantalla o tableta para cocina, con soporte de pared'],
    precio: null,
    demo: MESA + 'cocina.html',
  },
  {
    id: 'R06',
    slug: 'pantalla-tactil-de-pedidos',
    nombre: 'Pantalla táctil de autopedido',
    corto: 'Pantalla táctil de pedidos',
    sectores: ['restaurantes', 'comercio'],
    tipos: ['pantallas'],
    instala: true,
    para: 'Un kiosco en la entrada donde el cliente arma su pedido y paga, para locales de mostrador o de comida rápida con filas.',
    incluye: ['Carta táctil con fotos grandes', 'Sugerencias para completar el pedido', 'Número de orden y aviso cuando está listo'],
    equipo: ['Pantalla táctil de 22 a 32 pulgadas con pedestal', 'Terminal de pago o pago en caja'],
    precio: null,
    demo: MESA + 'kiosco.html',
  },
  {
    id: 'R07',
    slug: 'pedidos-para-llevar',
    nombre: 'Pedidos a domicilio y para llevar sin comisión por pedido',
    corto: 'Pedidos para llevar',
    sectores: ['restaurantes'],
    tipos: ['web', 'pagos'],
    instala: false,
    para: 'Tu propia página de pedidos con tu carta, para que el cliente pida para llevar o a domicilio sin pasar por una app que cobra por cada pedido.',
    incluye: ['Carta, carrito y horario de atención', 'Zonas de entrega con su costo', 'Pago con tarjeta o Yappy, o contra entrega', 'Aviso del pedido al WhatsApp del local'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'R08',
    slug: 'reservas-de-mesa',
    nombre: 'Reservas de mesa en línea',
    corto: 'Reservas de mesa',
    sectores: ['restaurantes'],
    tipos: ['web', 'software'],
    instala: false,
    para: 'El cliente reserva desde tu página o Instagram y recibe un recordatorio; tú ves las reservas del día sobre el plano del salón.',
    incluye: ['Horarios y capacidad por turno', 'Recordatorio y confirmación por WhatsApp', 'Lista de espera'],
    equipo: [],
    precio: null,
    demo: RESERVAS,
  },
  {
    id: 'R09',
    slug: 'menu-en-pantallas',
    nombre: 'Menú en pantallas del local',
    corto: 'Menú en pantallas',
    sectores: ['restaurantes', 'comercio'],
    tipos: ['pantallas'],
    instala: true,
    para: 'Pantallas sobre el mostrador con la carta, el plato del día y los precios, que cambias desde el celular.',
    incluye: ['Diseño de las pantallas', 'Cambios programados por horario (desayuno, almuerzo)', 'Plato agotado que se oculta solo'],
    equipo: ['Televisores con reproductor pequeño o TV con navegador'],
    precio: null,
    demo: null,
  },
  {
    id: 'R10',
    slug: 'temperatura-de-neveras',
    nombre: 'Sensores de temperatura en neveras y cuartos fríos',
    corto: 'Temperatura de neveras',
    sectores: ['restaurantes', 'comercio', 'salud'],
    tipos: ['iot'],
    instala: true,
    para: 'Un aviso al WhatsApp cuando la nevera pasa de 5 °C o la puerta queda abierta, antes de perder la mercancía, con el registro de temperaturas guardado.',
    incluye: ['Sensores inalámbricos por nevera y congelador', 'Aviso por WhatsApp o correo con el límite que tú eliges', 'Historial descargable para inspecciones'],
    equipo: ['Sensores de temperatura y de puerta', 'Puerta de enlace Wi-Fi'],
    precio: null,
    demo: 'laboratorio/sensores/',
  },

  // ── Tiendas y comercio ────────────────────────────────────────────────
  {
    id: 'C01',
    slug: 'contador-de-personas',
    nombre: 'Contador de personas en la entrada',
    corto: 'Contador de personas',
    sectores: ['comercio', 'restaurantes', 'operacion'],
    tipos: ['vision', 'iot'],
    instala: true,
    para: 'Cuántas personas entran por hora y día, y cuántas compran: con las ventas de la caja sale tu tasa de conversión.',
    incluye: ['Conteo de entradas y salidas por puerta', 'Aforo en vivo con aviso al llegar al máximo', 'Reporte por hora, día y semana'],
    equipo: ['Cámara sobre la puerta o sensor de conteo en el techo'],
    precio: null,
    demo: 'laboratorio/camara/',
  },
  {
    id: 'C02',
    slug: 'mapa-de-calor',
    nombre: 'Mapa de calor del local',
    corto: 'Mapa de calor',
    sectores: ['comercio'],
    tipos: ['vision'],
    instala: true,
    para: 'En qué pasillos se detiene la gente y cuáles nadie recorre, para decidir dónde poner lo que más quieres vender.',
    incluye: ['Mapa de calor por zona y por hora', 'Tiempo promedio de permanencia', 'Comparación antes y después de mover un exhibidor'],
    equipo: ['Cámaras de techo (se reutilizan las que tengas si sirven)'],
    precio: null,
    demo: 'laboratorio/camara/',
  },
  {
    id: 'C03',
    slug: 'alerta-de-filas',
    nombre: 'Aviso de filas en caja',
    corto: 'Aviso de filas',
    sectores: ['comercio', 'restaurantes'],
    tipos: ['vision'],
    instala: true,
    para: 'Cuando hay más de cierto número de personas esperando en caja, le llega un aviso al encargado para abrir otra.',
    incluye: ['Zona de fila marcada en la cámara', 'Aviso por WhatsApp o en una pantalla', 'Reporte de tiempos de espera'],
    equipo: ['Cámara que vea la fila'],
    precio: null,
    demo: 'laboratorio/camara/',
  },
  {
    id: 'C04',
    slug: 'inventario-por-escaneo',
    nombre: 'Inventario por escaneo',
    corto: 'Inventario por escaneo',
    sectores: ['comercio', 'operacion'],
    tipos: ['vision', 'iot', 'software'],
    instala: true,
    para: 'Contar la mercancía sin anotar a mano: etiquetas RFID en la ropa, o reconocer el producto por la etiqueta del estante en abarrotes.',
    incluye: ['Lector RFID de mano o de portal', 'Sistema de inventario conectado al escaneo', 'Diferencias contra lo que dice tu sistema'],
    equipo: ['Etiquetas RFID', 'Lector RFID de mano', 'O teléfono con cámara para leer estantes'],
    precio: null,
    demo: null,
  },
  {
    id: 'C05',
    slug: 'camaras-con-ia-en-caja',
    nombre: 'Cámaras con IA para pérdidas en caja y bodega',
    corto: 'Cámaras contra pérdidas',
    sectores: ['comercio', 'operacion'],
    tipos: ['vision', 'ia'],
    instala: true,
    para: 'La cámara marca los momentos que vale la pena revisar (cajón abierto sin venta, mercancía que sale por la puerta de atrás) para no ver horas de video.',
    incluye: ['Instalación o aprovechamiento de las cámaras existentes', 'Eventos marcados con el clip de video', 'Búsqueda por hora y por cámara'],
    equipo: ['Cámaras IP', 'Grabador con procesamiento local'],
    precio: null,
    demo: null,
  },
  {
    id: 'C06',
    slug: 'tienda-en-linea',
    nombre: 'Tienda en línea',
    corto: 'Tienda en línea',
    sectores: ['comercio', 'todos'],
    tipos: ['web', 'pagos'],
    instala: false,
    para: 'Vende por internet con tu catálogo, cobro con tarjeta o Yappy, y envíos o retiro en tienda.',
    incluye: ['Catálogo con variantes (talla, color)', 'Pasarela de pago panameña', 'Inventario que se descuenta solo', 'Aviso de pedido por correo y WhatsApp'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'C07',
    slug: 'etiquetas-de-precio-electronicas',
    nombre: 'Etiquetas de precio electrónicas',
    corto: 'Precios electrónicos',
    sectores: ['comercio'],
    tipos: ['iot', 'pantallas'],
    instala: true,
    para: 'Los precios del estante cambian desde la computadora, iguales a los de la caja, sin reimprimir etiquetas.',
    incluye: ['Etiquetas de tinta electrónica en los estantes', 'Conexión con tu lista de precios', 'Ofertas programadas'],
    equipo: ['Etiquetas electrónicas', 'Antena en el techo'],
    precio: null,
    demo: null,
  },
  {
    id: 'C08',
    slug: 'programa-de-lealtad',
    nombre: 'Programa de clientes frecuentes',
    corto: 'Clientes frecuentes',
    sectores: ['comercio', 'restaurantes'],
    tipos: ['web', 'software'],
    instala: false,
    para: 'Sellos o puntos en el teléfono del cliente, sin tarjeta de cartón, y un mensaje cuando lleva tiempo sin volver.',
    incluye: ['Tarjeta digital con QR', 'Premios por visitas o por monto', 'Lista de clientes para tus promociones, con su permiso'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'C09',
    slug: 'wifi-para-clientes',
    nombre: 'Wi-Fi para clientes con registro',
    corto: 'Wi-Fi con registro',
    sectores: ['comercio', 'restaurantes', 'hospedaje'],
    tipos: ['iot', 'web'],
    instala: true,
    para: 'El cliente se conecta a tu Wi-Fi con su correo o su WhatsApp, y tú sabes cuántos vuelven, con el consentimiento que pide la ley.',
    incluye: ['Página de entrada con tu marca', 'Límite de tiempo o de velocidad por cliente', 'Red separada de la de la caja'],
    equipo: ['Punto de acceso con portal de registro'],
    precio: null,
    demo: null,
  },

  // ── Clínicas y consultorios ───────────────────────────────────────────
  {
    id: 'S01',
    slug: 'agente-de-citas',
    nombre: 'Agente de citas con recordatorios',
    corto: 'Agente de citas',
    sectores: ['salud', 'todos'],
    tipos: ['software', 'ia'],
    instala: false,
    para: 'La recepción agenda la cita y el sistema le escribe al paciente 2 días o 1 día antes; si no contesta, le vuelve a escribir hasta que confirme o cancele.',
    incluye: [
      'Agenda por profesional y por consultorio, sin citas encimadas',
      'Registro del paciente con su historial de citas',
      'Recordatorio por WhatsApp con botón para confirmar',
      'Reintentos hasta tener respuesta, y aviso a recepción si no la hay',
      'Página para que el paciente pida cita solo',
    ],
    equipo: [],
    precio: null,
    aparte: 'Los recordatorios por WhatsApp los cobra Meta por mensaje: unos US$0,011 cada uno en Panamá, según su tarifa de octubre de 2026. El correo sale casi gratis.',
    demo: RESERVAS,
  },
  {
    id: 'S02',
    slug: 'turnos-en-sala-de-espera',
    nombre: 'Pantalla de turnos en sala de espera',
    corto: 'Turnos en sala de espera',
    sectores: ['salud', 'operacion'],
    tipos: ['pantallas', 'software'],
    instala: true,
    para: 'La pantalla de la sala llama al siguiente paciente por su turno, sin gritar nombres.',
    incluye: ['Turnos por consultorio', 'Llamado con sonido', 'Tiempo de espera estimado'],
    equipo: ['Televisor en la sala de espera'],
    precio: null,
    demo: null,
  },
  {
    id: 'S03',
    slug: 'encuesta-despues-de-la-cita',
    nombre: 'Encuesta después de la cita',
    corto: 'Encuesta después de la cita',
    sectores: ['salud', 'restaurantes', 'hospedaje'],
    tipos: ['software'],
    instala: false,
    para: 'Una pregunta por WhatsApp al día siguiente; si la respuesta es mala, te avisa a ti antes de que llegue a Google.',
    incluye: ['Encuesta corta de una a tres preguntas', 'Aviso inmediato de las respuestas malas', 'Enlace a reseñas de Google para las buenas'],
    equipo: [],
    precio: null,
    demo: null,
  },

  // ── Hospedaje y turismo ───────────────────────────────────────────────
  {
    id: 'H01',
    slug: 'motor-de-reservas',
    nombre: 'Motor de reservas en tu propia página',
    corto: 'Motor de reservas',
    sectores: ['hospedaje'],
    tipos: ['web', 'pagos'],
    instala: false,
    para: 'El huésped ve las fechas libres de cada cabaña o habitación y reserva con depósito en tu página, sin pagar comisión por esa reserva.',
    incluye: ['Calendario por unidad con tarifas por temporada', 'Reserva de varias unidades a la vez', 'Depósito con tarjeta o Yappy', 'Instrucciones de llegada automáticas'],
    equipo: [],
    precio: null,
    demo: RESERVAS + 'alojamiento.html',
  },
  {
    id: 'H02',
    slug: 'sincronizacion-con-booking-y-airbnb',
    nombre: 'Calendario sincronizado con Booking, Airbnb y Expedia, con vigilante',
    corto: 'Calendarios con vigilante',
    sectores: ['hospedaje'],
    tipos: ['software'],
    instala: false,
    para: 'Las fechas que se venden en un canal se cierran en los demás, y si un canal deja de sincronizar, te avisa y cierra la venta en tu página antes de que haya doble reserva.',
    incluye: ['Importación y exportación iCal por unidad', 'Vigilante: aviso si un canal lleva horas sin actualizar', 'Lista de choques de fechas con propuesta para reubicar'],
    equipo: [],
    precio: null,
    demo: RESERVAS + 'alojamiento.html#canales',
  },
  {
    id: 'H03',
    slug: 'cerraduras-con-codigo',
    nombre: 'Cerraduras con código por reserva',
    corto: 'Cerraduras con código',
    sectores: ['hospedaje', 'operacion'],
    tipos: ['iot'],
    instala: true,
    para: 'Cada huésped recibe un código que abre su puerta solo durante su estadía; no hay llaves que entregar ni que se pierdan.',
    incluye: ['Código generado con cada reserva', 'Registro de entradas', 'Código de limpieza separado'],
    equipo: ['Cerraduras electrónicas con teclado y conexión'],
    precio: null,
    demo: null,
  },
  {
    id: 'H04',
    slug: 'check-in-en-linea',
    nombre: 'Registro de huéspedes en línea',
    corto: 'Registro de huéspedes',
    sectores: ['hospedaje'],
    tipos: ['web'],
    instala: false,
    para: 'El huésped llena sus datos y firma antes de llegar, y tú recibes el registro completo sin papel en recepción.',
    incluye: ['Formulario con foto del documento', 'Firma de normas de la casa', 'Datos guardados según la Ley 81 de 2019'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'H05',
    slug: 'consumo-por-cabana',
    nombre: 'Consumo de luz y agua por cabaña',
    corto: 'Consumo por cabaña',
    sectores: ['hospedaje', 'operacion'],
    tipos: ['iot'],
    instala: true,
    para: 'Medidores por unidad para saber cuánto gasta cada cabaña y detectar el aire acondicionado prendido sin nadie o una fuga.',
    incluye: ['Medidor eléctrico por circuito', 'Sensor de nivel del tanque de agua', 'Aviso de consumo fuera de lo normal'],
    equipo: ['Medidores de energía en el tablero', 'Sensor ultrasónico de tanque'],
    precio: null,
    demo: 'laboratorio/sensores/',
  },

  // ── Bienes raíces ─────────────────────────────────────────────────────
  {
    id: 'B01',
    slug: 'recorrido-3d',
    nombre: 'Recorrido 360 y 3D de la propiedad',
    corto: 'Recorrido 360 y 3D',
    sectores: ['inmuebles', 'hospedaje'],
    tipos: ['tresd', 'web'],
    instala: false,
    visita: true,
    para: 'El comprador recorre la propiedad desde su teléfono: con una foto 360 de cada ambiente, o en 3D, caminando por las habitaciones como en un videojuego y con las medidas reales.',
    incluye: ['Fotos 360 de cada ambiente con cámara 360, o escaneo 3D con LiDAR', 'Recorrido para tu página o tu anuncio, en tu dominio', 'Medidas de cada ambiente en la versión 3D'],
    equipo: ['Cámara 360 o teléfono con LiDAR (lo llevamos nosotros)'],
    precio: null,
    demo: 'laboratorio/recorrido-360/',
  },
  {
    id: 'B02',
    slug: 'fotos-de-la-propiedad',
    nombre: 'Fotos profesionales de la propiedad',
    corto: 'Fotos profesionales',
    sectores: ['inmuebles', 'hospedaje'],
    tipos: ['tresd'],
    instala: false,
    visita: true,
    para: 'Fotos de cada ambiente con buena luz, tomadas en la misma visita del recorrido 360 o 3D, listas para tu anuncio.',
    incluye: ['Sesión en la propiedad', 'Fotos editadas listas para anunciar'],
    equipo: [],
    precio: { texto: '+$300', nota: 'como extra del recorrido 360 o 3D' },
    demo: null,
  },
  {
    id: 'B03',
    slug: 'planos-desde-el-escaneo',
    nombre: 'Plano con medidas a partir del escaneo',
    corto: 'Planos con medidas',
    sectores: ['inmuebles', 'operacion'],
    tipos: ['tresd'],
    instala: false,
    visita: true,
    para: 'Del mismo escaneo sale el plano en planta con las medidas de cada ambiente, para el anuncio o para remodelar.',
    incluye: ['Plano en planta en PDF', 'Metros cuadrados por ambiente'],
    equipo: [],
    precio: null,
    demo: 'laboratorio/recorrido-3d/',
  },
  {
    id: 'B04',
    slug: 'agente-de-whatsapp-para-inmobiliarias',
    nombre: 'Agente de WhatsApp para prospectos de bienes raíces',
    corto: 'Agente inmobiliario',
    sectores: ['inmuebles'],
    tipos: ['ia'],
    instala: false,
    para: 'Contesta a cualquier hora las preguntas de los interesados sobre cada propiedad, filtra al que viene en serio y le agenda la visita.',
    incluye: ['Respuestas con los datos reales de tus propiedades', 'Preguntas de filtro (presupuesto, fecha, financiamiento)', 'Visita agendada en tu calendario', 'Paso a una persona cuando hace falta'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'B05',
    slug: 'sitio-de-propiedades',
    nombre: 'Sitio de propiedades con fichas y recorridos',
    corto: 'Sitio de propiedades',
    sectores: ['inmuebles'],
    tipos: ['web'],
    instala: false,
    para: 'Tu propia página de propiedades, con filtros por zona y precio, la ficha de cada una y su recorrido 3D.',
    incluye: ['Fichas con fotos, plano y recorrido', 'Filtros por zona, precio y recámaras', 'Contacto directo a WhatsApp por propiedad'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'B06',
    slug: 'tomas-con-dron',
    nombre: 'Tomas aéreas con dron',
    corto: 'Tomas con dron',
    sectores: ['inmuebles', 'hospedaje'],
    tipos: ['tresd'],
    instala: false,
    visita: true,
    para: 'Vista aérea del terreno, del edificio o del proyecto, para mostrar el entorno y los accesos.',
    incluye: ['Fotos y video aéreo', 'Mapa del terreno a partir de las fotos'],
    equipo: ['Dron (lo llevamos nosotros)'],
    precio: null,
    demo: null,
  },

  // ── Bodegas, oficinas e industria ─────────────────────────────────────
  {
    id: 'I01',
    slug: 'tablero-de-sensores',
    nombre: 'Tablero de sensores del negocio',
    corto: 'Tablero de sensores',
    sectores: ['operacion', 'restaurantes', 'hospedaje'],
    tipos: ['iot', 'software'],
    instala: true,
    para: 'Temperatura, consumo eléctrico, nivel de tanques y puertas en una sola pantalla, con avisos cuando algo se sale de lo normal.',
    incluye: ['Instalación de los sensores', 'Tablero en el teléfono y la computadora', 'Avisos por WhatsApp', 'Historial para comparar meses'],
    equipo: ['Sensores según lo que se quiera medir', 'Puerta de enlace Wi-Fi o LoRa'],
    precio: null,
    demo: 'laboratorio/sensores/',
  },
  {
    id: 'I02',
    slug: 'gps-de-flota',
    nombre: 'GPS de vehículos y rutas',
    corto: 'GPS de flota',
    sectores: ['operacion', 'comercio'],
    tipos: ['iot'],
    instala: true,
    para: 'Dónde está cada camión o moto de reparto, por dónde pasó y cuánto tiempo estuvo detenido.',
    incluye: ['Rastreador por vehículo', 'Mapa en vivo e historial de rutas', 'Aviso de salida de zona'],
    equipo: ['Rastreador GPS con chip de datos'],
    precio: null,
    demo: null,
  },
  {
    id: 'I03',
    slug: 'lectura-de-placas',
    nombre: 'Lectura de placas en estacionamientos',
    corto: 'Lectura de placas',
    sectores: ['operacion', 'comercio', 'hospedaje'],
    tipos: ['vision'],
    instala: true,
    para: 'La cámara lee la placa en la entrada: abre a los autorizados y registra la hora de entrada y salida de cada vehículo.',
    incluye: ['Lista de placas autorizadas', 'Registro de entradas y salidas', 'Conexión con la pluma o el portón'],
    equipo: ['Cámara para lectura de placas', 'Controlador del portón'],
    precio: null,
    demo: null,
  },
  {
    id: 'I04',
    slug: 'control-de-acceso',
    nombre: 'Control de acceso con QR o tarjeta',
    corto: 'Control de acceso',
    sectores: ['operacion', 'salud', 'hospedaje'],
    tipos: ['iot', 'software'],
    instala: true,
    para: 'Empleados, proveedores y visitas entran con un QR o una tarjeta; cada entrada queda registrada y los permisos se quitan desde el teléfono.',
    incluye: ['Lector en la puerta', 'Permisos por persona y horario', 'Pases de visita que vencen solos', 'Registro de asistencia'],
    equipo: ['Lector QR o NFC', 'Cerradura electromagnética'],
    precio: null,
    demo: null,
  },
  {
    id: 'I05',
    slug: 'deteccion-de-equipo-de-seguridad',
    nombre: 'Detección de casco y chaleco',
    corto: 'Casco y chaleco',
    sectores: ['operacion'],
    tipos: ['vision', 'ia'],
    instala: true,
    para: 'La cámara de la zona de trabajo avisa cuando alguien entra sin casco o sin chaleco, con la foto del momento.',
    incluye: ['Zonas marcadas por cámara', 'Aviso con foto', 'Reporte semanal'],
    equipo: ['Cámaras IP', 'Equipo de procesamiento local'],
    precio: null,
    demo: null,
  },
  {
    id: 'I06',
    slug: 'contador-de-produccion',
    nombre: 'Contador de producción en línea',
    corto: 'Contador de producción',
    sectores: ['operacion'],
    tipos: ['vision', 'iot'],
    instala: true,
    para: 'Cuenta los sacos, cajas o piezas que pasan por la banda o salen por el portón, por turno y por hora.',
    incluye: ['Sensor o cámara sobre la línea', 'Conteo por turno', 'Tablero en la oficina'],
    equipo: ['Sensor de barrera o cámara'],
    precio: null,
    demo: 'laboratorio/camara/',
  },

  // ── Cualquier negocio ─────────────────────────────────────────────────
  {
    id: 'T01',
    slug: 'pagina-web',
    nombre: 'Página web',
    corto: 'Página web',
    sectores: ['todos'],
    tipos: ['web'],
    instala: false,
    para: 'La página de tu negocio, rápida en el teléfono, con tu información real y un botón directo a WhatsApp.',
    incluye: ['Diseño propio, no de plantilla', 'Textos y fotos de tu negocio', 'Aparecer en Google con tu nombre y tu zona', 'Dominio y correo con tu nombre'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T02',
    slug: 'software-a-medida',
    nombre: 'Software a medida',
    corto: 'Software a medida',
    sectores: ['todos'],
    tipos: ['software'],
    instala: false,
    para: 'El sistema que tu negocio hace hoy en Excel, en papel o en tres aplicaciones distintas, hecho para cómo trabajas tú.',
    incluye: ['Visita para entender el proceso', 'Versión usable en semanas, no en meses', 'Usuarios y permisos por puesto', 'Respaldo diario de los datos'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T03',
    slug: 'apps',
    nombre: 'Apps para teléfono',
    corto: 'Apps',
    sectores: ['todos'],
    tipos: ['web'],
    instala: false,
    para: 'Una app para tus clientes o tu equipo, en Android y iPhone, que funciona también sin señal cuando hace falta.',
    incluye: ['Android y iPhone', 'Funcionamiento sin conexión', 'Publicación en las tiendas'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T04',
    slug: 'automatizaciones',
    nombre: 'Automatizaciones',
    corto: 'Automatizaciones',
    sectores: ['todos'],
    tipos: ['software', 'ia'],
    instala: false,
    para: 'Lo que alguien copia y pega todos los días (pedidos, cotizaciones, reportes, correos) pasa a hacerse solo.',
    incluye: ['Conexión entre tus herramientas (correo, hojas de cálculo, WhatsApp, tu sistema)', 'Reportes que llegan solos', 'Aviso cuando algo falla'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T05',
    slug: 'chatbot-de-whatsapp',
    nombre: 'Asistente de WhatsApp y del sitio con IA',
    corto: 'Asistente con IA',
    sectores: ['todos'],
    tipos: ['ia'],
    instala: false,
    para: 'Contesta las preguntas de siempre (horario, precios, ubicación, disponibilidad) con tu información, a cualquier hora, y pasa la conversación a una persona cuando hace falta.',
    incluye: [
      'Configuración con tu información: catálogo, horarios, precios y preguntas frecuentes',
      'Toma pedidos o agenda citas',
      'Te pasa la conversación cuando el cliente lo pide',
      'Si te alcanza con el asistente que trae WhatsApp Business, lo configuramos ahí; si no, uno a la medida',
    ],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T06',
    slug: 'cotizador',
    nombre: 'Cotizador con tu inventario',
    corto: 'Cotizador',
    sectores: ['todos', 'comercio'],
    tipos: ['software'],
    instala: false,
    para: 'Tus vendedores arman cotizaciones de varios renglones con tus precios y existencias, y el cliente las recibe en PDF con tu marca.',
    incluye: ['Catálogo con precios y existencias', 'Cotizaciones con renglones, descuentos e ITBMS', 'Aprobación antes de enviar', 'Historial por cliente'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T07',
    slug: 'factura-electronica',
    nombre: 'Conexión con la factura electrónica',
    corto: 'Factura electrónica',
    sectores: ['todos'],
    tipos: ['pagos', 'software'],
    instala: false,
    para: 'Tu sistema de ventas manda cada factura al proveedor autorizado por la DGI, sin volver a escribirla.',
    incluye: ['Conexión con un PAC autorizado', 'Factura enviada al cliente por correo o WhatsApp', 'Notas de crédito'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T08',
    slug: 'tablero-de-ventas',
    nombre: 'Tablero de ventas y operación',
    corto: 'Tablero de ventas',
    sectores: ['todos'],
    tipos: ['software'],
    instala: false,
    para: 'Las cifras que miras cada semana, en una pantalla que se actualiza sola: ventas por día, por producto y por vendedor.',
    incluye: ['Conexión con tu sistema de ventas o tus hojas de cálculo', 'Comparación contra la semana y el mes anteriores', 'Envío automático por correo'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T09',
    slug: 'pagos-en-linea',
    nombre: 'Cobros en línea con tarjeta y Yappy',
    corto: 'Cobros en línea',
    sectores: ['todos'],
    tipos: ['pagos', 'web'],
    instala: false,
    para: 'Enlaces de pago y botón de pago en tu página, con la confirmación conectada a tu sistema.',
    incluye: ['Pasarela panameña', 'Enlaces de pago por WhatsApp', 'Confirmación automática del pago'],
    equipo: [],
    precio: null,
    demo: null,
  },

  // ── añadidos: punto de venta, red, video, 3D de productos, industria ──
  {
    id: 'R11',
    slug: 'punto-de-venta',
    nombre: 'Punto de venta para restaurante o tienda',
    corto: 'Punto de venta (POS)',
    sectores: ['restaurantes', 'comercio'],
    tipos: ['software', 'pagos', 'pantallas'],
    instala: true,
    para: 'La caja de tu negocio: ventas, cierre de turno, inventario que se descuenta solo y la factura electrónica conectada al proveedor autorizado.',
    incluye: ['Ventas por mesa, mostrador o para llevar', 'Cierre de caja por turno y por cajero', 'Inventario e insumos', 'Factura electrónica con PAC'],
    equipo: ['Computadora o tableta de caja', 'Impresora de tickets', 'Cajón de dinero', 'Lector de código de barras'],
    precio: null,
    demo: null,
  },
  {
    id: 'C10',
    slug: 'productos-en-3d',
    nombre: 'Productos en 3D y realidad aumentada',
    corto: 'Productos en 3D',
    sectores: ['comercio', 'inmuebles'],
    tipos: ['tresd', 'web'],
    instala: false,
    para: 'El cliente gira el producto en tu página y lo pone en su sala con la cámara del teléfono para ver cómo queda: muebles, electrodomésticos, adornos.',
    incluye: ['Modelo 3D del producto a partir de fotos o del fabricante', 'Visor en tu página o tienda en línea', 'Vista en realidad aumentada en Android y iPhone'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'I07',
    slug: 'sensores-en-motores',
    nombre: 'Sensores de vibración y temperatura en motores',
    corto: 'Sensores en motores',
    sectores: ['operacion'],
    tipos: ['iot'],
    instala: true,
    para: 'Un aviso cuando un motor, una bomba o un compresor empieza a vibrar o a calentarse más de lo normal, antes de que se dañe y pare la producción.',
    incluye: ['Sensores en los equipos críticos', 'Línea base de cada equipo', 'Aviso por WhatsApp con la tendencia'],
    equipo: ['Sensores inalámbricos de vibración y temperatura', 'Puerta de enlace'],
    precio: null,
    demo: 'laboratorio/sensores/',
  },
  {
    id: 'I08',
    slug: 'basculas-conectadas',
    nombre: 'Básculas y medidores conectados',
    corto: 'Básculas conectadas',
    sectores: ['operacion', 'comercio'],
    tipos: ['iot', 'software'],
    instala: true,
    para: 'Lo que pesa la báscula de la entrada o marca el medidor del tanque entra solo a tu sistema, sin que nadie lo copie a mano.',
    incluye: ['Conexión de la báscula o el medidor', 'Registro por camión, lote o turno', 'Reporte diario'],
    equipo: ['Adaptador de la báscula a la red'],
    precio: null,
    demo: null,
  },
  {
    id: 'T10',
    slug: 'red-y-wifi-del-negocio',
    nombre: 'Red e internet del negocio',
    corto: 'Red y Wi-Fi',
    sectores: ['todos'],
    tipos: ['iot'],
    instala: true,
    para: 'Wi-Fi que llega a todo el local, una red para la caja y las cámaras separada de la de los clientes, y un respaldo cuando se cae el internet.',
    incluye: ['Revisión del local y de la señal', 'Puntos de acceso y cableado', 'Red de clientes separada', 'Internet de respaldo para la caja'],
    equipo: ['Puntos de acceso', 'Enrutador', 'Cableado'],
    precio: null,
    demo: null,
  },
  {
    id: 'T11',
    slug: 'camaras-de-seguridad',
    nombre: 'Cámaras de seguridad con acceso desde el teléfono',
    corto: 'Cámaras de seguridad',
    sectores: ['todos'],
    tipos: ['vision'],
    instala: true,
    para: 'Cámaras en el local que ves en vivo desde el teléfono, con grabación de varios días y búsqueda por hora.',
    incluye: ['Ubicación de las cámaras según el local', 'Grabación local de varios días', 'Acceso desde el teléfono con usuario por persona'],
    equipo: ['Cámaras IP', 'Grabador', 'Disco duro'],
    precio: null,
    demo: null,
  },

  // ── añadidos del 3-oct (2): escuelas, talleres y salones, y más software para cualquier negocio ──
  {
    id: 'E01', slug: 'matricula-y-mensualidades', nombre: 'Matrícula y cobro de mensualidades en línea', corto: 'Matrícula y mensualidades',
    sectores: ['educacion'], tipos: ['software', 'pagos'], instala: false,
    para: 'Los padres matriculan y pagan la mensualidad desde el teléfono con Yappy o tarjeta; tú ves quién está al día sin perseguir a nadie.',
    incluye: ['Formulario de matrícula con documentos', 'Cobro de mensualidades con recordatorio', 'Estado de cuenta por estudiante', 'Reporte de morosidad'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'E02', slug: 'asistencia-con-qr', nombre: 'Asistencia con QR o tarjeta', corto: 'Asistencia con QR',
    sectores: ['educacion', 'operacion'], tipos: ['iot', 'software'], instala: true,
    para: 'Estudiantes o empleados marcan la entrada con su QR o tarjeta, y si alguien no llegó, se avisa a quien corresponda.',
    incluye: ['Lector en la entrada', 'Asistencia por día y por grupo', 'Aviso a padres o supervisores'],
    equipo: ['Lector QR o de tarjeta', 'Tableta o pantalla en la entrada'], precio: null, demo: null,
  },
  {
    id: 'E03', slug: 'avisos-a-padres', nombre: 'Avisos a padres por WhatsApp', corto: 'Avisos a padres',
    sectores: ['educacion'], tipos: ['software', 'ia'], instala: false,
    para: 'Circulares, notas, recordatorios de pago y avisos de último momento que llegan al WhatsApp de cada familia.',
    incluye: ['Envío por grupo, grado o estudiante', 'Confirmación de lectura', 'Respuestas automáticas a las preguntas de siempre'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'V01', slug: 'turnos-y-aviso-de-listo', nombre: 'Turnos en línea y aviso cuando está listo', corto: 'Turnos y aviso de listo',
    sectores: ['servicios'], tipos: ['software'], instala: false,
    para: 'El cliente del autolavado o del taller saca turno, ve cuántos tiene adelante y recibe un WhatsApp cuando su carro está listo.',
    incluye: ['Turno desde el teléfono o en el local', 'Fila en vivo', 'Aviso de listo por WhatsApp'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'V02', slug: 'ordenes-de-trabajo', nombre: 'Órdenes de trabajo del taller', corto: 'Órdenes de trabajo',
    sectores: ['servicios'], tipos: ['software'], instala: false,
    para: 'Recepción del vehículo con fotos, presupuesto que el cliente aprueba por WhatsApp, estado del trabajo e historial por placa.',
    incluye: ['Fotos del vehículo al recibirlo', 'Presupuesto con aprobación del cliente', 'Historial por placa', 'Aviso de entrega'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'V03', slug: 'agenda-para-salones', nombre: 'Agenda para barberías y salones', corto: 'Agenda para salones',
    sectores: ['servicios'], tipos: ['software'], instala: false,
    para: 'Citas por barbero o estilista, recordatorio por WhatsApp y seña en línea para que no se pierda el espacio.',
    incluye: ['Agenda por profesional y servicio', 'Recordatorio y confirmación', 'Seña con Yappy o tarjeta'],
    equipo: [], precio: null, demo: 'https://jojomunoz.github.io/alphateklab-reservas/',
  },
  {
    id: 'S04', slug: 'videoconsulta', nombre: 'Videoconsulta con cobro previo', corto: 'Videoconsulta',
    sectores: ['salud'], tipos: ['software', 'pagos'], instala: false,
    para: 'El paciente agenda, paga y entra a la consulta por video desde el enlace que le llega, sin instalar nada.',
    incluye: ['Sala de video por cita', 'Cobro antes de la consulta', 'Recordatorio con el enlace'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'S05', slug: 'expediente-del-paciente', nombre: 'Expediente digital del paciente', corto: 'Expediente digital',
    sectores: ['salud'], tipos: ['software'], instala: false,
    para: 'La historia del paciente, sus citas, fotos de control y documentos en un solo lugar, con acceso solo para quien debe verla.',
    incluye: ['Ficha por paciente con historial', 'Fotos de control por fecha', 'Permisos por persona', 'Consentimiento según la Ley 81 de 2019'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'H06', slug: 'domotica-para-alquileres', nombre: 'Luces, aire y cerraduras desde el teléfono', corto: 'Domótica para alquileres',
    sectores: ['hospedaje'], tipos: ['iot'], instala: true,
    para: 'Apagas el aire de la cabaña que quedó vacía, prendes las luces antes de que llegue el huésped y abres la puerta desde donde estés.',
    incluye: ['Interruptores y enchufes inteligentes', 'Control del aire acondicionado', 'Escenas por reserva (llegada, salida)'],
    equipo: ['Interruptores inteligentes', 'Control infrarrojo para el aire', 'Puerta de enlace Wi-Fi'], precio: null, demo: null,
  },
  {
    id: 'C11', slug: 'catalogo-por-whatsapp', nombre: 'Catálogo y pedidos por WhatsApp', corto: 'Pedidos por WhatsApp',
    sectores: ['comercio', 'restaurantes'], tipos: ['web', 'ia'], instala: false,
    para: 'Tu catálogo con precios y fotos en un enlace; el cliente arma el pedido y te llega ordenado al WhatsApp, listo para cobrar.',
    incluye: ['Catálogo con fotos, precios y existencias', 'Pedido que llega armado al WhatsApp', 'Cobro con enlace de pago'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'I09', slug: 'energia-solar-y-consumo', nombre: 'Medición de energía solar y consumo', corto: 'Energía y paneles solares',
    sectores: ['operacion', 'hospedaje'], tipos: ['iot'], instala: true,
    para: 'Cuánto producen tus paneles, cuánto consume cada área y cuánto te ahorras al mes, en una pantalla.',
    incluye: ['Medidores por circuito', 'Lectura del inversor solar', 'Reporte mensual de ahorro'],
    equipo: ['Medidores de energía con pinza', 'Puerta de enlace'], precio: null, demo: 'laboratorio/sensores/',
  },
  {
    id: 'I10', slug: 'inspeccion-con-dron', nombre: 'Inspección con dron de techos, obras y terrenos', corto: 'Inspección con dron',
    sectores: ['operacion'], tipos: ['tresd'], instala: false, visita: true,
    para: 'Revisar un techo, el avance de una obra o un terreno grande sin andamios ni caminar horas, con fotos y mapa del área.',
    incluye: ['Vuelo y fotos de alta resolución', 'Mapa del área a partir de las fotos', 'Informe con lo encontrado'],
    equipo: ['Dron (lo llevamos nosotros)'], precio: null, demo: null,
  },
  {
    id: 'T12', slug: 'correo-y-dominio', nombre: 'Correo y dominio con el nombre de tu negocio', corto: 'Correo y dominio',
    sectores: ['todos'], tipos: ['web'], instala: false,
    para: 'ventas@tunegocio.com en vez de un Gmail personal, configurado en el teléfono y la computadora de cada persona.',
    incluye: ['Registro del dominio a nombre de tu negocio', 'Cuentas de correo por persona', 'Configuración en sus equipos'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T13', slug: 'negocio-en-google', nombre: 'Tu negocio en Google Maps y reseñas', corto: 'Google Maps y reseñas',
    sectores: ['todos'], tipos: ['web'], instala: false,
    para: 'Que aparezcas cuando te buscan cerca, con horario, fotos, teléfono y reseñas, y que respondas a cada reseña.',
    incluye: ['Perfil de negocio de Google completo', 'Fotos y horario al día', 'Pedido de reseñas a tus clientes'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T14', slug: 'inventario-y-compras', nombre: 'Sistema de inventario y compras', corto: 'Inventario y compras',
    sectores: ['todos', 'comercio', 'operacion'], tipos: ['software'], instala: false,
    para: 'Entradas, salidas y existencias al día, aviso cuando algo se está acabando y órdenes de compra a tus proveedores.',
    incluye: ['Existencias por bodega', 'Mínimos y aviso de reposición', 'Órdenes de compra', 'Lector de código de barras'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T15', slug: 'seguimiento-de-clientes', nombre: 'Seguimiento de clientes y ventas', corto: 'Clientes y ventas (CRM)',
    sectores: ['todos'], tipos: ['software'], instala: false,
    para: 'Cada cliente con su historial, en qué etapa va cada venta y qué toca hacer hoy, para que ninguna se enfríe.',
    incluye: ['Ficha por cliente', 'Embudo de ventas por etapa', 'Recordatorios de seguimiento', 'Reportes por vendedor'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T16', slug: 'portal-de-clientes', nombre: 'Portal para tus clientes', corto: 'Portal de clientes',
    sectores: ['todos'], tipos: ['web', 'software'], instala: false,
    para: 'Tus clientes entran con su usuario y ven sus pedidos, facturas, documentos y el estado de lo que te encargaron.',
    incluye: ['Acceso por cliente', 'Pedidos, facturas y documentos', 'Estado de cada trabajo'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T17', slug: 'firma-de-documentos', nombre: 'Firma de documentos en línea', corto: 'Firma de documentos',
    sectores: ['todos'], tipos: ['software'], instala: false,
    para: 'Contratos y formularios que el cliente firma desde el teléfono, con registro de quién firmó y cuándo.',
    incluye: ['Envío del documento por enlace', 'Firma desde el teléfono', 'Registro de quién y cuándo', 'Para firma con valor legal pleno, conexión con un proveedor acreditado'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T18', slug: 'respaldo-y-seguridad', nombre: 'Respaldo de datos y seguridad informática', corto: 'Respaldo y seguridad',
    sectores: ['todos'], tipos: ['software'], instala: true,
    para: 'Copias automáticas de lo importante fuera de la oficina, contraseñas en orden y equipos protegidos, para que un disco dañado no te cueste el negocio.',
    incluye: ['Respaldo automático diario', 'Prueba de restauración', 'Gestor de contraseñas para el equipo', 'Revisión de equipos y accesos'],
    equipo: ['Disco o servicio de respaldo'], precio: null, demo: null,
  },
  {
    id: 'T19', slug: 'soporte-tecnico', nombre: 'Soporte técnico para tu oficina', corto: 'Soporte técnico',
    sectores: ['todos'], tipos: ['software'], instala: true,
    para: 'Alguien a quien escribirle cuando la impresora no imprime, el correo no sale o una computadora está lenta.',
    incluye: ['Atención por WhatsApp y remota', 'Visitas cuando hace falta', 'Inventario de equipos y licencias'],
    equipo: ['Lo que haga falta reparar o reemplazar'], precio: null, demo: null,
  },
  {
    id: 'T20', slug: 'conexion-entre-sistemas', nombre: 'Conexión entre sistemas', corto: 'Integraciones (APIs)',
    sectores: ['todos'], tipos: ['software'], instala: false,
    para: 'Que tu tienda, tu sistema de ventas, tu contabilidad, Yappy o el banco se pasen los datos solos.',
    incluye: ['Conexión por API entre tus sistemas', 'Sincronización programada', 'Aviso cuando algo no cuadra'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T21', slug: 'lectura-de-documentos-con-ia', nombre: 'Lectura de facturas y documentos con IA', corto: 'Lectura de documentos con IA',
    sectores: ['todos'], tipos: ['ia', 'software'], instala: false,
    para: 'Fotos o PDF de facturas, órdenes y formularios que se convierten solos en datos dentro de tu sistema o tu hoja de cálculo.',
    incluye: ['Lectura de facturas, órdenes y formularios', 'Revisión de lo dudoso antes de guardar', 'Exportación a tu sistema o a Excel'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T22', slug: 'capacitacion-en-ia', nombre: 'Capacitación en IA para tu equipo', corto: 'Capacitación en IA',
    sectores: ['todos'], tipos: ['ia'], instala: false,
    para: 'Una sesión práctica para que tu equipo use la IA en su trabajo de todos los días: redactar, resumir, cotizar y analizar.',
    incluye: ['Taller con ejemplos de tu propio negocio', 'Guía de qué datos no subir', 'Plantillas para las tareas de siempre'],
    equipo: [], precio: null, demo: null,
  },
];
