// Catálogo de servicios de alphateklab. De aquí salen la portada, las fichas y el cotizador
// (herramientas/generar.mjs escribe el HTML; las pruebas en pruebas/ validan este archivo).
//
// Reglas del contenido (ver CLAUDE.md):
// - precio: solo los que decidieron los socios. Todo lo demás va como null y se muestra «A cotizar».
// - demo: ruta relativa a una demo que existe en este repo o URL de otro repo de alphateklab.
// - instala: siempre false. Desde oct-2026 alphateklab hace solo software: no vende ni instala equipos ni va a
//   tomar fotos, escanear o volar un dron (js/catalogo-reglas.mjs no deja generar con instala: true ni con visita).
//   Lo que funciona en un equipo (la tableta de la cocina, el televisor de la sala) usa el que el negocio ya tiene.
// - equipo: siempre vacío, por lo mismo; lo que el negocio necesita tener va en «necesitas» de datos/fichas.mjs.
// - aparte: costo que cobra un tercero y no alphateklab (p. ej. mensajes de WhatsApp), con su fuente en el informe.

// «Bodegas, oficinas e industria» se juntó con «Cualquier negocio» (oct-2026): sin los sensores, el GPS, las cámaras y
// el control de acceso le quedaban dos servicios, y los dos ya sirven a cualquier negocio.
export const SECTORES = [
  { id: 'restaurantes', nombre: 'Restaurantes y cafés', corto: 'Restaurantes' },
  { id: 'comercio', nombre: 'Tiendas, minisúper y comercio', corto: 'Tiendas y minisúper' },
  { id: 'salud', nombre: 'Clínicas y consultorios', corto: 'Clínicas' },
  { id: 'hospedaje', nombre: 'Hospedaje y turismo', corto: 'Hospedaje' },
  { id: 'inmuebles', nombre: 'Bienes raíces', corto: 'Bienes raíces' },
  { id: 'educacion', nombre: 'Escuelas y academias', corto: 'Escuelas' },
  { id: 'servicios', nombre: 'Talleres, autolavados y salones', corto: 'Talleres y salones' },
  { id: 'todos', nombre: 'Cualquier negocio', corto: 'Cualquier negocio' },
];

export const TIPOS = [
  { id: 'software', nombre: 'Software a medida', icono: 'code', foto: 'tipo-software', desc: 'Sistemas hechos para cómo trabaja tu negocio: inventario, clientes, agendas, cotizaciones.' },
  { id: 'web', nombre: 'Web y apps', icono: 'devices', foto: 'tipo-web', desc: 'Páginas, tiendas en línea y apps para Android y iPhone.' },
  { id: 'ia', nombre: 'Inteligencia artificial', icono: 'chat-circle-dots', foto: 'tipo-ia', desc: 'Asistentes que contestan por WhatsApp, lectura de documentos y automatizaciones.' },
  { id: 'pagos', nombre: 'Cobros y facturación', icono: 'credit-card', foto: 'tipo-pagos', desc: 'Pagos con Yappy y tarjeta, punto de venta y factura electrónica.' },
];

const MESA = 'https://jojomunoz.github.io/alphateklab-mesa/';
const RESERVAS = 'https://jojomunoz.github.io/alphateklab-reservas/';

// «icono»: solo en los servicios donde un ícono propio dice más que el de su tipo (revisión del 3-oct: las agendas
// llevaban el de código); los demás usan el de su tipo.
export const SERVICIOS = [
  // ── Restaurantes y cafés ──────────────────────────────────────────────
  {
    id: 'R01',
    icono: 'qr-code',
    slug: 'menu-qr',
    nombre: 'Menú QR a la medida',
    corto: 'Menú QR',
    sectores: ['restaurantes'],
    tipos: ['web'],
    instala: false,
    para: 'Tu carta en el teléfono del cliente, con tus fotos, tus precios y en español e inglés, que cambias tú mismo cuando se acaba un plato.',
    incluye: [
      'Carta con categorías, fotos, alérgenos y precios con ITBMS',
      'Panel para cambiar platos, precios y «agotado» desde el celular',
      'Español e inglés',
      'El QR listo para imprimir, apuntando a una dirección tuya: no deja de funcionar si un día cambias de proveedor',
      'Pensado para acompañar la carta de papel, no para reemplazarla',
    ],
    equipo: [],
    precio: { texto: '$10 al mes', nota: 'precio de la carta sola; pedir y pagar desde la mesa se cotiza aparte' },
    demo: MESA,
  },
  {
    id: 'R02',
    icono: 'fork-knife',
    slug: 'pedir-y-pagar-desde-la-mesa',
    nombre: 'Pedir, llamar al mesero y pagar desde la mesa',
    corto: 'Pedir y pagar en la mesa',
    sectores: ['restaurantes'],
    tipos: ['web', 'pagos'],
    instala: false,
    para: 'El cliente escanea el QR de su mesa, pide, llama al mesero, pide la cuenta y paga con la propina que él elige, sin que nadie se la pregunte.',
    incluye: [
      'Un QR distinto por mesa, listo para imprimir: el sistema ya sabe qué mesa es',
      'Pedido que llega al instante a la tableta o la computadora de la cocina o de la caja',
      'Botones de «Llamar al mesero» y «Pedir la cuenta»',
      'Cuenta dividida en partes iguales o por plato',
      'Propina elegida por el cliente: 10, 15, 20 % u otra cifra',
    ],
    equipo: [],
    precio: null,
    demo: MESA,
  },
  {
    id: 'R04',
    slug: 'mapa-de-mesas-y-cuentas',
    nombre: 'Mapa de mesas y cuentas por mesa',
    corto: 'Mapa de mesas',
    sectores: ['restaurantes'],
    tipos: ['software', 'pagos'],
    instala: false,
    para: 'El plano de tu salón en una pantalla: qué mesa está libre, cuál pidió, cuál llama al mesero y cuánto lleva cada cuenta, para cobrar y facturar desde ahí.',
    incluye: [
      'Editor del plano: mueves, giras y numeras las mesas',
      'Estado de cada mesa en vivo',
      'Cuenta abierta por mesa, con ITBMS desglosado',
      'Cierre de mesa y comprobante',
      'Funciona en la tableta o la computadora que ya tienes en la caja',
    ],
    equipo: [],
    precio: null,
    demo: MESA + 'salon.html',
  },
  {
    id: 'R05',
    slug: 'pantalla-de-cocina',
    nombre: 'Pantalla de cocina',
    corto: 'Pantalla de cocina',
    sectores: ['restaurantes'],
    tipos: ['software'],
    instala: false,
    para: 'Los pedidos llegan a la tableta o la pantalla de tu cocina con la hora en que entraron, separados por estación, y el cocinero los marca listos con un toque.',
    incluye: ['Comandas por estación (parrilla, fríos, bar)', 'Tiempo de cada comanda a la vista', 'Aviso a la caja o al mesero cuando sale el plato', 'Funciona en el navegador de una tableta o una computadora que ya tengas'],
    equipo: [],
    precio: null,
    demo: MESA + 'cocina.html',
  },
  {
    id: 'R07',
    slug: 'pedidos-para-llevar',
    nombre: 'Pedidos a domicilio y para llevar sin comisión por pedido',
    corto: 'Pedidos para llevar',
    sectores: ['restaurantes'],
    tipos: ['web', 'pagos'],
    instala: false,
    para: 'Tu propia página de pedidos con tu carta, para que el cliente pida para llevar o a domicilio sin pasar por una app que cobra por cada pedido.',
    incluye: ['Carta, carrito y horario de atención', 'Zonas de entrega con su costo', 'Pago con tarjeta o Yappy, o contra entrega', 'Aviso del pedido al WhatsApp del local'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'R08',
    icono: 'calendar-check',
    slug: 'reservas-de-mesa',
    nombre: 'Reservas de mesa en línea',
    corto: 'Reservas de mesa',
    sectores: ['restaurantes'],
    tipos: ['web', 'software'],
    instala: false,
    para: 'El cliente reserva desde tu página o Instagram y recibe un recordatorio; tú ves las reservas del día sobre el plano del salón.',
    incluye: ['Horarios y capacidad por turno', 'Recordatorio y confirmación por WhatsApp', 'Lista de espera'],
    equipo: [],
    precio: null,
    demo: RESERVAS,
  },

  // ── Tiendas y comercio ────────────────────────────────────────────────
  {
    id: 'C06',
    slug: 'tienda-en-linea',
    nombre: 'Tienda en línea',
    corto: 'Tienda en línea',
    sectores: ['comercio', 'todos'],
    tipos: ['web', 'pagos'],
    instala: false,
    para: 'Vende por internet con tu catálogo, cobro con tarjeta o Yappy, y envíos o retiro en tienda.',
    incluye: ['Catálogo con variantes (talla, color)', 'Pasarela de pago panameña', 'Inventario que se descuenta solo', 'Aviso de pedido por correo y WhatsApp'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'C08',
    icono: 'handshake',
    slug: 'programa-de-lealtad',
    nombre: 'Programa de clientes frecuentes',
    corto: 'Clientes frecuentes',
    sectores: ['comercio', 'restaurantes'],
    tipos: ['web', 'software'],
    instala: false,
    para: 'Sellos o puntos en el teléfono del cliente, sin tarjeta de cartón, y un mensaje cuando lleva tiempo sin volver.',
    incluye: ['Tarjeta digital con QR', 'Premios por visitas o por monto', 'Lista de clientes para tus promociones, con su permiso'],
    equipo: [],
    precio: null,
    demo: null,
  },

  // ── Clínicas y consultorios ───────────────────────────────────────────
  {
    id: 'S01',
    icono: 'calendar-check',
    slug: 'agente-de-citas',
    nombre: 'Agente de citas con recordatorios',
    corto: 'Agente de citas',
    sectores: ['salud', 'todos'],
    tipos: ['software', 'ia'],
    instala: false,
    para: 'La recepción agenda la cita y el sistema le escribe al paciente 2 días o 1 día antes; si no contesta, le vuelve a escribir hasta que confirme o cancele.',
    incluye: [
      'Agenda por profesional y por consultorio, sin citas encimadas',
      'Registro del paciente con su historial de citas',
      'Recordatorio por WhatsApp con botón para confirmar',
      'Reintentos hasta tener respuesta, y aviso a recepción si no la hay',
      'Página para que el paciente pida cita solo',
    ],
    equipo: [],
    precio: null,
    aparte: 'Los recordatorios por WhatsApp los cobra Meta por mensaje: unos US$0.011 cada uno en Panamá, según su tarifa de octubre de 2026. El correo sale casi gratis.',
    demo: RESERVAS,
  },
  {
    id: 'S02',
    slug: 'turnos-en-sala-de-espera',
    nombre: 'Pantalla de turnos en sala de espera',
    corto: 'Turnos en sala de espera',
    sectores: ['salud', 'todos'],
    tipos: ['software'],
    instala: false,
    para: 'El televisor o la pantalla que ya tienes en la sala de espera llama al siguiente paciente por su turno, sin gritar nombres.',
    incluye: ['Turnos por consultorio', 'Llamado con sonido', 'Tiempo de espera estimado', 'Funciona en un televisor con navegador o en una computadora conectada a él'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'S03',
    slug: 'encuesta-despues-de-la-cita',
    nombre: 'Encuesta después de la visita',
    corto: 'Encuesta después de la visita',
    sectores: ['salud', 'restaurantes', 'hospedaje'],
    tipos: ['software'],
    instala: false,
    para: 'Una pregunta por WhatsApp al día siguiente; si la respuesta es mala, te avisa a ti antes de que llegue a Google.',
    incluye: ['Encuesta corta de una a tres preguntas', 'Aviso inmediato de las respuestas malas', 'Enlace a reseñas de Google para las buenas'],
    equipo: [],
    precio: null,
    demo: null,
  },

  // ── Hospedaje y turismo ───────────────────────────────────────────────
  {
    id: 'H01',
    icono: 'calendar-check',
    slug: 'motor-de-reservas',
    nombre: 'Motor de reservas en tu propia página',
    corto: 'Motor de reservas',
    sectores: ['hospedaje'],
    tipos: ['web', 'pagos'],
    instala: false,
    para: 'El huésped ve las fechas libres de cada cabaña o habitación y reserva con depósito en tu página, sin pagar comisión por esa reserva.',
    incluye: ['Calendario por unidad con tarifas por temporada', 'Reserva de varias unidades a la vez', 'Depósito con tarjeta o Yappy', 'Instrucciones de llegada automáticas'],
    equipo: [],
    precio: null,
    demo: RESERVAS + 'alojamiento.html',
  },
  {
    id: 'H02',
    icono: 'calendar-check',
    slug: 'sincronizacion-con-booking-y-airbnb',
    nombre: 'Calendario sincronizado con Booking, Airbnb y Expedia, con vigilante',
    corto: 'Aviso de calendario caído',
    sectores: ['hospedaje'],
    tipos: ['software'],
    instala: false,
    para: 'Las fechas que se venden en un canal se cierran en los demás, y si un canal deja de sincronizar, te avisa y cierra la venta en tu página antes de que haya doble reserva.',
    incluye: ['Importación y exportación iCal por unidad', 'Vigilante: aviso si un canal lleva horas sin actualizar', 'Lista de choques de fechas con propuesta para reubicar'],
    equipo: [],
    precio: null,
    demo: RESERVAS + 'alojamiento.html#canales',
  },
  {
    id: 'H04',
    icono: 'bed',
    slug: 'check-in-en-linea',
    nombre: 'Registro de huéspedes en línea',
    corto: 'Registro de huéspedes',
    sectores: ['hospedaje'],
    tipos: ['web'],
    instala: false,
    para: 'El huésped llena sus datos y firma antes de llegar, y tú recibes el registro completo sin papel en recepción.',
    incluye: ['Formulario con foto del documento', 'Firma de normas de la casa', 'Datos guardados según la Ley 81 de 2019'],
    equipo: [],
    precio: null,
    demo: null,
  },

  // ── Bienes raíces ─────────────────────────────────────────────────────
  {
    id: 'B04',
    icono: 'whatsapp-logo',
    slug: 'agente-de-whatsapp-para-inmobiliarias',
    nombre: 'Agente de WhatsApp para prospectos de bienes raíces',
    corto: 'Bot de prospectos en WhatsApp',
    sectores: ['inmuebles'],
    tipos: ['ia'],
    instala: false,
    para: 'Contesta a cualquier hora las preguntas de los interesados sobre cada propiedad, filtra al que viene en serio y le agenda la visita.',
    incluye: ['Respuestas con los datos reales de tus propiedades', 'Preguntas de filtro (presupuesto, fecha, financiamiento)', 'Visita agendada en tu calendario', 'Paso a una persona cuando hace falta'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'B05',
    slug: 'sitio-de-propiedades',
    nombre: 'Sitio de propiedades con fichas y filtros',
    corto: 'Sitio de propiedades',
    sectores: ['inmuebles'],
    tipos: ['web'],
    instala: false,
    para: 'Tu propia página de propiedades, con filtros por zona y precio, y la ficha de cada una con sus fotos, su plano y el video o el recorrido virtual que ya tengas.',
    incluye: ['Fichas con tus fotos y planos, y el video o el recorrido virtual si ya lo tienes', 'Filtros por zona, precio y recámaras', 'Contacto directo a WhatsApp por propiedad'],
    equipo: [],
    precio: null,
    demo: null,
  },

  // ── Cualquier negocio ─────────────────────────────────────────────────
  {
    id: 'T01',
    slug: 'pagina-web',
    nombre: 'Página web',
    corto: 'Página web',
    sectores: ['todos'],
    tipos: ['web'],
    instala: false,
    para: 'La página de tu negocio, rápida en el teléfono, con tu información real y un botón directo a WhatsApp.',
    incluye: ['Diseño propio, no de plantilla', 'Textos y fotos de tu negocio', 'Aparecer en Google con tu nombre y tu zona', 'Dominio y correo con tu nombre'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T02',
    slug: 'software-a-medida',
    nombre: 'Software a medida',
    corto: 'Software a medida',
    sectores: ['todos'],
    tipos: ['software'],
    instala: false,
    para: 'El sistema que tu negocio hace hoy en Excel, en papel o en tres aplicaciones distintas, hecho para cómo trabajas tú.',
    incluye: ['Visita para entender el proceso', 'Una primera versión para usar mientras se termina el resto', 'Usuarios y permisos por puesto', 'Respaldo diario de los datos'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T03',
    slug: 'apps',
    nombre: 'Apps para teléfono',
    corto: 'Apps',
    sectores: ['todos'],
    tipos: ['web'],
    instala: false,
    para: 'Una app para tus clientes o tu equipo, en Android y iPhone, que funciona también sin señal cuando hace falta.',
    incluye: ['Android y iPhone', 'Funcionamiento sin conexión', 'Publicación en las tiendas'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T04',
    icono: 'robot',
    slug: 'automatizaciones',
    nombre: 'Automatizaciones',
    corto: 'Automatizaciones',
    sectores: ['todos'],
    tipos: ['software', 'ia'],
    instala: false,
    para: 'Lo que alguien copia y pega todos los días (pedidos, cotizaciones, reportes, correos) pasa a hacerse solo.',
    incluye: ['Conexión entre tus herramientas (correo, hojas de cálculo, WhatsApp, tu sistema)', 'Reportes que llegan solos', 'Aviso cuando algo falla'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T05',
    icono: 'whatsapp-logo',
    slug: 'chatbot-de-whatsapp',
    nombre: 'Asistente de WhatsApp y del sitio con IA',
    corto: 'Asistente con IA',
    sectores: ['todos'],
    tipos: ['ia'],
    instala: false,
    para: 'Contesta las preguntas de siempre (horario, precios, ubicación, disponibilidad) con tu información, a cualquier hora, y pasa la conversación a una persona cuando hace falta.',
    incluye: [
      'Configuración con tu información: catálogo, horarios, precios y preguntas frecuentes',
      'Toma pedidos o agenda citas',
      'Te pasa la conversación cuando el cliente lo pide',
      'Si te alcanza con el asistente que trae WhatsApp Business, lo configuramos ahí; si no, uno a la medida',
    ],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T06',
    slug: 'cotizador',
    nombre: 'Cotizador con tu inventario',
    corto: 'Cotizador',
    sectores: ['todos', 'comercio'],
    tipos: ['software'],
    instala: false,
    para: 'Tus vendedores arman cotizaciones de varios renglones con tus precios y existencias, y el cliente las recibe en PDF con tu marca.',
    incluye: ['Catálogo con precios y existencias', 'Cotizaciones con renglones, descuentos e ITBMS', 'Aprobación antes de enviar', 'Historial por cliente'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T07',
    slug: 'factura-electronica',
    nombre: 'Conexión con la factura electrónica',
    corto: 'Factura electrónica',
    sectores: ['todos'],
    tipos: ['pagos', 'software'],
    instala: false,
    para: 'Tu sistema de ventas manda cada factura al proveedor autorizado por la DGI, sin volver a escribirla.',
    incluye: ['Conexión con un PAC autorizado', 'Factura enviada al cliente por correo o WhatsApp', 'Notas de crédito'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T08',
    icono: 'chart-line-up',
    slug: 'tablero-de-ventas',
    nombre: 'Tablero de ventas y operación',
    corto: 'Tablero de ventas',
    sectores: ['todos'],
    tipos: ['software'],
    instala: false,
    para: 'Las cifras que miras cada semana, en una pantalla que se actualiza sola: ventas por día, por producto y por vendedor.',
    incluye: ['Conexión con tu sistema de ventas o tus hojas de cálculo', 'Comparación contra la semana y el mes anteriores', 'Envío automático por correo'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'T09',
    slug: 'pagos-en-linea',
    nombre: 'Cobros en línea con tarjeta y Yappy',
    corto: 'Cobros en línea',
    sectores: ['todos'],
    tipos: ['pagos', 'web'],
    instala: false,
    para: 'Enlaces de pago y botón de pago en tu página, con la confirmación conectada a tu sistema.',
    incluye: ['Pasarela panameña', 'Enlaces de pago por WhatsApp', 'Confirmación automática del pago'],
    equipo: [],
    precio: null,
    demo: null,
  },

  // ── añadidos: punto de venta y 3D de productos ──
  {
    id: 'R11',
    icono: 'credit-card',
    slug: 'punto-de-venta',
    nombre: 'Punto de venta para restaurante o tienda',
    corto: 'Punto de venta (POS)',
    sectores: ['restaurantes', 'comercio'],
    tipos: ['software', 'pagos'],
    instala: false,
    para: 'La caja de tu negocio: ventas, cierre de turno, inventario que se descuenta solo y la factura electrónica conectada al proveedor autorizado.',
    incluye: ['Ventas por mesa, mostrador o para llevar', 'Cierre de caja por turno y por cajero', 'Inventario e insumos', 'Factura electrónica con PAC', 'Funciona en la computadora o la tableta de tu caja, con tu impresora de tickets y tu lector de código de barras si ya los tienes'],
    equipo: [],
    precio: null,
    demo: null,
  },
  {
    id: 'C10',
    slug: 'productos-en-3d',
    nombre: 'Productos en 3D y realidad aumentada',
    corto: 'Productos en 3D',
    sectores: ['comercio', 'inmuebles'],
    tipos: ['web'],
    instala: false,
    para: 'El cliente gira el producto en tu página y lo pone en su sala con la cámara del teléfono para ver cómo queda: muebles, electrodomésticos, adornos.',
    incluye: ['Modelo 3D del producto a partir de fotos o del fabricante', 'Visor en tu página o tienda en línea', 'Vista en realidad aumentada en Android y iPhone'],
    equipo: [],
    precio: null,
    demo: null,
  },

  // ── añadidos del 3-oct (2): escuelas, talleres y salones, y más software para cualquier negocio ──
  {
    id: 'E01', icono: 'graduation-cap', slug: 'matricula-y-mensualidades', nombre: 'Matrícula y cobro de mensualidades en línea', corto: 'Matrícula y mensualidades',
    sectores: ['educacion'], tipos: ['software', 'pagos'], instala: false,
    para: 'Los padres matriculan y pagan la mensualidad desde el teléfono con Yappy o tarjeta; tú ves quién está al día sin perseguir a nadie.',
    incluye: ['Formulario de matrícula con documentos', 'Cobro de mensualidades con recordatorio', 'Estado de cuenta por estudiante', 'Reporte de morosidad'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'E03', icono: 'whatsapp-logo', slug: 'avisos-a-padres', nombre: 'Avisos a padres por WhatsApp', corto: 'Avisos a padres',
    sectores: ['educacion'], tipos: ['software', 'ia'], instala: false,
    para: 'Circulares, notas, recordatorios de pago y avisos de último momento que llegan al WhatsApp de cada familia.',
    incluye: ['Envío por grupo, grado o estudiante', 'Confirmación de lectura', 'Respuestas automáticas a las preguntas de siempre'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'V01', icono: 'clock', slug: 'turnos-y-aviso-de-listo', nombre: 'Turnos en línea y aviso cuando está listo', corto: 'Turnos y aviso de listo',
    sectores: ['servicios'], tipos: ['software'], instala: false,
    para: 'El cliente del autolavado o del taller saca turno, ve cuántos tiene adelante y recibe un WhatsApp cuando su carro está listo.',
    incluye: ['Turno desde el teléfono o en el local', 'Fila en vivo', 'Aviso de listo por WhatsApp'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'V02', icono: 'wrench', slug: 'ordenes-de-trabajo', nombre: 'Órdenes de trabajo del taller', corto: 'Órdenes de trabajo',
    sectores: ['servicios'], tipos: ['software'], instala: false,
    para: 'Recepción del vehículo con fotos, presupuesto que el cliente aprueba por WhatsApp, estado del trabajo e historial por placa.',
    incluye: ['Fotos del vehículo al recibirlo', 'Presupuesto con aprobación del cliente', 'Historial por placa', 'Aviso de entrega'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'V03', icono: 'calendar-check', slug: 'agenda-para-salones', nombre: 'Agenda para barberías y salones', corto: 'Agenda para salones',
    sectores: ['servicios'], tipos: ['software'], instala: false,
    para: 'Citas por barbero o estilista, recordatorio por WhatsApp y depósito en línea para que no se pierda el espacio.',
    incluye: ['Agenda por profesional y servicio', 'Recordatorio y confirmación', 'Depósito con Yappy o tarjeta'],
    equipo: [], precio: null, demo: 'https://jojomunoz.github.io/alphateklab-reservas/',
  },
  {
    id: 'S04', icono: 'stethoscope', slug: 'videoconsulta', nombre: 'Videoconsulta con cobro previo', corto: 'Videoconsulta',
    sectores: ['salud'], tipos: ['software', 'pagos'], instala: false,
    para: 'El paciente agenda, paga y entra a la consulta por video desde el enlace que le llega, sin instalar nada.',
    incluye: ['Sala de video por cita', 'Cobro antes de la consulta', 'Recordatorio con el enlace'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'S05', icono: 'stethoscope', slug: 'expediente-del-paciente', nombre: 'Expediente digital del paciente', corto: 'Expediente digital',
    sectores: ['salud'], tipos: ['software'], instala: false,
    para: 'La historia del paciente, sus citas, fotos de control y documentos en un solo lugar, con acceso solo para quien debe verla.',
    incluye: ['Ficha por paciente con historial', 'Fotos de control por fecha', 'Permisos por persona', 'Consentimiento según la Ley 81 de 2019'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'C11', icono: 'whatsapp-logo', slug: 'catalogo-por-whatsapp', nombre: 'Catálogo y pedidos por WhatsApp', corto: 'Pedidos por WhatsApp',
    sectores: ['comercio', 'restaurantes'], tipos: ['web', 'ia'], instala: false,
    para: 'Tu catálogo con precios y fotos en un enlace; el cliente arma el pedido y te llega ordenado al WhatsApp, listo para cobrar.',
    incluye: ['Catálogo con fotos, precios y existencias', 'Pedido que llega armado al WhatsApp', 'Cobro con enlace de pago'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T12', icono: 'envelope-simple', slug: 'correo-y-dominio', nombre: 'Correo y dominio con el nombre de tu negocio', corto: 'Correo y dominio',
    sectores: ['todos'], tipos: ['web'], instala: false,
    para: 'ventas@tunegocio.com en vez de un Gmail personal, configurado en el teléfono y la computadora de cada persona.',
    incluye: ['Registro del dominio a nombre de tu negocio', 'Cuentas de correo por persona', 'Configuración en sus equipos'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T13', icono: 'map-pin', slug: 'negocio-en-google', nombre: 'Tu negocio en Google Maps y reseñas', corto: 'Google Maps y reseñas',
    sectores: ['todos'], tipos: ['web'], instala: false,
    para: 'Que aparezcas cuando te buscan cerca, con horario, fotos, teléfono y reseñas, y que respondas a cada reseña.',
    incluye: ['Perfil de negocio de Google completo', 'Fotos y horario al día', 'Pedido de reseñas a tus clientes'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T14', slug: 'inventario-y-compras', nombre: 'Sistema de inventario y compras', corto: 'Inventario y compras',
    sectores: ['todos', 'comercio'], tipos: ['software'], instala: false,
    para: 'Entradas, salidas y existencias al día, aviso cuando algo se está acabando y órdenes de compra a tus proveedores.',
    incluye: ['Existencias por bodega', 'Mínimos y aviso de reposición', 'Órdenes de compra', 'Uso del lector de código de barras si ya tienes uno (opcional)'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T15', icono: 'handshake', slug: 'seguimiento-de-clientes', nombre: 'Seguimiento de clientes y ventas', corto: 'Clientes y ventas (CRM)',
    sectores: ['todos'], tipos: ['software'], instala: false,
    para: 'Cada cliente con su historial, en qué etapa va cada venta y qué toca hacer hoy, para que ninguna se enfríe.',
    incluye: ['Ficha por cliente', 'Embudo de ventas por etapa', 'Recordatorios de seguimiento', 'Reportes por vendedor'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T16', slug: 'portal-de-clientes', nombre: 'Portal para tus clientes', corto: 'Portal de clientes',
    sectores: ['todos'], tipos: ['web', 'software'], instala: false,
    para: 'Tus clientes entran con su usuario y ven sus pedidos, facturas, documentos y el estado de lo que te encargaron.',
    incluye: ['Acceso por cliente', 'Pedidos, facturas y documentos', 'Estado de cada trabajo'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T17', slug: 'firma-de-documentos', nombre: 'Firma de documentos en línea', corto: 'Firma de documentos',
    sectores: ['todos'], tipos: ['software'], instala: false,
    para: 'Contratos y formularios que el cliente firma desde el teléfono, con registro de quién firmó y cuándo.',
    incluye: ['Envío del documento por enlace', 'Firma desde el teléfono', 'Registro de quién y cuándo', 'Para firma con valor legal pleno, conexión con un proveedor acreditado'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T18', icono: 'shield-check', slug: 'respaldo-y-seguridad', nombre: 'Respaldo de datos y seguridad informática', corto: 'Respaldo y seguridad',
    sectores: ['todos'], tipos: ['software'], instala: false,
    para: 'Copias automáticas de lo importante en la nube, contraseñas en orden y cuentas protegidas, para que una computadora dañada no te cueste el negocio.',
    incluye: ['Respaldo automático diario en la nube', 'Prueba de restauración', 'Gestor de contraseñas para el equipo', 'Revisión de cuentas y accesos'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T20', icono: 'arrows-clockwise', slug: 'conexion-entre-sistemas', nombre: 'Conexión entre sistemas', corto: 'Conexión entre sistemas',
    sectores: ['todos'], tipos: ['software'], instala: false,
    para: 'Que tu tienda, tu sistema de ventas, tu contabilidad, Yappy o el banco se pasen los datos solos.',
    incluye: ['Conexión por API entre tus sistemas', 'Sincronización programada', 'Aviso cuando algo no cuadra'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T21', slug: 'lectura-de-documentos-con-ia', nombre: 'Lectura de facturas y documentos con IA', corto: 'Lectura de documentos con IA',
    sectores: ['todos'], tipos: ['ia', 'software'], instala: false,
    para: 'Fotos o PDF de facturas, órdenes y formularios que se convierten solos en datos dentro de tu sistema o tu hoja de cálculo.',
    incluye: ['Lectura de facturas, órdenes y formularios', 'Revisión de lo dudoso antes de guardar', 'Exportación a tu sistema o a Excel'],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'T22', icono: 'graduation-cap', slug: 'capacitacion-en-ia', nombre: 'Capacitación en IA para tu equipo', corto: 'Capacitación en IA',
    sectores: ['todos'], tipos: ['ia'], instala: false,
    para: 'Una sesión práctica para que tu equipo use la IA en su trabajo de todos los días: redactar, resumir, cotizar y analizar.',
    incluye: ['Taller con ejemplos de tu propio negocio', 'Guía de qué datos no subir', 'Plantillas para las tareas de siempre'],
    equipo: [], precio: null, demo: null,
  },

  // ── añadidos del 3-oct (3): delivery propio y pedidos automáticos por WhatsApp ──
  {
    id: 'R12', slug: 'app-de-delivery-propia', nombre: 'App de delivery propia, para tu restaurante o tu grupo', corto: 'App de delivery propia',
    sectores: ['restaurantes'], tipos: ['web', 'software', 'pagos'], instala: false,
    para: 'Una app de pedidos a domicilio como PedidosYa o Uber Eats, pero tuya: para tu restaurante, tus sucursales o un grupo de restaurantes que venden juntos, con tus motorizados y sin comisión por pedido.',
    incluye: [
      'App para Android y iPhone, y la misma tienda en la web',
      'Varias sucursales o varios restaurantes en un mismo pedido, con la cuenta separada para cada uno',
      'Zonas de entrega por barrio con su costo y tiempo',
      'App para tus motorizados con la ruta, y seguimiento del pedido para el cliente',
      'Cobro con Yappy y tarjeta, o en efectivo al entregar',
    ],
    equipo: [], precio: null, demo: null,
  },
  {
    id: 'R13', icono: 'whatsapp-logo', slug: 'pedidos-por-whatsapp-automaticos', nombre: 'Pedidos por WhatsApp automáticos, con la comanda directo a la cocina', corto: 'Pedidos por WhatsApp a cocina',
    sectores: ['restaurantes'], tipos: ['ia', 'software'], instala: false,
    para: 'El cliente pide por WhatsApp como siempre, un asistente toma el pedido con tu carta, confirma la dirección y el pago, y la comanda sale sola en la impresora o la pantalla de la cocina.',
    incluye: [
      'Asistente que toma el pedido con tu carta, precios y agotados del día',
      'Confirmación de la dirección, la zona de entrega y la forma de pago (Yappy, tarjeta o efectivo)',
      'Comanda en la impresora o la pantalla que ya tienes en la cocina, sin que nadie la copie a mano',
      'Paso a una persona cuando el cliente lo pide o algo no cuadra',
    ],
    equipo: [], precio: null, demo: null,
    aparte: 'Los mensajes de WhatsApp Business los cobra Meta por mensaje, según su tarifa vigente.',
  },
];
