// Cómo cuenta su problema un dueño de negocio de Panamá, por servicio: frases que escribiría en el buscador o le diría
// a un amigo. El buscador las suma a cada servicio (campo «situaciones», peso como el de los problemas).
// Las escribieron agentes en el papel de dueños de negocios sin ver la batería de control (pruebas/control/) y un
// verificador quitó las que llevaban a otro servicio o no decían nada concreto (3-oct-2026).
export const SITUACIONES = {
  B04: [
    "visitas con curiosos",
    "me escriben a las 11 de la noche por el apartamento y contesto al otro día",
    "pierdo clientes xq contesto tarde los mensajes del anuncio de la casa",
    "contestar mil veces lo mismo: precio, cuántas recámaras, si aceptan mascotas",
    "agendo visitas con gente que no tiene ni pa la separación",
    "gente que no califica pal préstamo y me hace perder la mañana enseñando la casa",
    "quiero saber si el cliente está precalificado antes de ir a enseñarle la propiedad",
    "los extranjeros preguntan por las casas de madrugada x la diferencia de hora",
    "no doy abasto con los whatsapp de los anuncios de alquiler de apartamentos",
    "¿hay algo q conteste el whatsapp de la inmobiliaria y me agende las visitas?",
    "el whatsapp de la inmobiliaria explota los fines de semana y no alcanzo",
    "soy corredor de bienes raíces y paso el día contestando mensajes en vez de vender",
    "¿cuánto cuesta algo que atienda por WhatsApp a los interesados en mis apartamentos?",
    "quiero que alguien filtre a los que preguntan por la casa antes de pasármelos",
    "todo el santo día me preguntan si el apto tiene estacionamiento y si es amoblado",
    "buco de mensajes por el apartamento y la mitad no van en serio",
    "me escriben «info» por el apartamento y cuando digo el precio desaparecen",
  ],
  B05: [
    "página para mis propiedades",
    "inmobiliaria sin página propia",
    "todas mis propiedades están solo en Encuentra24 y en Facebook",
    "si me cierran la cuenta del portal me quedo sin dónde mostrar mis casas",
    "en el portal le salen al cliente las casas de la competencia junto a las mías",
    "le mando las fotos de cada casa por whatsapp una x una, quiero un link con todas",
    "tengo 30 casas y lotes y no tengo dónde enseñarlos todos juntos",
    "que el cliente busque por zona y precio en mi propia página",
    "¿cuánto cuesta una página web pa corredor de bienes raíces?",
    "mi página vieja de la inmobiliaria no deja buscar por recámaras ni por precio",
    "pago cada mes por destacar en el portal y los contactos se los llevan otros agentes",
    "quiero mandar un link por apartamento con sus fotos, el precio y mi whatsapp",
    "quiero un sitio con mis propiedades, no solo el instagram",
    "promotora con varios proyectos: una página donde se vean todas las unidades disponibles",
    "¿hay algo para tener mi listado de casas en venta y alquiler en una pagina mia?",
  ],
  C06: [
    "vender por internet",
    "ventas online con envio",
    "vender ropa online",
    "que me compren aunque la tienda esté cerrada",
    "quiero que los clientes del interior me compren y paguen en línea",
    "que el cliente escoja talla y color y pague ahí mismo",
    "vendo por instagram y quiero que paguen sin tener que escribirme",
    "cuanto cuesta montar una pagina para vender en panama",
    "algo como shopify pero que acepte yappy",
    "tengo 300 productos y quiero venderlos por internet",
    "que compren en la web y pasen a recoger a la tienda",
    "se me venden cosas que ya no tengo porque la página no descuenta",
    "mis clientes quieren comprar desde la casa y que se lo manden",
    "dejar de vender por marketplace y tener mi propia pagina con pagos",
    "nesesito vender online, con la tienda fisica sola ya no da",
    "cobrar el envío según la zona cuando compran por internet",
    "¿me puedes armar una página donde la gente compre con tarjeta y yappy?",
    "vendo canastas de regalo y quiero que las pidan y paguen en una pagina",
  ],
  C08: [
    "tarjeta de sellos",
    "el décimo café gratis",
    "fidelizar clientes de la cafeteria",
    "la tarjetita de sellos de cartón se pierde",
    "me falsifican los sellos de la tarjeta",
    "premiar a los clientes que vienen seguido",
    "clientes que venían cada semana y dejaron de venir",
    "puntos por compra como los del super pero para mi negocio",
    "mandarle un mensaje al que tiene un mes sin venir",
    "sellos en el celular en vez de tarjeta de papel",
    "el labado numero 6 gratis en el autolavado",
    "corte gratis al décimo en la barbería",
    "cuanto cuesta darles puntos a mis clientes de la heladeria",
    "que el cliente acumule sin bajar ninguna app",
    "saber quienes vuelven mas y darles un premio",
    "la competencia da puntos y mis clientes se van pa alla",
    "en la farmacia quiero darle descuento al que compra su medicina todos los meses",
    "chuleta, ya no se cuantos sellos lleva cada cliente",
    "¿se puede dar un premio por cada 50 dólares que compre el cliente?",
  ],
  C10: [
    "muebles a tamaño real",
    "devoluciones por medidas",
    "girar producto en la web",
    "el cliente no sabe si el sofá le cabe en la sala",
    "me devuelven muebles porque no cabían",
    "que el cliente vea cómo queda el mueble en su casa con el celular",
    "como lo de ikea que pones el mueble en tu cuarto con la camara",
    "vendemos lavadoras y la gente no sabe si cabe en el espacio",
    "que puedan darle buelta al producto en la pagina",
    "me piden fotos del mueble por todos los lados",
    "que el cliente apunte la camara a su sala y vea el mueble ahi",
    "la gente quiere ver el producto de todos los ángulos antes de pagar",
    "¿se puede ver el mueble a tamaño real en la casa con el teléfono?",
    "que el cliente vea con el celular si la estufa le cabe en su cocina",
    "cuanto cuesta que mis muebles se puedan girar y ver en la casa del cliente",
    "comedor de 6 sillas: el cliente quiere ver si entra en su apartamento",
    "el cliente de chiriqui no puede venir a ver el mueble en persona",
    "el cliente tiene q venir hasta la tienda a medir el mueble",
    "ver como queda la lampara en la casa antes de comprarla",
  ],
  C11: [
    "pedidos regados en whatsapp",
    "pierdo pedidos en whatsapp",
    "mandar fotos y precios uno por uno por whatsapp",
    "los pedidos me llegan en notas de voz y se me confunden",
    "la lista de precios en pdf que mando por whatsapp nunca está al día",
    "un link con mis productos pa poner en el estado de whatsapp",
    "que el cliente arme su pedido y me llegue completo al whatsapp",
    "vendo cosméticos por whatsapp y se me enredan los pedidos",
    "el catálogo de whatsapp business se me queda corto",
    "vendo repuestos por whatsapp y paso el día mandando fotos",
    "que el pedido llegue con el total y yo solo mande el link de pago",
    "¿hay algo pa que vean lo que vendo y me pidan por whatsapp ya ordenado?",
    "en el chino de mi papa asemos delivery por whatsapp y los pedidos llegan desordenados",
    "sumar a mano el total de cada pedido de whatsapp",
    "los pedidos por whatsapp me llegan incompletos, sin cantidades ni total",
    "los clientes me piden el catalogo y no tengo",
    "cuanto cuesta tener mis precios en un link para compartir por whatsapp",
    "dejar de mandar 50 fotos a cada cliente",
  ],
  E01: [
    "los padres no pagan la mensualidad a tiempo",
    "perseguir a los acudientes pa que paguen",
    "no se quien esta al dia con la mensualidad",
    "cobrar mensualidades x yappy",
    "la matricula en papel es un relajo con tantos documentos",
    "lista de morosos del colegio",
    "academia de baile: las mamas pagan cuando se acuerdan",
    "los papas mandan ACH y no se de que niño es",
    "matricular en linea con los documentos del niño",
    "escuela de futbol: cobrar la mensualidad sin andar detras de los papas",
    "la secretaria cruza el estado del banco con la lista de pagos",
    "cuanto cuesta un sistema pa cobrar mensualidades en un colegio pequeño",
    "academia de ingles con alumnos que deben tres meses",
    "filas de padres pa matricular en febrero",
    "guarderia: los papas pagan en efectivo y se me pierden los recibos",
    "que cada papa vea cuanto debe",
    "padres morosos",
    "mensualidades atrasadas",
  ],
  E03: [
    "las circulares no llegan a la casa",
    "los papelitos de la escuela se quedan en la mochila",
    "el grupo de whatsapp de padres es un desorden",
    "avisar a todos los padres que se suspenden las clases por lluvia",
    "saber si los papas leyeron el aviso",
    "la secretaria contesta todo el dia a que hora salen y cuando es la reunion",
    "mandar un aviso solo a los papas de cuarto grado",
    "los padres dicen que nunca se enteraron de la reunion",
    "no quiero que los papas vean el numero de los demas",
    "avisos de ultimo momento del colegio",
    "la academia necesita avisar cambios de horario a las familias",
    "mandar las notas a cada papa por separado",
    "los papas no entran a la plataforma del colegio",
    "cierran calles por protestas y hay que avisar a las familias rapido",
    "cuanto cuesta mandar avisos del colegio x whatsapp a todas las familias",
    "en el chat de padres el aviso se pierde entre memes y quejas",
    "recordarles a los papas el acto civico de mañana",
    "circulares x whatsapp",
    "comunicados del colegio",
  ],
  H01: [
    "reservas directas sin comision",
    "reservar cabañas sin booking",
    "booking me cobra 15% por cada reserva",
    "quiero que me reserben directo sin pasar por airbnb",
    "que el huésped vea qué fechas hay libres sin escribirme",
    "cobrar el deposito de la reserva de la cabaña con yappy",
    "que en carnavales y semana santa la tarifa suba sola",
    "una familia quiere reservar 2 cabañas juntas el mismo fin de semana",
    "mandar cómo llegar a la finca después que reservan",
    "llevo las reservas en un cuaderno y nadie puede ver que fechas hay libres",
    "dejar de depender de airbnb para llenar el hostal",
    "la gente aparta la cabaña por whatsapp y despues no deposita",
    "cuánto cuesta un sistema de reservas para mi hostal",
    "airbnb se queda con una tajada de cada reserva",
    "hotelito de 8 habitaciones sin pagina para reservar",
    "apartan la cabaña por ACH y tengo que estar confirmando en el banco",
    "huéspedes que repiten quieren reservar directo y no tengo cómo",
    "¿se puede tener reservas en mi propia página como en booking?",
  ],
  H02: [
    "doble reserva",
    "overbooking entre airbnb y booking",
    "fechas cruzadas airbnb booking",
    "me cayeron dos reservas pa la misma noche",
    "serrar las fechas a mano en booking cuando me reservan en airbnb",
    "el calendario de airbnb no se actualizó y vendí la cabaña dos veces",
    "llegaron dos familias a la misma cabaña",
    "conectar el calendario de airbnb con el de booking",
    "tuve que reubicar a un huésped porque vendí la misma noche dos veces",
    "booking me penalizó por cancelarle a un huésped por doble reserva",
    "cada vez que reservan tengo que bloquear las fechas en las otras paginas",
    "expedia, airbnb y booking al mismo tiempo sin que se crucen las fechas",
    "manejar las mismas cabañas en airbnb y booking sin volverme loco",
    "como me entero si el calendario de booking dejo de actualizarse",
    "se me cruzaron reservas del hostal en semana santa",
    "me da miedo abrir en booking además de airbnb por las dobles reservas",
    "que me avise cuando el calendario de airbnb se pegue",
    "mi pagina y airbnb se pisan las fechas",
    "fechas vendidas que siguen abiertas en booking",
    "¿cuánto cuesta que no se me crucen las reservas de airbnb y booking?",
  ],
  H04: [
    "libro de huespedes",
    "fotocopiar pasaportes en recepcion",
    "copia de cedula del huesped",
    "el huésped llega cansado y tiene que llenar la hoja de registro",
    "pedir la foto del pasaporte antes de que llegue",
    "que firmen las normas de la casa antes de llegar",
    "se me pierden las fichas de registro de los huespedes",
    "no se entiende la letra de los huespedes en el formulario",
    "que los huespedes firmen que no se permiten fiestas ni visitas extra",
    "guardar los datos de los huéspedes como pide la ley 81",
    "llega un grupo y se tardan media hora llenando papeles en recepcion",
    "el huesped llega a la 1am y no hay nadie pa tomarle los datos",
    "los extranjeros llegan sin saber que datos les voy a pedir",
    "un huésped rompió cosas y no tenía nada firmado",
    "¿hay forma de que el huésped llene sus datos antes de llegar?",
    "a la recepsionista del hotel se le olvida pedir la cedula",
    "formularios de papel en la recepción del hotel",
    "cuanto cuesta que los huespedes llenen el registro desde el celular",
  ],
  R01: [
    "los turistas no entienden la carta",
    "carta en ingles",
    "solo tengo 3 cartas y los clientes esperan pa verla",
    "el cliente pide de la carta un plato q ya se acabo",
    "¿hay algo pa que el cliente vea la carta en su celular?",
    "cuanto cuesta tener mi carta en el telefono del cliente",
    "me preguntan a cada rato si el plato lleva mani o mariscos",
    "café en Boquete, la mitad de los clientes solo habla inglés",
    "el cuadrito que escaneas y te sale el menu",
    "el qr de la carta dejo de servir cuando cambie de proveedor",
    "quiero cambiar los precios de la carta yo misma desde el cel",
    "los meseros pierden tiempo explicando cada plato a los extranjeros",
    "menu pa turistas",
  ],
  R02: [
    "los clientes esperan mucho pa que les tomen el pedido",
    "nadie trae la cuenta",
    "cada uno quiere pagar lo suyo",
    "que el cliente pague desde la mesa con yappy",
    "dibidir la cuenta entre 6 amigos es un relajo",
    "me da pena preguntarle al cliente cuanta propina va a dejar",
    "los viernes no tengo suficientes meseros pa tomar pedidos",
    "llamar al mesero sin estar alzando la mano",
    "¿hay algo pa que los clientes pidan otra ronda sin esperar?",
    "cevicheria con 14 mesas y solo 2 meseros",
    "la gente se para a pagar en la caja y se forma un tranque",
    "cuanto cuesta que el cliente pida y pague con su celular en la mesa",
    "el mesero entiende mal lo que pidio el cliente",
    "la gente se aburre esperando la cuenta y se va molesta",
    "pedir la cuenta sin hacer señas",
    "propina que escoja el cliente",
    "en la terraza los clientes no encuentran a quien pedirle otra cerveza",
    "la cuenta se tarda",
  ],
  R04: [
    "no se que mesa esta libre",
    "desde la caja no veo cuanto lleva cada mesa",
    "el cajero tiene que salir a preguntar que mesa pidio la cuenta",
    "una mesa se fue sin pagar y nadie se dio cuenta",
    "ver todo el salon en una pantalla",
    "los domingos juntamos mesas y se enredan las cuentas",
    "cuanto lleva la mesa 12",
    "salon y terraza, no se cual mesa ya pidio",
    "llega un grupo y no se donde sentarlo",
    "se cruzan las cuentas de la mesa 4 y la 5",
    "los meseros le cobran a la mesa equivocada",
    "¿hay algo pa ver todas las mesas y lo que ha pedido cada una?",
    "mesas ocupadas y libres en la compu de la caja",
    "al cobrar la mesa no me sale el itbms aparte",
    "que mesas faltan por cobrar",
    "mesas libres u ocupadas",
  ],
  R05: [
    "las comandas de papel se pierden en la cocina",
    "el cocinero no entiende la letra del mesero",
    "los pedidos salen en desorden",
    "en la cocina no saben cuanto lleva esperando cada pedido",
    "el papelito del pedido se mojo y no se leia",
    "la parrilla y el bar se gritan los pedidos",
    "el mesero no sabe cuando el plato esta listo",
    "que los pedidos salgan en una tele en la cocina",
    "platos listos enfriandose en el pase",
    "el pincho de comandas se llena y se confunden",
    "los viernes en la noche se olvidan pedidos en la cocina",
    "cada estacion que vea solo lo suyo",
    "¿como hago pa que el cocinero avise cuando sale el plato?",
    "el bar se entera tarde de las bebidas",
    "comandas perdidas",
    "cuanto cuesta una tablet en la cocina pa ver los pedidos",
    "pedidos atrasados en cocina",
    "tele pa la cocina",
  ],
  R07: [
    "un link pa que me pidan comida desde instagram",
    "no quiero pagar comision por cada pedido de delivery",
    "cobrar el delivery segun el barrio",
    "los clientes me preguntan cuanto es el delivery a su zona",
    "que paguen con yappy en la pagina antes de mandar la comida",
    "pizzeria con repartidor propio, quiero que me pidan directo y no por la app",
    "pedidos pa llevar sin hacer fila",
    "que no me puedan pedir fuera de mi horario",
    "contra entrega o yappy, que el cliente escoja al pedir",
    "que me pidan el almuerzo por internet sin pagarle comision a nadie",
    "cuanto cuesta una pagina pa recibir pedidos de comida",
    "carrito de compras pa mi restaurante",
    "pedidosya se come la ganancia",
    "fonda que reparte almuerzos a oficinas, quiero que pidan en una pagina",
    "¿hay algo pa que me pidan a domicilio sin pasar por pedidosya?",
    "delivery propio sin app",
    "link pa pedir comida",
  ],
  R08: [
    "me reservan por instagram y se me pierden los mensajes",
    "reservan mesa y no llegan",
    "anoto las reservas en un cuaderno",
    "los sabados se llena y no se cuantas reservas puedo aceptar",
    "lista de espera pa cuando se llena el turno",
    "que el cliente aparte mesa sin llamar",
    "dos grupos con la misma mesa apartada",
    "contestar llamadas pa reservar en plena hora pico",
    "¿como hago pa que la gente aparte mesa desde el link de instagram?",
    "aparto mesas por whatsapp y se me olvida anotarlas",
    "recordarle al cliente su reserva de la cena",
    "el dia de las madres las reservas son un caos",
    "reserva pa cumpleaños sin llamar al restaurante",
    "cuanto cuesta un sistema pa reservar mesa en mi restaurante",
    "apartar mesa",
    "me dejan la mesa reservada vacia un viernes",
  ],
  R11: [
    "la caja no cuadra al final del turno",
    "no se cuanto vendio cada cajero",
    "todavia uso una caja registradora vieja",
    "en el minisuper anoto las ventas en un cuaderno",
    "vendo y el inventario no baja solo",
    "cierre de caja por turno",
    "en el cierre falta plata y no se de cual cajero",
    "lector de codigo de barras pa el minisuper",
    "impresora de tickets y cajon de dinero",
    "vendo en mesas y en mostrador y no tengo un sistema pa las dos",
    "cuanto cuesta un sistema de caja pa mi panaderia",
    "vendo un pan con jamon y no se cuanto jamon me queda",
    "se daño la impresora fiscal y necesito otra caja que haga factura electronica",
    "dejar de cobrar con calculadora",
    "cobrar rapido escaniando en el chino",
    "programa pa la caja de la fonda",
    "caja registradora",
    "cuadrar la caja",
    "cobrar con escaner",
  ],
  R12: [
    "quiero mi propia app como pedidosya",
    "app de pedidos pa mis 3 sucursales",
    "varios restaurantes de la plaza queremos una app de delivery juntos",
    "el cliente quiere ver por donde viene su pedido como en uber eats",
    "pedidosya me cobra 30% hasta a mis clientes de siempre",
    "app en el play store con el nombre de mi restaurante",
    "que el cliente pida hamburguesa y helado de dos locales en un solo pedido",
    "repartir los pedidos entre mis motorizados",
    "cuanto me sale tener una app pa pedidos a domicilio con mi marca",
    "cada sucursal recibe pedidos por su lado y es un desorden",
    "tengo 5 motorizados y quiero dejar las apps que cobran comision",
    "que cada local vea solo sus ventas en la app compartida",
    "el cliente no sabe a que hora le llega la comida",
    "franquicia chiquita con 4 locales, delivery con app propia",
    "mis motorizados no saben que pedido llevar primero",
    "uber eats se queda con la ganancia de mis tres locales",
    "app pa varios restaurantes",
  ],
  R13: [
    "paso el dia copiando pedidos del whatsapp a la cocina",
    "los viernes me llegan 60 pedidos por whatsapp y no doy abasto",
    "el que contesta el whatsapp anota mal la direccion",
    "que alguien conteste el whatsapp y tome el pedido mientras cocino",
    "bot pa tomar pedidos de comida x whatsapp",
    "por whatsapp me piden sin cebolla y en la cocina no llega",
    "que el pedido del whatsapp salga impreso en la cocina",
    "me escriben pa pedir pizza a las 11 y nadie contesta",
    "confirmar direccion y yappy de cada pedido es un relajo",
    "pedidos de whatsapp directo a la impresora de la cocina",
    "copio el pedido del whatsapp en un papel y me equivoco",
    "el que contesta ofrece platos que ya se acabaron",
    "cuanto cuesta que un asistente tome los pedidos de mi restaurante por whatsapp",
  ],
  S01: [
    "ausencias de pacientes",
    "citas cruzadas en el consultorio",
    "recordar citas a pacientes",
    "los pacientes no llegan y no avisan",
    "la recepcionista se pasa el día llamando para confirmar citas",
    "pacientes que dejan plantado al doctor",
    "dos pacientes a la misma hora con el mismo doctor",
    "que el paciente saque su cita solo desde una página, sin llamar",
    "en la veterinaria la gente se olvida de la cita de la vacuna",
    "el fisioterapeuta pierde plata con las citas que no llegan",
    "llamar uno por uno a confirmar las citas de mañana",
    "si el paciente no contesta que le vuelvan a escribir solo",
    "cuánto cuesta que le llegue un recordatorio por whatsapp a cada paciente",
    "pacientes que dicen que nadie les recordó la cita",
    "el odontologo pierde la mañana por citas que no bienen",
    "en la oficina los clientes se olvidan de la cita con el abogado",
    "dos doctoras, una sola recepcionista y la agenda es un relajo",
    "¿hay algo que confirme las citas por WhatsApp con un botón?",
    "huecos en la agenda x gente que no confirma",
  ],
  S02: [
    "sala de espera desordenada",
    "llamar pacientes por numero",
    "gritar nombres en la sala",
    "la secretaria grita el nombre del paciente en la sala",
    "los pacientes no saben cuánto les falta",
    "nadie sabe a quién le toca en la sala de espera",
    "una pantalla que diga el número del siguiente como en el banco",
    "se pelean en la sala de espera por quien yego primero",
    "no quiero que se oigan los nombres de los pacientes en voz alta",
    "en la sala de espera dicen que alguien se coló",
    "turnos para 4 consultorios en una sola sala",
    "en el laboratorio llamar a la gente por numero pa la toma de muestra",
    "el doctor sale a la puerta a buscar al siguiente",
    "tengo un tele en la sala de espera y quiero que muestre los turnos",
    "en la oficina de cobros atendemos por orden de llegada y es un relajo",
    "la recepcionista se asoma a cada rato a llamar pacientes",
    "llamar al siguiente paciente desde el celular del doctor",
    "papelitos con número en la clínica que se pierden",
    "¿cuánto cuesta que la tele de la sala llame a los pacientes por número?",
  ],
  S03: [
    "enterarme de quejas primero",
    "satisfaccion de pacientes",
    "clientes insatisfechos que no dicen nada",
    "saber si el paciente quedó contento",
    "me enteré de la queja por google y ya era tarde",
    "preguntarle al cliente cómo le fue al día siguiente",
    "que me avise cuando un cliente se va molesto",
    "me pusieron 1 estrella y en el local nunca dijeron nada",
    "la gente no se queja en el momento y despues pone mala reseña",
    "el cliente se fue bravo y no me dijo nada",
    "saber qué doctor tiene pacientes descontentos",
    "ay forma de saber si los clientes del restaurante salen satisfechos?",
    "enterarme de las quejas antes de que las pongan en internet",
    "que los contentos me dejen reseña y los molestos me digan a mi primero",
    "el huesped se fue molesto y me entere por la reseña",
    "mandar una pregunta corta por whatsapp después de la consulta",
    "el mesero atendio mal y me entere una semana despues",
    "el buzon de sugerencias no lo usa nadie",
    "¿cuánto cuesta preguntarle a cada cliente del 1 al 5 cómo lo atendimos?",
  ],
  S04: [
    "telemedicina pa consultorio pequeño",
    "consulta en linea pagada",
    "citas de seguimiento a distancia",
    "¿hay forma de cobrar la consulta antes de la videollamada?",
    "pacientes del interior que no pueden venir a la consulta",
    "hago consultas por videollamada de whatsapp y despues no me pagan",
    "sesiones de psicología en línea con pago adelantado",
    "revisar resultados por video sin que el paciente tenga que venir",
    "el zoom gratis se me corta a los 40 minutos",
    "nutricionista: seguimiento a pacientes por video",
    "paciente que vive fuera del país quiere consulta",
    "cobrar con yappy antes de la consulta por video",
    "que el paciente entre a la llamada con un link sin bajar nada",
    "me dejan esperando en la videollamada y ni pagaron",
    "atender pasientes por video desde la casa",
    "cuánto cuesta una plataforma para consultas virtuales en mi consultorio",
    "con el tranque los pacientes llegan tarde, quiero darles consulta por video",
    "que las consultas por video no se crucen con las del consultorio",
  ],
  S05: [
    "historias clínicas en papel",
    "carpetas de pacientes",
    "llevo los expedientes en excel",
    "no encuentro el expediente del paciente",
    "fotos de antes y después de los pacientes regadas en mi celular",
    "la recepcionista puede ver todo el historial y no debería",
    "cuando el paciente vuelve no se que le recete la ultima bez",
    "el archivo de papel ya no cabe en el consultorio",
    "se me mojaron unas historias clinicas con la lluvia",
    "dos doctores ven al mismo paciente y cada uno tiene sus notas aparte",
    "anotar la evolución de cada sesión de fisioterapia",
    "resultados de laboratorio que me mandan por whatsapp y se pierden",
    "tengo los datos de los pacientes en un cuaderno, eso cumple la ley 81?",
    "dejar de escribir las historias a mano",
    "comparar las fotos de control de un paciente por fecha",
    "el peso y las medidas de cada paciente en hojas sueltas",
    "que solo el doctor vea el diagnóstico y la secretaria solo las citas",
    "buscar el historial de un paciente me toma 10 minutos",
    "cuanto cuesta tener las historias de los pacientes en la computadora",
  ],
  T01: [
    "solo tengo instagram",
    "no tengo pagina",
    "mi web se ve fea en el cel",
    "la gente me pide un link para ver mis trabajos y solo tengo facebook",
    "la página que me hizo mi sobrino ya ni abre",
    "cuanto cuesta que me hagan una pagina pa mi taller",
    "quiero un link donde vean mis servicios y me escriban directo al whatsapp",
    "me da pena dar mi facebook como si fuera la web de la empresa",
    "las empresas grandes me piden un sitio donde ver lo que hago antes de contratarme",
    "mi página tarda demasiado en abrir en el teléfono y la gente se sale",
    "la plantilla que tengo se ve igualita a la de todo el mundo",
    "¿hay algo pa q mi consultorio tenga su propia pagina?",
    "si me cierran el instagram me quedo sin donde mostrar lo que hago",
    "el que me hizo el sitio desaparecio y no puedo cambiar ni el telefono",
    "mi web tiene los precios de hace tres años y no se como cambiarlos",
    "algo serio en internet pa mi empresa de fumigación, no un perfil de facebook",
    "mi negocio no existe en internet fuera de las redes",
    "conoces a alguien q haga paginas?",
    "link pa mis trabajos",
  ],
  T02: [
    "todo en excel ya no da",
    "el excel compartido se daña cuando lo abren dos a la vez",
    "nadie sabe cuál es la versión buena del excel",
    "pago tres programas y ninguno hace lo que necesito",
    "ningun programa de los que venden sirve para como trabajamos",
    "los técnicos llaman a la oficina para saber a dónde les toca ir hoy",
    "toda la operacion vive en cuadernos y papelitos",
    "cada empleado tiene su propio excel y nada cuadra",
    "quiero un sistema propio pa mi empresa, no uno generico",
    "administro 12 apartamentos y llevo en una libreta quien vive, cuanto paga y cuando vence",
    "el sistema que compramos nos obliga a trabajar como ellos quieren",
    "en la lavanderia anotamos las ordenes en papel y se confunden las bolsas",
    "las notas de los estudiantes andan en el excel de cada profe",
    "si se va la secretaria nadie entiende sus hojas de calculo",
    "pasamos más tiempo arreglando el excel que trabajando",
    "que cada puesto vea solo lo suyo y no un excel que todos tocan",
    "cuanto cuesta hacer un programa para mi distribuidora",
    "llebo los mantenimientos de los aires en un excel que ya es un desastre",
    "todo en excel",
    "sistema pa mi empresa",
  ],
  T03: [
    "app pa mi negocio",
    "app que funcione sin internet",
    "mis clientes me preguntan si tengo app",
    "mis vendedores en el interior se quedan sin señal y no pueden anotar los pedidos",
    "que mi negocio salga en la play store",
    "cuanto cuesta una app para android y iphone",
    "en las fincas no hay señal y los muchachos anotan todo en papel",
    "quiero que mi gimnasio tenga su propia app con mi logo",
    "los inspectores llenan formularios en el campo donde no hay internet",
    "subir mi aplicacion al app store de apple",
    "la competencia ya tiene app y yo no",
    "una app para mis vendedores de ruta en chiriqui",
    "mi equipo en la calle necesita algo en el celular q funcione sin datos",
    "los tecnicos trabajan en sotanos sin señal y pierden lo que anotan",
    "la app tiene que funcionar en iphone y en android, ¿la hacen pa los dos?",
    "nesesito una aplicasion pa mi empresa",
    "mis clientes entran todos los dias y piden algo que se instale en el cel",
    "¿me conviene una app o me basta con la pagina?",
    "app sin señal",
    "app pa mis vendedores",
  ],
  T04: [
    "copiar y pegar todo el dia",
    "pasar datos a mano",
    "paso las noches copiando los pedidos del correo al excel",
    "todos los lunes armo el mismo reporte a mano",
    "la secretaria pasa la mañana metiendo al sistema lo que llega de los formularios",
    "las respuestas del formulario de google alguien las copia una x una",
    "hay una tarea repetida que nos come tres horas diarias",
    "quiero que esto se haga solo, siempre es lo mismo",
    "en la distribuidora alguien arma la hoja del reparto todas las noches a mano",
    "para la planilla de la quincena copio las horas de tres hojas distintas",
    "no quiero contratar a otra persona solo pa pasar datos",
    "renombrar y archivar los pdf que llegan al correo me quita la mañana",
    "¿hay algo para que la compu haga sola lo que hoy hacemos a mano?",
    "el mismo correo de bienvenida lo escribo para cada cliente nuevo",
    "¿se puede hacer que cuando llegue un pedido por correo se anote solo?",
    "pasar datos de una hoja a otra me tiene loco",
    "copio lo mismo en el excel, en el correo y en el whatsapp del jefe",
    "tareas repetidas en la ofisina que nadie quiere hacer",
    "copiar y pegar",
    "tareas repetidas",
  ],
  T05: [
    "mensajes sin contestar",
    "me escriben a las 11 de la noche preguntando si hay",
    "contesto lo mismo cincuenta veces al día",
    "no doy abasto con los mensajes de whatsapp",
    "pierdo ventas porque contesto tarde",
    "¿hay algo que conteste el whatsapp cuando estoy cerrado?",
    "todos preguntan a cuánto, dónde quedan y a qué hora abren",
    "un robot q conteste los mensajes del negocio",
    "la muchacha de la tienda se pasa el dia pegada al celular contestando lo mismo",
    "en la ferreteria me preguntan por whatsapp si hay tal tornillo y no tengo tiempo",
    "los domingos se me acumulan los mensajes y el lunes ya compraron en otro lado",
    "quiero que los clientes tengan respuesta aunque yo este durmiendo",
    "algo que conteste con mis precios y no se invente nada",
    "que conteste lo facil y me pase a mi lo complicado",
    "la recepcion del gimnasio no da con tantas preguntas de precios y horarios",
    "la gente escribe \"info\" y hay que mandarle todo cada vez",
    "respuestas automaticas que sirvan de verdad, no el mensaje de ausencia",
    "en el consultorio preguntan todo el dia cuanto cuesta la consulta y si aceptan seguro",
    "me escriben buco y no alcanzo a contestar a todos",
    "whatsapp que conteste solo",
  ],
  T06: [
    "proformas rapidas",
    "cotizar desde el celular en la visita al cliente",
    "hacer una proforma en word me toma una hora",
    "los vendedores cotizan con precios viejos",
    "cotizamos cosas que no hay en bodega",
    "cada vendedor manda la cotisacion con un formato distinto",
    "los vendedores dan descuentos sin preguntarme",
    "no encuentro la cotizacion que le mande al cliente el mes pasado",
    "calcular el itbms renglon por renglon a mano",
    "los contratistas me piden cotizacion de una lista larga y tardo un dia en mandarla",
    "me equivoque sumando una cotizacion y perdi plata",
    "en la ferreteria las cotizaciones se hacen en excel y siempre sale un error",
    "quiero aprobar los descuentos grandes antes de que salga la cotizacion",
    "el cliente pide precio de 40 productos y armarlo es un parto",
    "a cuanto le cotice a este cliente la otra vez?",
    "cotizacion con mi logo y ruc que se vea profesional",
    "mi vendedor cotizo 50 sacos de cemento y solo teniamos 10",
    "cotizaciones con mi logo",
  ],
  T07: [
    "adios impresora fiscal",
    "la DGI me obliga a facturar electronico?",
    "escribo cada factura dos veces, en mi sistema y en el portal del PAC",
    "que es un PAC y cual me conviene",
    "la impresora fiscal ya no me sirve, y ahora que hago",
    "mi contador dice que tengo que pasarme a factura electrónica",
    "facturar electronico desde el sistema que ya tengo",
    "que la factura le llegue al cliente por whatsapp o correo sin imprimirla",
    "como hago una nota de credito si el cliente devuelve algo",
    "me da miedo una multa de la DGI por no facturar bien",
    "el facturador gratuito de la DGI ya no me alcanza",
    "mis clientes empresas me piden factura electronica y no tengo",
    "cada venta la tengo que volver a teclear pa facturar",
    "hago 300 facturas al mes y no doy con el portal",
    "el PAC que tengo no se conecta con mi programa de ventas",
    "q nesesito pa facturar electronicamente en panama",
    "pasarme de la factura fiscal a la electronica sin cambiar de sistema",
    "cuanto cuesta conectar mi sistema con la facturacion de la dgi",
    "facturar sin impresora fiscal",
  ],
  T08: [
    "como van las ventas hoy",
    "graficas de mis ventas",
    "no se cuanto vendi esta semana hasta que me dice el contador",
    "¿hay algo para ver las ventas de mis dos locales desde el celular?",
    "cual vendedor esta vendiendo mas",
    "que productos se venden mas y cuales no se mueven",
    "vendí más o menos que el mes pasado?",
    "ver las ventas del dia sin llamar a la cajera",
    "estoy de viaje y no se como va la panaderia",
    "tengo los datos en el sistema pero no les entiendo nada",
    "un resumen de ventas que me llegue al correo los lunes",
    "comparar las ventas de esta quincena con la anterior",
    "el reporte del sistema es una lista larguisima que nadie lee",
    "me entero tarde de que un local bajo las ventas",
    "cuanto vendio cada sucursal ayer",
    "manejo tres farmacias y cada una me manda su cierre en una foto x whatsapp",
    "xq bajaron las ventas este mes? no tengo como verlo",
    "los numeros del negocio en una sola pantalla",
    "comparar ventas por mes",
  ],
  T09: [
    "capturas de yappy falsas",
    "cobrar con tarjeta sin maquinita",
    "quiero mandar un enlace para que me paguen",
    "el cliente dice que ya pagó y no me aparece",
    "clientes de afuera quieren pagar con tarjeta y no tengo como",
    "boton de pago pa mi pagina",
    "cobrar sin tener que dar mi numero de cuenta a todo el mundo",
    "stripe no funciona en panama, que uso?",
    "abrir yappy comercial pa mi negocio y conectarlo",
    "un cliente me jugo vivo con una captura editada",
    "que el pago se confirme solo sin revisar el banco",
    "vendo x whatsapp y no tengo como cobrar con tarjeta",
    "vendo tours en bocas y los gringos quieren pagar con tarjeta antes de venir",
    "me encargan tortas y despues no las recogen ni las pagan",
    "cuanto cobra yappy por cada pago",
    "me deben plata de trabajos y quiero mandarles algo pa que paguen ahi mismo",
    "soy fotografo y quiero que me paguen la sesion con tarjeta antes",
    "cobrar con un link",
  ],
  T12: [
    "correo de empresa",
    "ventas@minegocio como se hace",
    "mis empleados cotizan desde su gmail personal",
    "da mala impresión escribirle a los clientes desde un hotmail",
    "cuando se va un empleado se lleva los correos de los clientes",
    "quiero un correo con el nombre de mi empresa",
    "los clientes creen que es estafa porque escribo desde gmail",
    "el correo de la empresa en el celular de cada vendedor",
    "el nombre de mi negocio .com.pa esta libre?",
    "me pidieron un correo corporativo pa poder ser proveedor",
    "tengo el .com pero no se como hacer los correos",
    "cada quien usa un correo distinto y los clientes no saben a cual escribir",
    "quiero administracion@ y ventas@ separados",
    "me da cosa poner mi gmail personal en las tarjetas de presentacion",
    "los correos de la empresa salen de yahoo y se ve poco serio",
    "nesesito correos pa 5 personas con el nombre de la empresa",
    "comprar el nombre de mi negocio para usarlo en el correo",
    "correo que no sea gmail",
  ],
  T13: [
    "no salgo en google maps",
    "como respondo las reseñas",
    "en google sale mi horario viejo",
    "me dejaron una reseña mala en google y no se que hacer",
    "la ubicacion de mi negocio en google esta mal y los clientes se pierden",
    "cuando buscan barberia cerca de mi no aparezco",
    "como hago pa que mis clientes me dejen estrellas en google",
    "alguien creo el perfil de mi negocio y no tengo acceso",
    "google dice que estoy cerrado y estoy abierto",
    "tengo 3 reseñas y la competencia tiene 200",
    "salir en el mapa cuando buscan ferreteria en la chorrera",
    "en google sale el telefono viejo del taller",
    "puedo borrar una reseña falsa?",
    "no tengo local, igual puedo salir en google maps?",
    "las fotos de mi restaurante en google las subieron clientes y se ven feas",
    "poner el horario de los feriados en google",
    "los turistas buscan hostales en el mapa y salen todos menos yo",
    "un cliente me puso una estrella por gusto",
    "reseñas en google",
    "salir en google maps",
  ],
  T14: [
    "inventario en libreta",
    "le pido al proveedor a ojo",
    "me entero que se acabo algo cuando el cliente lo pide",
    "no se cuanto tengo en la bodega",
    "le compro dos veces lo mismo al proveedor porque no sabia que habia",
    "¿hay algo que me avise cuando se este acabando un producto?",
    "tengo dos bodegas y no se que hay en cada una",
    "hacer los pedidos a los proveedores me toma toda la tarde",
    "sacan cosas de la bodega pa la tienda y nadie lo anota",
    "se acaba el alimento de perro que mas se vende y no me doy cuenta",
    "en la farmacia se nos acaban las medicinas que más piden",
    "pasar el codigo de barras al sacar algo de la bodega",
    "cuanto me queda de cada repuesto?",
    "registrar que material sale para cada obra",
    "ordenes de compra en papel que se pierden",
    "me quedo sin mercansia los fines de semana",
    "en la abarroteria siempre se acaba el arroz antes de que llegue el pedido",
    "cuanto entra y cuanto sale de cada producto, no tengo idea",
    "productos agotados sin aviso",
  ],
  T15: [
    "a quien llamo hoy",
    "mi lista de clientes es un desorden",
    "se me olvida llamar a los clientes que cotizaron",
    "los vendedores anotan los clientes en una libreta",
    "no se en que va cada venta",
    "cuando un vendedor se va se lleva la lista de clientes",
    "clientes que preguntan y nadie les da seguimiento",
    "tengo 30 cotizaciones mandadas y no se cuales siguen vivas",
    "perdi una venta grande porque nadie volvio a llamar",
    "cuantas ventas tiene abiertas cada vendedor",
    "los contactos de los clientes estan en el celular de cada vendedor",
    "no se que le vendimos a este cliente el año pasado",
    "se me olvida llamar a la gente pa renovar la poliza",
    "en la academia la gente pregunta por los cursos y nadie les vuelve a escribir",
    "cada vendedor maneja sus clientes en un excel diferente",
    "los clientes se enfrian porque tardamos en volver a escribirles",
    "gente que vino a preguntar al gimnasio y no se inscribio, nadie la llama",
    "quien atendio a este cliente la ultima vez?",
    "clientes sin seguimiento",
  ],
  T16: [
    "clientes preguntando en que va lo suyo",
    "los clientes llaman todo el dia a preguntar si ya esta su pedido",
    "me piden la factura otra vez porque la perdieron",
    "quiero que mis clientes vean en que va su trabajo sin llamarme",
    "en la imprenta nos preguntan cada hora si ya estan los volantes",
    "los clientes de la agencia de aduanas quieren saber en que va su carga",
    "los clientes de la oficina contable me piden copia de sus declaraciones a cada rato",
    "que los pacientes bajen sus resultados del laboratorio sin venir",
    "que cada cliente entre con su usuario y vea solo lo suyo",
    "los clientes me escriben pa pedir sus documentos y los busco en mil carpetas",
    "el cliente no sabe si su tramite ya esta listo",
    "¿hay algo para que mis clientes vean sus facturas y lo que me deben?",
    "mis clientes mayoristas quieren ver el estado de sus pedidos solos",
    "los clientes del bufete quieren ver los papeles de su caso sin venir",
    "el dueño de la remodelación quiere ver en qué va la obra y los papeles",
    "las empresas a las que les doy mantenimiento quieren ver sus reportes de cada visita",
    "en el estudio de diseño los clientes quieren ver sus pruebas y avances sin escribirnos",
    "clientes preguntando \"¿ya está?\"",
  ],
  T17: [
    "firmas a distancia",
    "imprimir, firmar, escanear y mandar, que fastidio",
    "el cliente vive en david y tiene que venir a firmar el contrato",
    "firmar contratos desde el celular",
    "los inquilinos tienen que venir a la oficina a firmar el contrato de alquiler",
    "el cliente se hace el vivo y dice que nunca aceptó las condiciones",
    "que el cliente firme el contrato antes de llevarse lo que alquila",
    "los papeles firmados se pierden en el archivo",
    "mandar un contrato por whatsapp y que lo firmen ahi mismo",
    "con el tranque nadie quiere venir hasta la oficina solo a firmar",
    "los empleados nuevos firman el contrato en papel y despues no aparece",
    "que los papas firmen el permiso de la gira desde el celular",
    "la firma por el celular vale legalmente en panama?",
    "saber quien firmo y a que hora",
    "clientes en el extranjero que tienen que firmar un contrato conmigo",
    "hoja de recibido conforme firmada por el cliente al entregar",
    "los clientes tardan semanas en devolverme el contrato firmado",
    "cuanto cuesta que mis clientes firmen en linea",
    "firmar sin imprimir",
  ],
  T18: [
    "contraseñas en una libreta",
    "clave123 en todas las cuentas",
    "si se daña el disco duro pierdo todo",
    "a un amigo le bloquearon todo con un virus y no quiero que me pase",
    "si se roban la compu pierdo toda la contabilidad",
    "cuando se va un empleado no se a que cuentas tiene acceso",
    "todos en la oficina usan la misma clave",
    "la clave de la DGI y la CSS la sabe todo el mundo",
    "copio todo a una usb cuando me acuerdo",
    "donde guardo una copia de los archivos fuera de la oficina?",
    "si se inunda la oficina pierdo los archivos de 10 años",
    "me hackearon el correo y les escribieron a mis clientes",
    "los archivos de la empresa solo estan en la compu de la contadora",
    "nunca he probado si la copia de seguridad sirve",
    "el exempleado todavia entra a las cuentas de la empresa",
    "me da miedo que me secuestren los archivos como a la otra empresa",
    "el disco externo esta en la misma oficina que la computadora",
    "perder todos los archivos",
  ],
  T20: [
    "los sistemas no se hablan",
    "cuadrar yappy con pedidos",
    "la tienda en linea y el local tienen inventarios distintos",
    "las ventas de la sucursal de david no llegan al sistema de la principal",
    "el programa de la planilla y el de contabilidad no se pasan nada",
    "cada noche cuadro las existencias de la web y de la tienda",
    "vendi por la web algo que ya se habia vendido en el local",
    "los pagos del banco los paso a mano a quickbooks",
    "entra un pago y no se de que pedido es",
    "tengo shopify y un pos y no se conectan",
    "que los pagos de yappy entren solos al sistema contable",
    "la contadora vuelve a escribir todo lo que ya esta en el sistema de ventas",
    "uso cuatro programas y tengo que meter la misma venta en todos",
    "los pedidos de la tienda online no pasan solos al sistema de la oficina",
    "las cifras del banco y del sistema nunca cuadran",
    "que el estado de cuenta del banco se cruce solo con las facturas",
    "cada sistema dice una cosa distinta",
    "conectar mi programa con el banco, se puede?",
    "sistemas que no cuadran",
  ],
  T21: [
    "digitar facturas todo el dia",
    "fotos de facturas a excel",
    "paso las facturas de los proveedores a excel a mano",
    "tomarle foto a la factura y que se llene solo",
    "tengo una caja de facturas que pasar cada mes",
    "los clientes mandan ordenes de compra en pdf y alguien las transcribe",
    "sacar el ruc, el total y el itbms de cada factura sin teclear",
    "formularios llenados a mano que alguien tiene que teclear",
    "las facturas llegan x whatsapp, x correo y en papel y todo hay que pasarlo",
    "la administradora se pasa el sabado pasando facturas",
    "recibos de gastos de los vendedores en fotos arrugadas",
    "en la cooperativa las solicitudes llegan escaneadas y hay que copiar los datos a mano",
    "en el taller nadie pasa las facturas de repuestos al excel porque da pereza",
    "me equivoco copiando los montos de las facturas",
    "la letra de los recibos a mano, eso se puede leer solo?",
    "pa declarar el itbms sumo a mano cientos de facturas de compra",
    "que la compu lea los pdf y saque los datos",
    "las notas de entrega de los proveedores las pasamos a mano al sistema",
    "teclear facturas de proveedores",
    "recibos a excel",
  ],
  T22: [
    "aprender a usar chatgpt",
    "taller de IA pa mi oficina",
    "mi equipo no sabe usar chatgpt",
    "quiero que mis empleados aprendan a usar la inteligencia artificial",
    "me da miedo que pongan datos de clientes en chatgpt",
    "curso de chatgpt para empresas en panama",
    "como uso la IA para resumir contratos largos",
    "los pelaos de la oficina usan chatgpt pero les sale todo raro",
    "en el despacho queremos usar la IA sin meter la pata con los expedientes",
    "que se puede subir y que no a chatgpt",
    "todo el mundo habla de la IA y en mi negocio nadie la usa",
    "enseñarle a la secretaria a usar chatgpt pa las cartas",
    "mi gente tarda una hora en cada correo y no sabe usar chatgpt",
    "mis vendedores copian lo que dice chatgpt sin revisar",
    "plantillas de chatgpt pa las tareas de la oficina",
    "clase practica de IA con ejemplos de mi negocio",
    "pago chatgpt plus y nadie en la oficina lo usa",
    "chatgpt pa empleados",
  ],
  V01: [
    "en el autolavado la gente espera sin saber cuanto le falta",
    "avisarle al cliente por whatsapp que su carro ya esta listo",
    "cuantos carros tengo adelante",
    "los sabados el lavado se llena y la gente se va",
    "llamo uno por uno pa decir que el carro esta listo",
    "un juega vivo se metio en la fila del lavado",
    "que el cliente saque turno desde el celular pa lavar el carro",
    "que se vaya a la panaderia y le aviso cuando este el carro",
    "en el taller me llaman a cada rato a preguntar si ya esta el carro",
    "turno pa lavar la moto",
    "un qr en la entrada del autolavado pa sacar turno",
    "los carros esperando se parquean en la calle y tapan",
    "cuanto cuesta un sistema de turnos pa autolavado",
    "gritar el nombre del cliente cuando sale su carro",
    "detailing: el cliente no sabe a que hora volver por su carro",
    "el carro listo y el dueño ni enterado",
    "fila en el lavado",
    "turno pa el lavado",
  ],
  V02: [
    "el cliente dice que el golpe se lo hicimos nosotros",
    "presupuestos aprobados de palabra y despues no quieren pagar",
    "no me acuerdo que le hicimos a ese carro la vez pasada",
    "tomar fotos del carro cuando entra al taller",
    "el dueño dice que nunca autorizo cambiar las pastillas",
    "las ordenes del taller en papel se pierden",
    "mandarle el presupuesto al cliente pa que lo apruebe por whatsapp",
    "chapisteria: siempre hay pleito por lo que se acordo cobrar",
    "cuanto cuesta un programa pa el taller mecanico",
    "buscar por placa que se le hizo al carro",
    "el cliente reclama que le cobramos mas de lo que le dijimos",
    "la empresa quiere el historial de reparaciones de cada pick-up",
    "hoja de recepcion del carro con fotos",
    "taller de motos sin registro de los trabajos",
    "en que va la reparacion de cada carro",
    "rayones que nadie anoto",
    "el mecanico no sabe que aprobo el cliente",
    "historial del carro",
  ],
  V03: [
    "los clientes reservan y no llegan a la barberia",
    "se me cruzan las citas de los barberos",
    "cobrar un adelanto pa apartar la cita",
    "llevo la agenda del salon en una libreta",
    "me escriben a toda hora pa sacar sita de corte",
    "que el cliente escoja su barbero",
    "recordarle a las clientas la cita de uñas un dia antes",
    "dos clientas a la misma hora con la misma estilista",
    "cancelan a ultima hora y se pierde el espacio",
    "spa: cobrar deposito por yappy antes del masaje",
    "cada barbero quiere ver su agenda en el celular",
    "un tinte de 3 horas se me monta con otras citas",
    "cuanto cuesta algo pa que me agenden los cortes por internet",
    "los que llegan sin cita y los que tienen cita se pelean el turno",
    "citas barberia",
    "manicurista con clientas que cancelan el mismo dia",
    "deposito pa la cita",
  ],
};
