// Cómo cuenta su problema un dueño de negocio de Panamá, por servicio: frases que escribiría en el buscador o le diría
// a un amigo. El buscador las suma a cada servicio (campo «situaciones», peso como el de los problemas).
// Las escribieron agentes en el papel de dueños de negocios sin ver la batería de control (pruebas/control/) y un
// verificador quitó las que llevaban a otro servicio o no decían nada concreto (3-oct-2026).
export const SITUACIONES = {
  B01: [
    "ver apartamento sin ir",
    "visita virtual del apto",
    "los interesados viven afuera y quieren ver el apartamento por dentro antes de viajar",
    "el cliente está en Miami y me pide videollamada pa enseñarle el apto cuarto x cuarto",
    "la gente llega a ver el apartamento y dice que se lo imaginaba más grande",
    "las fotos no dan idea de cómo es el espacio ni cómo se conectan los cuartos",
    "que el comprador se pasee por la casa desde su celular",
    "que el cliente mida desde su teléfono si le cabe la cama en el cuarto",
    "huespedes que quieren ver la cabaña por dentro antes de reservar",
    "en el hostal me preguntan cómo son los cuartos y las fotos no les alcanzan",
    "¿cuánto cuesta un tour virtual de una casa para venderla?",
    "el apartamento modelo solo se ve en la sala de ventas y la gente no llega",
    "que los interesados vean el local por dentro sin tener que ir yo a enseñarlo",
    "alquilo oficinas y los interesados de Chiriquí no pueden venir a la capital a verlas",
    "el video que grabo con el cel de la casa sale mareado y no se entiende nada",
    "nesesito que los clientes vean la casa x dentro antes de cuadrar la visita",
    "¿hay algo para que el cliente recorra la casa como si estuviera adentro?",
  ],
  B02: [
    "fotos feas del apto",
    "fotógrafo para casa en venta",
    "las fotos que tomo con el celular salen oscuras y el apartamento se ve feo",
    "las ventanas salen blancas en las fotos y no se ve la vista al mar",
    "en las fotos los cuartos se ven más chiquitos de lo que son",
    "las fotos de mi anuncio en Encuentra24 se ven pobres al lado de las de otros",
    "¿cuánto cobra un fotógrafo por fotos de una casa de playa para alquilar?",
    "las fotos de mi Airbnb no le hacen justicia a la casa",
    "nadie le da clic al anuncio del apartamento, creo q es por las fotos",
    "fotos del hotel para Booking que no se vean de aficionado",
    "las fotos de la casa las tomo yo con el teléfono y se nota",
    "las fotos del apartamento salen amarillas por los bombillos y torcidas",
    "no se aser fotos que se vean bien de la casa, no tengo buena cámara",
    "fren, ¿conoces a alguien que tome fotos de apartamentos pa vender?",
    "las fotos de las recámaras salen con sombras y se ven tristes",
    "quiero que la terraza y la piscina se vean bonitas en las fotos del anuncio",
    "fotos bonitas de la cabaña pa las redes",
  ],
  B03: [
    "sacar el plano de la casa",
    "metros de cada cuarto",
    "no tengo el plano del apartamento y el comprador me lo está pidiendo",
    "voy a remodelar y el contratista me pide las medidas de todo",
    "pa cotizar el porcelanato necesito los metros cuadrados de cada ambiente",
    "quiero alquilar la bodega en dos partes y no sé cuántos metros tiene cada una",
    "medir la casa con cinta cuarto x cuarto me toma el día entero",
    "el anuncio dice 120 m2 pero el cliente quiere saber cuánto mide cada recámara",
    "necesito el plano de la oficina nueva para ver cómo acomodar los escritorios",
    "¿cuánto cuesta que me hagan el plano de un local con las medidas reales?",
    "la constructora cerró y nadie me da el plano del apartamento",
    "el ebanista me pide las medidas de la cocina para cotizar los muebles",
    "quiero poner el plano en el anuncio para que se entienda la distribucion",
    "¿hay algo q saque el plano de un apartamento sin medir todo a mano?",
    "el dueño dice que el local tiene 200 metros y yo creo que tiene menos",
    "alquilo depósitos por metro cuadrado y necesito saber cuánto mide cada uno",
  ],
  B04: [
    "visitas con curiosos",
    "me escriben a las 11 de la noche por el apartamento y contesto al otro día",
    "pierdo clientes xq contesto tarde los mensajes del anuncio de la casa",
    "contestar mil veces lo mismo: precio, cuántas recámaras, si aceptan mascotas",
    "agendo visitas con gente que no tiene ni pa la separación",
    "gente que no califica pal préstamo y me hace perder la mañana enseñando la casa",
    "quiero saber si el cliente está precalificado antes de ir a enseñarle la propiedad",
    "los extranjeros preguntan por las casas de madrugada x la diferencia de hora",
    "no doy abasto con los whatsapp de los anuncios de alquiler de apartamentos",
    "¿hay algo q conteste el whatsapp de la inmobiliaria y me agende las visitas?",
    "el whatsapp de la inmobiliaria explota los fines de semana y no alcanzo",
    "soy corredor de bienes raíces y paso el día contestando mensajes en vez de vender",
    "¿cuánto cuesta algo que atienda por WhatsApp a los interesados en mis apartamentos?",
    "quiero que alguien filtre a los que preguntan por la casa antes de pasármelos",
    "todo el santo día me preguntan si el apto tiene estacionamiento y si es amoblado",
    "buco de mensajes por el apartamento y la mitad no van en serio",
    "me escriben «info» por el apartamento y cuando digo el precio desaparecen",
  ],
  B05: [
    "página para mis propiedades",
    "inmobiliaria sin página propia",
    "todas mis propiedades están solo en Encuentra24 y en Facebook",
    "si me cierran la cuenta del portal me quedo sin dónde mostrar mis casas",
    "en el portal le salen al cliente las casas de la competencia junto a las mías",
    "le mando las fotos de cada casa por whatsapp una x una, quiero un link con todas",
    "tengo 30 casas y lotes y no tengo dónde enseñarlos todos juntos",
    "que el cliente busque por zona y precio en mi propia página",
    "¿cuánto cuesta una página web pa corredor de bienes raíces?",
    "mi página vieja de la inmobiliaria no deja buscar por recámaras ni por precio",
    "pago cada mes por destacar en el portal y los contactos se los llevan otros agentes",
    "quiero mandar un link por apartamento con sus fotos, el precio y mi whatsapp",
    "quiero un sitio con mis propiedades, no solo el instagram",
    "promotora con varios proyectos: una página donde se vean todas las unidades disponibles",
    "¿hay algo para tener mi listado de casas en venta y alquiler en una pagina mia?",
  ],
  B06: [
    "video aéreo del lote",
    "vendo unos lotes y en las fotos desde el suelo no se ve nada",
    "quiero mostrar que el proyecto queda a 5 minutos de la playa",
    "el comprador no entiende dónde queda el terreno ni por dónde se entra",
    "fotos desde arriba del edificio pal brochure de ventas",
    "un video del hotel visto desde arriba para las redes",
    "¿cuánto cobran por grabar una finca con dron en Chame?",
    "la finca que vendo es tan grande que no cabe en ninguna foto",
    "que el comprador vea la vista al mar que tiene el lote",
    "mostrar cómo se reparten los lotes de la lotificación",
    "vendo en planos y solo hay monte, quiero que se vea dónde queda y qué hay alrededor",
    "las cabañas están en la montaña y quiero que se vea todo el paisaje alrededor",
    "fren, ¿conoces a alguien con dron pa sacar el terreno desde arriba? lo estoy vendiendo",
    "quiero enseñar lo cerca que está la casa de la carretera y del pueblo",
    "video desde el aire de la finca para un comprador que vive en el extranjero",
    "un mapa visto desde arriba de la finca para enseñarle al comprador cómo es",
    "haber si alguien puede bolar un dron sobre el terreno que estoy vendiendo",
  ],
  C01: [
    "cuanta gente entra",
    "contar clientes que entran",
    "control de aforo",
    "no sé cuántas personas me entran al día",
    "entra buco de gente pero casi nadie compra",
    "¿cuántos de los que entran terminan comprando?",
    "a qué hora entra más gente pa poner otra vendedora",
    "el seguridad cuenta la gente con un contadorcito de mano y siempre se pierde",
    "la caja marcó 40 ventas pero no sé cuánta gente entró",
    "se llena la tienda el sabado pero no se cuantos de esos compran",
    "mi encargado dice que entra poca gente y yo digo que entran y no compran",
    "saber si la vitrina nueva está trayendo más gente",
    "¿hay algo que cuente cuántas personas hay adentro del local ahorita?",
    "cuanta gente entra los domingos, haber si vale la pena abrir",
    "en el bar los viernes hay que controlar cuanta gente hay adentro",
    "que me avise cuando el local llegue al máximo de personas que permiten los bomberos",
    "cuanto cuesta algo q cuente la gente que entra a la zapateria",
    "quiero saber cuanta gente entra y se va sin comprar",
  ],
  C02: [
    "pasillos que nadie recorre",
    "zonas muertas del local",
    "nadie llega al fondo",
    "por dónde camina la gente dentro del local",
    "en qué parte de la tienda se para la gente a mirar",
    "movi la gondola de lugar y no se si sirvio de algo",
    "dónde pongo lo que más quiero vender para que la gente lo vea",
    "el segundo piso del almacén casi nadie lo sube",
    "cuanto tiempo se queda la gente frente a cada exhibidor",
    "¿hay forma de ver por dónde se mueven los clientes adentro de la tienda?",
    "cambie la vitrina de sitio y quiero comparar si aora se detienen mas",
    "el rincon de las ofertas no lo ve nadie",
    "como acomodar la ferreteria pa q la gente vea todo",
    "qué pasillo es el más caminado del súper",
    "las camaras que ya tengo sirven para ver por donde pasa la gente?",
    "quiero saber si la cabecera del pasillo de verdad la mira la gente",
    "cuanto cuesta saber que zonas de mi tienda visita la gente",
    "tengo los juguetes al fondo y por ahi no pasa nadie",
  ],
  C03: [
    "fila larga en caja",
    "se van por la fila",
    "se me forma cola en la caja y el encargado ni cuenta se da",
    "clientes que dejan la canasta botada x la fila",
    "cómo saber cuándo abrir otra caja",
    "tengo 3 cajas y al mediodía solo hay una abierta y se llena",
    "que le llegue un aviso al encargado cuando hay mucha gente esperando para pagar",
    "en quincena la fila llega hasta el fondo del super",
    "el supervisor está en la bodega y no ve la fila",
    "cuánto tiempo espera la gente para pagar en mi tienda",
    "la cajera sola con dies personas esperando y nadie la ayuda",
    "¿hay algo que avise al gerente cuando la cola de la caja está muy larga?",
    "pierdo ventas en la hora pico porque la gente no aguanta la fila",
    "a que hora se hace fila pa poner otra cajera en ese turno",
    "en la farmacia la cola del mediodía es eterna",
    "se me van clientes con el carrito lleno porque la fila no avanza",
    "fren, la gente se me va de la fila y nadie abre la otra caja",
    "en la panaderia a las 6am la fila llega a la calle y nadie ayuda",
    "cuanto cuesta que me avisen cuando se llena la fila de la caja",
  ],
  C04: [
    "toma de inventario rapida",
    "contar mercancia a mano",
    "conteo fisico sin libreta",
    "haser inventario me toma todo el fin de semana",
    "cerrar la tienda un domingo pa contar la ropa",
    "contar prenda por prenda es eterno",
    "lo que cuento nunca cuadra con lo que dice el sistema",
    "el inventario de fin de mes nos tiene hasta las 11 de la noche",
    "algo que lea toda la ropa del colgador de un solo pase",
    "etiquetas que se leen sin sacar la pieza del gancho",
    "en la abarrotería contar lata por lata es un martirio",
    "cómo contar el inventario más rápido en una tienda de ropa",
    "¿hay forma de pasar el celular por el estante y que cuente lo que hay?",
    "faltan tallas y no sé cuáles hasta que cuento todo",
    "zapatería de dos pisos, contar los pares es un relajo",
    "las etiquetas que se leen solas para la ropa, cuanto cuestan",
    "los muchachos pasan dos días contando y siempre hay diferencias con el sistema",
    "hacer el conteo de la bodega estante por estante tarda demasiado",
  ],
  C05: [
    "la caja no cuadra",
    "robo de empleados",
    "faltantes en caja",
    "robo hormiga en el minisuper",
    "me falta plata en la caja y no sé quién fue",
    "el cajero abre la gaveta sin vender nada",
    "sacan mercancía por la puerta de atrás",
    "tengo cámaras pero nadie tiene tiempo de ver 8 horas de video",
    "sospecho que un empleado me está robando",
    "se estan perdiendo cajas de cerveza del deposito y no se como",
    "como agarro al que juega vivo con la caja",
    "el inventario sale corto cada mes y creo que es gente de adentro",
    "salen cosas de la bodega fuera del horario de carga",
    "el pelao del turno de la noche cierra y siempre falta algo",
    "en la ferreteria desaparesen herramientas del almacen",
    "solo quiero ver los videos de cuando algo no cuadra en la caja",
    "¿hay cámaras que avisen solas cuando pasa algo raro en la caja?",
    "cuanto cuesta que las camaras me marquen cuando abren el cajon sin venta",
  ],
  C06: [
    "vender por internet",
    "ventas online con envio",
    "vender ropa online",
    "que me compren aunque la tienda esté cerrada",
    "quiero que los clientes del interior me compren y paguen en línea",
    "que el cliente escoja talla y color y pague ahí mismo",
    "vendo por instagram y quiero que paguen sin tener que escribirme",
    "cuanto cuesta montar una pagina para vender en panama",
    "algo como shopify pero que acepte yappy",
    "tengo 300 productos y quiero venderlos por internet",
    "que compren en la web y pasen a recoger a la tienda",
    "se me venden cosas que ya no tengo porque la página no descuenta",
    "mis clientes quieren comprar desde la casa y que se lo manden",
    "dejar de vender por marketplace y tener mi propia pagina con pagos",
    "nesesito vender online, con la tienda fisica sola ya no da",
    "cobrar el envío según la zona cuando compran por internet",
    "¿me puedes armar una página donde la gente compre con tarjeta y yappy?",
    "vendo canastas de regalo y quiero que las pidan y paguen en una pagina",
  ],
  C07: [
    "precio distinto en caja",
    "reimprimir etiquetas de precio",
    "cambiar precios en estantes",
    "el precio del estante no es el mismo de la caja",
    "el cliente agarra algo a un precio y en caja le sale otro",
    "subió el aceite y tengo q cambiar 40 etiquetas",
    "imprimir y pegar precios cada semana",
    "acodeco me puede multar si el precio del estante no cuadra?",
    "en el minisúper los precios de los estantes nunca están al día",
    "en la ferreteria la varilla cambia de precio cada rato y las etiquetas quedan viejas",
    "poner y quitar los presios de oferta del fin de semana a mano",
    "¿hay etiquetas de precio que se cambien desde la computadora?",
    "las pantallitas de precio en el estante como en los supers grandes",
    "el muchacho se pasa la noche cambiando precios en el súper",
    "cada vez que cambian los precios controlados hay que reetiquetar todo",
    "en la farmacia los precios de las medicinas cambian y la etiqueta no",
    "que la oferta empiece sola el viernes y se quite el domingo en los estantes",
    "gasto un buco en papel y etiquetas de precio",
    "cuánto cuesta que los precios del estante cambien solos",
  ],
  C08: [
    "tarjeta de sellos",
    "el décimo café gratis",
    "fidelizar clientes de la cafeteria",
    "la tarjetita de sellos de cartón se pierde",
    "me falsifican los sellos de la tarjeta",
    "premiar a los clientes que vienen seguido",
    "clientes que venían cada semana y dejaron de venir",
    "puntos por compra como los del super pero para mi negocio",
    "mandarle un mensaje al que tiene un mes sin venir",
    "sellos en el celular en vez de tarjeta de papel",
    "el labado numero 6 gratis en el autolavado",
    "corte gratis al décimo en la barbería",
    "cuanto cuesta darles puntos a mis clientes de la heladeria",
    "que el cliente acumule sin bajar ninguna app",
    "saber quienes vuelven mas y darles un premio",
    "la competencia da puntos y mis clientes se van pa alla",
    "en la farmacia quiero darle descuento al que compra su medicina todos los meses",
    "chuleta, ya no se cuantos sellos lleva cada cliente",
    "¿se puede dar un premio por cada 50 dólares que compre el cliente?",
  ],
  C09: [
    "wifi con correo",
    "limitar wifi de clientes",
    "wifi sin clave que pida datos",
    "la clave del wifi pegada en la pared y la usa todo el mundo",
    "gente que pasa todo el día con un café usando el wifi",
    "que el cliente ponga su correo o whatsapp pa conectarse al wifi",
    "conseguir el contacto de los clientes cuando se conectan al wifi",
    "página de bienvenida del wifi con mi logo como en los hoteles",
    "cuántos de los que se conectan al wifi vuelven",
    "cambiar la contraseña del wifi cada semana es un fastidio",
    "ponerle tiempo límite al wifi de los clientes",
    "que pide la ley para guardar los datos de los que usan mi wifi",
    "una hora de internet x cliente y despues q se desconecte",
    "el wifi de la heladeria lo usan los pelaos del colegio toda la tarde",
    "la gente me pide la clave del wifi a cada rato",
    "que los huespedes del hostal entren al wifi con su correo, no con clave",
    "¿se puede saber cuántos clientes nuevos llegan cada semana por el wifi?",
    "quiero aser una lista de clientes con el wifi del local",
    "cuanto cuesta un wifi que le pida el correo al cliente antes de conectarse",
  ],
  C10: [
    "muebles a tamaño real",
    "devoluciones por medidas",
    "girar producto en la web",
    "el cliente no sabe si el sofá le cabe en la sala",
    "me devuelven muebles porque no cabían",
    "que el cliente vea cómo queda el mueble en su casa con el celular",
    "como lo de ikea que pones el mueble en tu cuarto con la camara",
    "vendemos lavadoras y la gente no sabe si cabe en el espacio",
    "que puedan darle buelta al producto en la pagina",
    "me piden fotos del mueble por todos los lados",
    "que el cliente apunte la camara a su sala y vea el mueble ahi",
    "la gente quiere ver el producto de todos los ángulos antes de pagar",
    "¿se puede ver el mueble a tamaño real en la casa con el teléfono?",
    "que el cliente vea con el celular si la estufa le cabe en su cocina",
    "cuanto cuesta que mis muebles se puedan girar y ver en la casa del cliente",
    "comedor de 6 sillas: el cliente quiere ver si entra en su apartamento",
    "el cliente de chiriqui no puede venir a ver el mueble en persona",
    "el cliente tiene q venir hasta la tienda a medir el mueble",
    "ver como queda la lampara en la casa antes de comprarla",
  ],
  C11: [
    "pedidos regados en whatsapp",
    "pierdo pedidos en whatsapp",
    "mandar fotos y precios uno por uno por whatsapp",
    "los pedidos me llegan en notas de voz y se me confunden",
    "la lista de precios en pdf que mando por whatsapp nunca está al día",
    "un link con mis productos pa poner en el estado de whatsapp",
    "que el cliente arme su pedido y me llegue completo al whatsapp",
    "vendo cosméticos por whatsapp y se me enredan los pedidos",
    "el catálogo de whatsapp business se me queda corto",
    "vendo repuestos por whatsapp y paso el día mandando fotos",
    "que el pedido llegue con el total y yo solo mande el link de pago",
    "¿hay algo pa que vean lo que vendo y me pidan por whatsapp ya ordenado?",
    "en el chino de mi papa asemos delivery por whatsapp y los pedidos llegan desordenados",
    "sumar a mano el total de cada pedido de whatsapp",
    "los pedidos por whatsapp me llegan incompletos, sin cantidades ni total",
    "los clientes me piden el catalogo y no tengo",
    "cuanto cuesta tener mis precios en un link para compartir por whatsapp",
    "dejar de mandar 50 fotos a cada cliente",
  ],
  E01: [
    "los padres no pagan la mensualidad a tiempo",
    "perseguir a los acudientes pa que paguen",
    "no se quien esta al dia con la mensualidad",
    "cobrar mensualidades x yappy",
    "la matricula en papel es un relajo con tantos documentos",
    "lista de morosos del colegio",
    "academia de baile: las mamas pagan cuando se acuerdan",
    "los papas mandan ACH y no se de que niño es",
    "matricular en linea con los documentos del niño",
    "escuela de futbol: cobrar la mensualidad sin andar detras de los papas",
    "la secretaria cruza el estado del banco con la lista de pagos",
    "cuanto cuesta un sistema pa cobrar mensualidades en un colegio pequeño",
    "academia de ingles con alumnos que deben tres meses",
    "filas de padres pa matricular en febrero",
    "guarderia: los papas pagan en efectivo y se me pierden los recibos",
    "que cada papa vea cuanto debe",
    "padres morosos",
    "mensualidades atrasadas",
  ],
  E02: [
    "pasar lista en papel toma mucho tiempo",
    "avisar a los papas cuando el niño no llego a la escuela",
    "los empleados llegan tarde y no queda registro",
    "reloj pa marcar la entrada de los empleados",
    "la mama se entera en la tarde que el pelao no entro",
    "carnet con codigo pa marcar la entrada del colegio",
    "la maestra pierde 15 minutos pasando lista",
    "el supervisor quiere saber quien falto al turno sin llamar a nadie",
    "la lista de asistencia se pierde",
    "cuanto cuesta un lector de carnet pa la entrada de la escuela",
    "los papas no saben si su hijo entro al colegio",
    "pa la planilla cuento las tardanzas a mano",
    "el libro de firmas de entrada lo llenan como quieren",
    "academia: saber que alumnos faltaron sin pasar lista",
    "marcar asistencia",
    "en la bodega no se a que hora llego el turno de la noche",
    "pasar lista rapido",
    "tardanzas de empleados",
  ],
  E03: [
    "las circulares no llegan a la casa",
    "los papelitos de la escuela se quedan en la mochila",
    "el grupo de whatsapp de padres es un desorden",
    "avisar a todos los padres que se suspenden las clases por lluvia",
    "saber si los papas leyeron el aviso",
    "la secretaria contesta todo el dia a que hora salen y cuando es la reunion",
    "mandar un aviso solo a los papas de cuarto grado",
    "los padres dicen que nunca se enteraron de la reunion",
    "no quiero que los papas vean el numero de los demas",
    "avisos de ultimo momento del colegio",
    "la academia necesita avisar cambios de horario a las familias",
    "mandar las notas a cada papa por separado",
    "los papas no entran a la plataforma del colegio",
    "cierran calles por protestas y hay que avisar a las familias rapido",
    "cuanto cuesta mandar avisos del colegio x whatsapp a todas las familias",
    "en el chat de padres el aviso se pierde entre memes y quejas",
    "recordarles a los papas el acto civico de mañana",
    "circulares x whatsapp",
    "comunicados del colegio",
  ],
  H01: [
    "reservas directas sin comision",
    "reservar cabañas sin booking",
    "booking me cobra 15% por cada reserva",
    "quiero que me reserben directo sin pasar por airbnb",
    "que el huésped vea qué fechas hay libres sin escribirme",
    "cobrar el deposito de la reserva de la cabaña con yappy",
    "que en carnavales y semana santa la tarifa suba sola",
    "una familia quiere reservar 2 cabañas juntas el mismo fin de semana",
    "mandar cómo llegar a la finca después que reservan",
    "llevo las reservas en un cuaderno y nadie puede ver que fechas hay libres",
    "dejar de depender de airbnb para llenar el hostal",
    "la gente aparta la cabaña por whatsapp y despues no deposita",
    "cuánto cuesta un sistema de reservas para mi hostal",
    "airbnb se queda con una tajada de cada reserva",
    "hotelito de 8 habitaciones sin pagina para reservar",
    "apartan la cabaña por ACH y tengo que estar confirmando en el banco",
    "huéspedes que repiten quieren reservar directo y no tengo cómo",
    "¿se puede tener reservas en mi propia página como en booking?",
  ],
  H02: [
    "doble reserva",
    "overbooking entre airbnb y booking",
    "fechas cruzadas airbnb booking",
    "me cayeron dos reservas pa la misma noche",
    "serrar las fechas a mano en booking cuando me reservan en airbnb",
    "el calendario de airbnb no se actualizó y vendí la cabaña dos veces",
    "llegaron dos familias a la misma cabaña",
    "conectar el calendario de airbnb con el de booking",
    "tuve que reubicar a un huésped porque vendí la misma noche dos veces",
    "booking me penalizó por cancelarle a un huésped por doble reserva",
    "cada vez que reservan tengo que bloquear las fechas en las otras paginas",
    "expedia, airbnb y booking al mismo tiempo sin que se crucen las fechas",
    "manejar las mismas cabañas en airbnb y booking sin volverme loco",
    "como me entero si el calendario de booking dejo de actualizarse",
    "se me cruzaron reservas del hostal en semana santa",
    "me da miedo abrir en booking además de airbnb por las dobles reservas",
    "que me avise cuando el calendario de airbnb se pegue",
    "mi pagina y airbnb se pisan las fechas",
    "fechas vendidas que siguen abiertas en booking",
    "¿cuánto cuesta que no se me crucen las reservas de airbnb y booking?",
  ],
  H03: [
    "no quiero mas llaves",
    "entregar llaves de noche",
    "llegada autonoma pa mi airbnb",
    "esperar al huésped hasta las 12 de la noche pa darle la llave",
    "los huespedes se llevan las llaves",
    "perdieron la llave de la cabaña otra vez",
    "el huésped llega tarde de tocumen y no hay nadie que le abra",
    "que el huésped entre solo sin que yo tenga que ir",
    "cerradura con clave que cambie con cada huesped",
    "la cajita de llaves con clave ya la sabe todo el mundo",
    "saber a que hora entro la de limpieza a cada cabaña",
    "sacar copia de yaves cada vez que se pierde una",
    "apartamento de alquiler corto en el casco, entregar llaves es un lio",
    "que la clave de la puerta deje de servir cuando el huesped se va",
    "el muchacho que entrega las llaves me cobra cada vez que va",
    "un huésped de hace meses todavía tiene copia de la llave",
    "un codigo para la limpieza y otro para cada huesped",
    "¿tú me puedes poner cerraduras de teclado en las cabañas?",
    "cuanto cuesta cambiar las cerraduras de las cabañas por unas de clave",
  ],
  H04: [
    "libro de huespedes",
    "fotocopiar pasaportes en recepcion",
    "copia de cedula del huesped",
    "el huésped llega cansado y tiene que llenar la hoja de registro",
    "pedir la foto del pasaporte antes de que llegue",
    "que firmen las normas de la casa antes de llegar",
    "se me pierden las fichas de registro de los huespedes",
    "no se entiende la letra de los huespedes en el formulario",
    "que los huespedes firmen que no se permiten fiestas ni visitas extra",
    "guardar los datos de los huéspedes como pide la ley 81",
    "llega un grupo y se tardan media hora llenando papeles en recepcion",
    "el huesped llega a la 1am y no hay nadie pa tomarle los datos",
    "los extranjeros llegan sin saber que datos les voy a pedir",
    "un huésped rompió cosas y no tenía nada firmado",
    "¿hay forma de que el huésped llene sus datos antes de llegar?",
    "a la recepsionista del hotel se le olvida pedir la cedula",
    "formularios de papel en la recepción del hotel",
    "cuanto cuesta que los huespedes llenen el registro desde el celular",
  ],
  H05: [
    "fuga de agua escondida",
    "cabaña vacia gastando luz",
    "cuanta luz gasta cada cabaña",
    "el recibo de luz de las cabañas llegó altísimo y no sé cuál gasta más",
    "se bacio el tanque de las cabañas de madrugada y nadie uso agua",
    "un inodoro de las cabañas se queda corriendo y me vacia el tanque",
    "saber si quedó el aire prendido en una cabaña vacía",
    "cobrarle la luz aparte a cada apartamento que alquilo",
    "en las cabañas se va el agua y no sé cuánto queda en el tanque",
    "que me avise cuando el tanque de las cabañas este bajo",
    "cuanto cuesta poner un medidor de luz en cada cabaña",
    "la cuenta de luz subio y las cabañas estuvieron medio vacias",
    "los huéspedes de larga estadía gastan un buco de luz",
    "los huespedes se quedan sin agua y yo no sabia que el tanque estaba vacio",
    "detectar consumo raro de luz en una cabaña",
    "¿cuánto gasta de luz una cabaña con huéspedes y sin huéspedes?",
    "subo con linterna a ver cuanta agua le queda al tanque de las cabañas",
    "comparar cuanta luz gasta cada cabaña en temporada alta y baja",
  ],
  H06: [
    "aire desde el celular",
    "casa inteligente pa airbnb",
    "luces de cabañas a distancia",
    "prender las luces antes de que llegue el huésped",
    "los huéspedes se van y dejan todo prendido",
    "que la cabaña esté fresquita cuando llegue el huésped",
    "estoy en la ciudad y las cabañas en la playa, quiero apagar todo desde aquí",
    "mandar al muchacho a apagar los aires de las cabañas vacias",
    "controlar el aire acondicionado de las cabañas por wifi",
    "que se apage todo solito cuando el huesped hace checkout",
    "la luz del portal de la cabaña se queda prendida todo el dia",
    "el huesped llega de noche y la cabaña esta oscura",
    "el huesped se queja que la cabaña estaba caliente al llegar",
    "¿se puede manejar el aire de cada cabaña desde el celular?",
    "apagar los aires que dejan prendidos sin tener que ir hasta alla",
    "vivo lejos de mis cabañas y no tengo quien apague las luces",
    "ver desde el celular qué luces quedaron prendidas en las cabañas",
    "cuanto cuesta poner las luces y el aire de las cabañas en el celular",
  ],
  I01: [
    "vigilar tanque y neveras desde el cel",
    "ver en el celular los cuartos fríos, el tanque y la luz de la bodega",
    "el tanque de reserva del restaurante se vacía y nos enteramos cuando ya no sale agua",
    "el portón de atrás de la bodega se queda abierto de noche y nadie se da cuenta",
    "quiero saber cuándo baja el diesel del tanque de la planta eléctrica",
    "mando un pelao a revisar neveras, tanque y tablero a diario, ¿algo que avise solo?",
    "que me llegue un whatsapp si la temperatura, el agua o la luz se salen de lo normal",
    "el tanque del edificio se rebosa o se queda vacío y nadie se entera",
    "tengo 3 congeladores, un cuarto frío y el tanque, y no sé cómo están de noche",
    "la distribuidora queda sola el fin de semana: ¿siguen bien los cuartos fríos y el tanque?",
    "quiero un historial de temperaturas y consumo pa comparar este mes con el pasado",
    "algo que vigile la planta de noche: temperatura, tanque y si quedó una puerta abierta",
    "que me avise si de noche la planta está gastando luz como si estuviera trabajando",
    "todo lo del local en una pantalla: neveras, luz, agua y puertas",
    "en el hotel quiero ver en el teléfono la cisterna, las neveras y el consumo de luz",
    "¿hay algo que avise al whatsapp cuando el tanque de agua del local está bajito?",
  ],
  I02: [
    "dónde andan mis camiones",
    "rastrear motos de reparto",
    "el repartidor dice que estava en tranque pero no le creo",
    "el chofer se va a hacer sus vueltas con el pickup de la empresa",
    "un camión estuvo una hora parado fuera de ruta y nadie sabe por qué",
    "quiero ver por dónde pasaron los camiones ayer",
    "el cliente llama q dónde viene el camión con su mercancía y no sé qué decirle",
    "¿cuánto cuesta ponerle gps a los camiones de reparto?",
    "que me avise si el camión se sale de la zona que le toca",
    "sospecho que los choferes dan vueltas de más con el camión",
    "los choferes cobran horas extras y no sé si de verdad estaban en la calle",
    "distribuidora de agua en botellón, quiero saber dónde está cada camión",
    "si me roban la moto de reparto quiero saber dónde está",
    "quiero saber a qué hora llegó el camión a cada cliente de la ruta",
    "¿hay algo para ver en un mapa dónde están los carros de la empresa ahorita?",
    "los conductores se paran una hora a comer en cada fonda del camino",
    "camiones que van pal interior y no sé por dónde andan",
    "el mensajero de la farmacia se tarda toda la tarde en dos entregas",
    "la ferretería reparte materiales en camión y no sé cuánto se demora en cada obra",
  ],
  I03: [
    "registro de carros del PH",
    "el guardia anota las placas en un cuaderno y no se le entiende la letra",
    "que la pluma le abra sola a los residentes",
    "no sé a qué hora entró y salió cada carro del estacionamiento",
    "carros de afuera se parquean en los puestos de los inquilinos",
    "los controles del portón del estacionamiento se pierden y toca cambiarlos todos",
    "fila en la garita en la mañana porque el guardia apunta cada placa",
    "camiones de proveedores entran al patio y nadie lleva registro de cuáles",
    "el que juega vivo se mete detrás del carro de un residente y nadie sabe quién era",
    "quiero que el portón de la bodega abra solo para los carros de los empleados",
    "en el hotel no sabemos qué carros del estacionamiento son de huéspedes",
    "¿cuánto cuesta una cámara q lea placas pa la entrada del edificio?",
    "edificio de oficinas: saber a qué hora llegan y se van los carros de cada empresa",
    "el guardia le levanta la pluma a todo el mundo sin preguntar",
    "me rayaron el carro en el parking y no hay registro de qué carros entraron",
    "lista de carros que pueden entrar y que el resto quede anotado con la hora",
    "parqueo de la empresa lleno de carros que no son de empleados",
  ],
  I04: [
    "quién entró al depósito",
    "un empleado se fue y se llevó la llave de la oficina",
    "cambiar la cerradura cada vez que alguien renuncia",
    "no sé quién entró al cuarto de medicinas de la clínica",
    "el técnico del aire tiene que entrar solo esta tarde y no quiero darle llave",
    "las llaves de la bodega las tienen como 5 personas y ya no sé quién sacó copia",
    "quiero que la cajera solo pueda entrar a la oficina en su horario",
    "los proveedores entran por la puerta de la bodega y no queda registro de nada",
    "el libro de visitas de la recepción nadie lo llena bien",
    "que los empleados abran la puerta con el celular en vez de llave",
    "quitarle la entrada desde mi celular a alguien que despedí",
    "en el gym siguen entrando socios que no han pagado",
    "el contratista viene 3 días y después no quiero que pueda entrar",
    "¿cuánto cuesta poner una puerta que abra con tarjeta en la oficina?",
    "al cuarto de servidores entra todo el mundo y solo deberían entrar dos",
    "en el coworking quiero que cada quien entre solo en el horario que pagó",
    "alguien abrio la bodega el domingo y no ay forma de saber quien fue",
    "en el colegio entran visitas y nadie sabe quién estuvo adentro",
  ],
  I05: [
    "obreros sin casco",
    "los trabajadores no se ponen el casco cuando no estoy",
    "en el patio los del montacargas no ven a la gente que anda sin chaleco",
    "el supervisor no puede estar en todos lados vigilando que usen el chaleco",
    "en la obra se quitan el casco apenas me doy la vuelta",
    "si un pelao se golpea sin casco después es un lío con la CSS",
    "la inspección de seguridad nos llamó la atención por gente sin chaleco",
    "quiero saber a qué horas anda la gente sin casco en la planta",
    "¿hay algo q me avise con foto cuando alguien entra sin casco a la zona de carga?",
    "en la bloquera se quitan el chaleco por el calor",
    "¿cuánto cuesta una cámara que vea si la gente lleva casco y chaleco?",
    "patio de contenedores con gente caminando sin chaleco entre las grúas",
    "pelaos sin chaleco reflectivo en el almacén",
    "necesito fotos de cuando no usan el casco pa poder hablar con ellos",
    "cuántas veces entraron sin casco esta semana",
    "en el aserradero nadie usa el casco aunque se los compré",
    "jente sin chaleco donde pasan los camiones",
  ],
  I06: [
    "contar sacos por turno",
    "no sé cuánto se produjo hoy hasta que el capataz me trae la hoja",
    "el turno de la noche rinde menos y no tengo cómo probarlo",
    "quiero ver desde la oficina cuántos bloques van hoy",
    "anotan con palitos en un papel cuántas cajas salen de la línea",
    "la meta son 2000 botellas al día y a media tarde no sé cómo vamos",
    "cuántas piezas por hora saca la máquina",
    "los muchachos dicen q sacaron 500 cajas y yo cuento 430",
    "quiero saber cuántas cajas salen por la puerta de carga cada hora",
    "¿hay algo q cuente solo las cajas que pasan por la banda?",
    "en el molino quiero saber cuántos sacos de arroz salen por el portón en cada turno",
    "cuántas bandejas de pan salen del horno por hora en la panadería",
    "comparar la producción de un turno contra el otro sin esperar el reporte",
    "¿cuánto cuesta algo que cuente la producción de la línea de empaque?",
    "producción por hora sin estar en la planta",
    "las piesas que salen de la línea se cuentan a mano al final del turno",
    "en la fábrica de hielo nadie sabe cuántas bolsas se hicieron por turno",
  ],
  I07: [
    "motor de la planta se recalienta",
    "se nos dañó el compresor sin aviso y paramos dos días",
    "la bomba de agua se quemó y nadie notó que estaba sonando raro",
    "el motor se calienta y nos damos cuenta cuando ya botó humo",
    "quiero saber que un motor se va a dañar antes, no después",
    "el mecánico de la planta solo se entera cuando el motor ya se dañó",
    "si para el compresor, para toda la planta de hielo",
    "la bomba del pozo empiesa a vibrar y a la semana se friega",
    "cada vez que se quema un motor perdemos un día entero de producción",
    "¿hay algo que avise al whatsapp cuando una máquina empieza a vibrar raro?",
    "los rodamientos se gastan y no avisan hasta que se traba todo",
    "mantenimiento quiere saber qué equipo está fallando antes de que pare",
    "compresor que se calienta más de lo normal",
    "la banda se para porque se quema el motor y no tenemos repuesto",
    "el extractor suena raro y cuando uno se da cuenta la vaina ya se quemó",
    "¿cuánto cuesta algo que vigile los compresores y avise antes de que se dañen?",
  ],
  I08: [
    "pesos anotados a mano",
    "el pesador anota los pesos de los camiones en un cuaderno",
    "los pesos que anotan a mano no cuadran con lo que pagamos",
    "copiar el ticket de la báscula a Excel todos los días",
    "sospecho que el pesador juega vivo y le pone kilos de más a algunos",
    "la báscula es vieja, ¿se puede conectar a la compu?",
    "en el patio de chatarra cada pesada se escribe en una libreta",
    "compramos café por peso a los productores y todo queda en papel",
    "alguien lee el medidor del tanque de combustible y lo apunta, a veces mal",
    "quiero el reporte de lo que se pesó hoy sin esperar al pesador",
    "¿cuánto cuesta conectar la báscula de camiones al sistema?",
    "el peso de cada lote de cacao lo copia una muchacha a mano y se equivoca",
    "la bascula de la galera y el sistema no se hablan",
    "en la arrocera el peso de cada viaje de arroz en cáscara se anota a mano",
    "el medidor de agua de la planta lo lee alguien a ojo cada mañana",
    "en la subasta anotamos el peso de cada res a mano",
    "x cada camión hay que escribir el peso dos veces: en el ticket y en la compu",
  ],
  I09: [
    "cuánto ahorro con paneles",
    "consumo de luz por área",
    "puse paneles solares y no sé cuánto me estoy ahorrando",
    "la factura de la luz sigue alta aunque tengo paneles",
    "no sé qué parte del negocio gasta más luz",
    "la cuenta de luz llegó en $900 y no sé de dónde sale tanto",
    "el instalador me prometió que iba a ahorrar la mitad y no sé si es verdad",
    "la app del inversor solo me dice kWh y no entiendo nada",
    "cuánta luz gasta la cocina y cuánta los aires del salón",
    "antes de poner paneles quiero saber cuánto consumo de día",
    "no sé si los paneles están produciendo lo que deberían",
    "Naturgy me cobra un buco y no sé qué es lo que más consume",
    "quiero ver cada mes cuánto me dieron los paneles en plata, no en kWh",
    "en el hotel quiero ver cuánto gastan las habitaciones contra la lavandería",
    "cuánta luz se come cada máquina de la fábrica",
    "¿valió la pena lo que gasté en los paneles?",
    "los aires de la oficina se comen la luz y no se cuanto exactamente",
    "en el minisúper los congeladores se comen la luz, quiero saber cuánto",
  ],
  I10: [
    "goteras en la galera",
    "se me filtra el techo de la bodega y no sé por dónde",
    "subir al techo de zinc es peligroso y no quiero que nadie se caiga",
    "quiero ver el avance de la obra sin ir cada semana",
    "el contratista dice que va por el 60% y no le creo",
    "después del ventarrón se levantaron láminas del techo y no sé cuántas",
    "tengo una finca grande y quiero ver cómo están las cercas sin caminarla toda",
    "alquilar andamio solo pa revisar el techo sale carísimo",
    "mandarle fotos del avance de la obra al dueño que vive afuera",
    "saber exactamente dónde están las goteras para mandar al techero directo",
    "quiero ver si se metieron precaristas en el terreno sin recorrerlo entero",
    "el techo del edificio tiene filtraciones y nadie quiere subir",
    "¿cuánto cobran por revisar un techo con dron?",
    "comparar mes a mes cómo va la construcción vista desde arriba",
    "la canaleta del techo se tapa y desde abajo no se ve nada",
    "chuleta, otra vez se mojó la mercancía por el techo y no encontramos el hueco",
    "ver si hubo deslizamientos en el terreno después de las lluvias",
    "mopri, ¿sabes de alguien que revise techos con dron? el de la bodega gotea",
  ],
  R01: [
    "los turistas no entienden la carta",
    "carta en ingles",
    "solo tengo 3 cartas y los clientes esperan pa verla",
    "el cliente pide de la carta un plato q ya se acabo",
    "¿hay algo pa que el cliente vea la carta en su celular?",
    "cuanto cuesta tener mi carta en el telefono del cliente",
    "me preguntan a cada rato si el plato lleva mani o mariscos",
    "café en Boquete, la mitad de los clientes solo habla inglés",
    "el cuadrito que escaneas y te sale el menu",
    "el qr de la carta dejo de servir cuando cambie de proveedor",
    "quiero cambiar los precios de la carta yo misma desde el cel",
    "los meseros pierden tiempo explicando cada plato a los extranjeros",
    "menu pa turistas",
  ],
  R02: [
    "los clientes esperan mucho pa que les tomen el pedido",
    "nadie trae la cuenta",
    "cada uno quiere pagar lo suyo",
    "que el cliente pague desde la mesa con yappy",
    "dibidir la cuenta entre 6 amigos es un relajo",
    "me da pena preguntarle al cliente cuanta propina va a dejar",
    "los viernes no tengo suficientes meseros pa tomar pedidos",
    "llamar al mesero sin estar alzando la mano",
    "¿hay algo pa que los clientes pidan otra ronda sin esperar?",
    "cevicheria con 14 mesas y solo 2 meseros",
    "la gente se para a pagar en la caja y se forma un tranque",
    "cuanto cuesta que el cliente pida y pague con su celular en la mesa",
    "el mesero entiende mal lo que pidio el cliente",
    "la gente se aburre esperando la cuenta y se va molesta",
    "pedir la cuenta sin hacer señas",
    "propina que escoja el cliente",
    "en la terraza los clientes no encuentran a quien pedirle otra cerveza",
    "la cuenta se tarda",
  ],
  R03: [
    "acercar el celular a la mesa y que salga la carta",
    "con poca luz no lee el qr",
    "los señores mayores no saben escanear el codigo",
    "como cuando pagas acercando el cel, pero que abra el menu",
    "tocar la placa y ver el menu",
    "pegatina en la mesa que abre la carta con solo tocarla",
    "a los clientes no les escanea el qr de la mesa",
    "abrir el menu sin la camara",
    "que ningun juega vivo pueda cambiar a donde lleva la placa de la mesa",
    "bar oscuro en el Casco, la camara no enfoca el codigo",
    "algo mas rapido que escanear pa ver la carta",
    "hostal: que el huesped toque la placa y vea el menu del restaurante",
    "placas de madera pa las mesas que abran la carta al acercar el telefono",
    "¿hay alguna placa que funcione sin abrir la camara?",
    "la camara del celular se tarda en leer el cuadrito",
    "tocar pa ver menu",
    "menu sin escanear",
  ],
  R04: [
    "no se que mesa esta libre",
    "desde la caja no veo cuanto lleva cada mesa",
    "el cajero tiene que salir a preguntar que mesa pidio la cuenta",
    "una mesa se fue sin pagar y nadie se dio cuenta",
    "ver todo el salon en una pantalla",
    "los domingos juntamos mesas y se enredan las cuentas",
    "cuanto lleva la mesa 12",
    "salon y terraza, no se cual mesa ya pidio",
    "llega un grupo y no se donde sentarlo",
    "se cruzan las cuentas de la mesa 4 y la 5",
    "los meseros le cobran a la mesa equivocada",
    "¿hay algo pa ver todas las mesas y lo que ha pedido cada una?",
    "mesas ocupadas y libres en la compu de la caja",
    "al cobrar la mesa no me sale el itbms aparte",
    "que mesas faltan por cobrar",
    "mesas libres u ocupadas",
  ],
  R05: [
    "las comandas de papel se pierden en la cocina",
    "el cocinero no entiende la letra del mesero",
    "los pedidos salen en desorden",
    "en la cocina no saben cuanto lleva esperando cada pedido",
    "el papelito del pedido se mojo y no se leia",
    "la parrilla y el bar se gritan los pedidos",
    "el mesero no sabe cuando el plato esta listo",
    "que los pedidos salgan en una tele en la cocina",
    "platos listos enfriandose en el pase",
    "el pincho de comandas se llena y se confunden",
    "los viernes en la noche se olvidan pedidos en la cocina",
    "cada estacion que vea solo lo suyo",
    "¿como hago pa que el cocinero avise cuando sale el plato?",
    "el bar se entera tarde de las bebidas",
    "comandas perdidas",
    "cuanto cuesta una tablet en la cocina pa ver los pedidos",
    "pedidos atrasados en cocina",
    "tele pa la cocina",
  ],
  R06: [
    "la fila pa pedir llega hasta la puerta",
    "una maquinita como la de McDonald's pa que pidan solos",
    "a la hora del almuerzo la gente se va por la fila",
    "una sola cajera pa tomar pedidos y fila larga",
    "que el cliente se haga el pedido solo en una pantalla",
    "comida rapida en la plaza, la caja no da abasto",
    "que salga el numero de orden y avisar cuando esta listo",
    "que le ofrezca las papas y el refresco sin que la cajera se acuerde",
    "hamburgueseria con fila al mediodia en La Chorrera",
    "cuanto cuesta una pantalla tactil pa que los clientes pidan",
    "con tanta gente la cajera se equivoca tomando los pedidos",
    "necesito otra caja pero no tengo pa pagar otro cajero",
    "heladeria: en la hora pico la fila es eterna",
    "autoservicio pa pedir comida",
    "la gente se demora decidiendo en la caja y atrasa la fila",
    "fila pa pedir",
    "kiosko pa pedir comida",
  ],
  R07: [
    "un link pa que me pidan comida desde instagram",
    "no quiero pagar comision por cada pedido de delivery",
    "cobrar el delivery segun el barrio",
    "los clientes me preguntan cuanto es el delivery a su zona",
    "que paguen con yappy en la pagina antes de mandar la comida",
    "pizzeria con repartidor propio, quiero que me pidan directo y no por la app",
    "pedidos pa llevar sin hacer fila",
    "que no me puedan pedir fuera de mi horario",
    "contra entrega o yappy, que el cliente escoja al pedir",
    "que me pidan el almuerzo por internet sin pagarle comision a nadie",
    "cuanto cuesta una pagina pa recibir pedidos de comida",
    "carrito de compras pa mi restaurante",
    "pedidosya se come la ganancia",
    "fonda que reparte almuerzos a oficinas, quiero que pidan en una pagina",
    "¿hay algo pa que me pidan a domicilio sin pasar por pedidosya?",
    "delivery propio sin app",
    "link pa pedir comida",
  ],
  R08: [
    "me reservan por instagram y se me pierden los mensajes",
    "reservan mesa y no llegan",
    "anoto las reservas en un cuaderno",
    "los sabados se llena y no se cuantas reservas puedo aceptar",
    "lista de espera pa cuando se llena el turno",
    "que el cliente aparte mesa sin llamar",
    "dos grupos con la misma mesa apartada",
    "contestar llamadas pa reservar en plena hora pico",
    "¿como hago pa que la gente aparte mesa desde el link de instagram?",
    "aparto mesas por whatsapp y se me olvida anotarlas",
    "recordarle al cliente su reserva de la cena",
    "el dia de las madres las reservas son un caos",
    "reserva pa cumpleaños sin llamar al restaurante",
    "cuanto cuesta un sistema pa reservar mesa en mi restaurante",
    "apartar mesa",
    "me dejan la mesa reservada vacia un viernes",
  ],
  R09: [
    "los precios del letrero del mostrador estan viejos",
    "cada vez que cambio el plato del dia tengo que borrar la pisarra",
    "tele sobre la caja con el menu",
    "que el menu de la tele cambie solo del desayuno al almuerzo",
    "se acabo el sancocho y sigue apareciendo en el menu de la pared",
    "el banner de precios hay que mandarlo a hacer otra vez",
    "la pizarra con tiza se ve fea",
    "usar los televisores que ya tengo pa mostrar los platos",
    "desde la fila la gente no ve bien los precios",
    "panaderia: los precios de la pared ya no son esos",
    "promos en la tele del local a cierta hora",
    "cuanto cuesta poner pantallas con el menu en mi cafeteria",
    "el letrero luminoso del menu no se puede cambiar",
    "cambiar lo que sale en la tele del local desde el celular",
    "menu en la pared",
    "el cartel de arriba de la caja dice un precio y cobro otro",
    "pizarra del menu",
    "tele con precios",
  ],
  R10: [
    "se daño la nebera de noche y perdi toda la carne",
    "el congelador se apago el fin de semana y nadie se dio cuenta",
    "los muchachos dejan la puerta del cuarto frio abierta",
    "el minsa me pide el registro de temperaturas",
    "que me avise al whatsapp si la nevera se calienta",
    "perdi 800 dolares en mariscos por un congelador malo",
    "farmacia con insulina y vacunas, me preocupa la temperatura de la nevera",
    "anotar la temperatura de las neveras a mano todos los dias",
    "termometro que mande mensaje",
    "en el chino los helados amanecen derretidos",
    "cuarto frio de la carniceria sin nadie en la noche",
    "clinica: las vacunas tienen que estar entre 2 y 8 grados",
    "alarma si la puerta del congelador se queda abierta",
    "cuanto cuesta un sensor pa la nevera que avise",
    "nevera caliente",
    "quiero saber si la nevera estuvo caliente mientras no habia nadie",
    "cuarto frio caliente",
  ],
  R11: [
    "la caja no cuadra al final del turno",
    "no se cuanto vendio cada cajero",
    "todavia uso una caja registradora vieja",
    "en el minisuper anoto las ventas en un cuaderno",
    "vendo y el inventario no baja solo",
    "cierre de caja por turno",
    "en el cierre falta plata y no se de cual cajero",
    "lector de codigo de barras pa el minisuper",
    "impresora de tickets y cajon de dinero",
    "vendo en mesas y en mostrador y no tengo un sistema pa las dos",
    "cuanto cuesta un sistema de caja pa mi panaderia",
    "vendo un pan con jamon y no se cuanto jamon me queda",
    "se daño la impresora fiscal y necesito otra caja que haga factura electronica",
    "dejar de cobrar con calculadora",
    "cobrar rapido escaniando en el chino",
    "programa pa la caja de la fonda",
    "caja registradora",
    "cuadrar la caja",
    "cobrar con escaner",
  ],
  R12: [
    "quiero mi propia app como pedidosya",
    "app de pedidos pa mis 3 sucursales",
    "varios restaurantes de la plaza queremos una app de delivery juntos",
    "el cliente quiere ver por donde viene su pedido como en uber eats",
    "pedidosya me cobra 30% hasta a mis clientes de siempre",
    "app en el play store con el nombre de mi restaurante",
    "que el cliente pida hamburguesa y helado de dos locales en un solo pedido",
    "repartir los pedidos entre mis motorizados",
    "cuanto me sale tener una app pa pedidos a domicilio con mi marca",
    "cada sucursal recibe pedidos por su lado y es un desorden",
    "tengo 5 motorizados y quiero dejar las apps que cobran comision",
    "que cada local vea solo sus ventas en la app compartida",
    "el cliente no sabe a que hora le llega la comida",
    "franquicia chiquita con 4 locales, delivery con app propia",
    "mis motorizados no saben que pedido llevar primero",
    "uber eats se queda con la ganancia de mis tres locales",
    "app pa varios restaurantes",
  ],
  R13: [
    "paso el dia copiando pedidos del whatsapp a la cocina",
    "los viernes me llegan 60 pedidos por whatsapp y no doy abasto",
    "el que contesta el whatsapp anota mal la direccion",
    "que alguien conteste el whatsapp y tome el pedido mientras cocino",
    "bot pa tomar pedidos de comida x whatsapp",
    "por whatsapp me piden sin cebolla y en la cocina no llega",
    "que el pedido del whatsapp salga impreso en la cocina",
    "me escriben pa pedir pizza a las 11 y nadie contesta",
    "confirmar direccion y yappy de cada pedido es un relajo",
    "pedidos de whatsapp directo a la impresora de la cocina",
    "copio el pedido del whatsapp en un papel y me equivoco",
    "el que contesta ofrece platos que ya se acabaron",
    "cuanto cuesta que un asistente tome los pedidos de mi restaurante por whatsapp",
  ],
  S01: [
    "ausencias de pacientes",
    "citas cruzadas en el consultorio",
    "recordar citas a pacientes",
    "los pacientes no llegan y no avisan",
    "la recepcionista se pasa el día llamando para confirmar citas",
    "pacientes que dejan plantado al doctor",
    "dos pacientes a la misma hora con el mismo doctor",
    "que el paciente saque su cita solo desde una página, sin llamar",
    "en la veterinaria la gente se olvida de la cita de la vacuna",
    "el fisioterapeuta pierde plata con las citas que no llegan",
    "llamar uno por uno a confirmar las citas de mañana",
    "si el paciente no contesta que le vuelvan a escribir solo",
    "cuánto cuesta que le llegue un recordatorio por whatsapp a cada paciente",
    "pacientes que dicen que nadie les recordó la cita",
    "el odontologo pierde la mañana por citas que no bienen",
    "en la oficina los clientes se olvidan de la cita con el abogado",
    "dos doctoras, una sola recepcionista y la agenda es un relajo",
    "¿hay algo que confirme las citas por WhatsApp con un botón?",
    "huecos en la agenda x gente que no confirma",
  ],
  S02: [
    "sala de espera desordenada",
    "llamar pacientes por numero",
    "gritar nombres en la sala",
    "la secretaria grita el nombre del paciente en la sala",
    "los pacientes no saben cuánto les falta",
    "nadie sabe a quién le toca en la sala de espera",
    "una pantalla que diga el número del siguiente como en el banco",
    "se pelean en la sala de espera por quien yego primero",
    "no quiero que se oigan los nombres de los pacientes en voz alta",
    "en la sala de espera dicen que alguien se coló",
    "turnos para 4 consultorios en una sola sala",
    "en el laboratorio llamar a la gente por numero pa la toma de muestra",
    "el doctor sale a la puerta a buscar al siguiente",
    "tengo un tele en la sala de espera y quiero que muestre los turnos",
    "en la oficina de cobros atendemos por orden de llegada y es un relajo",
    "la recepcionista se asoma a cada rato a llamar pacientes",
    "llamar al siguiente paciente desde el celular del doctor",
    "papelitos con número en la clínica que se pierden",
    "¿cuánto cuesta que la tele de la sala llame a los pacientes por número?",
  ],
  S03: [
    "enterarme de quejas primero",
    "satisfaccion de pacientes",
    "clientes insatisfechos que no dicen nada",
    "saber si el paciente quedó contento",
    "me enteré de la queja por google y ya era tarde",
    "preguntarle al cliente cómo le fue al día siguiente",
    "que me avise cuando un cliente se va molesto",
    "me pusieron 1 estrella y en el local nunca dijeron nada",
    "la gente no se queja en el momento y despues pone mala reseña",
    "el cliente se fue bravo y no me dijo nada",
    "saber qué doctor tiene pacientes descontentos",
    "ay forma de saber si los clientes del restaurante salen satisfechos?",
    "enterarme de las quejas antes de que las pongan en internet",
    "que los contentos me dejen reseña y los molestos me digan a mi primero",
    "el huesped se fue molesto y me entere por la reseña",
    "mandar una pregunta corta por whatsapp después de la consulta",
    "el mesero atendio mal y me entere una semana despues",
    "el buzon de sugerencias no lo usa nadie",
    "¿cuánto cuesta preguntarle a cada cliente del 1 al 5 cómo lo atendimos?",
  ],
  S04: [
    "telemedicina pa consultorio pequeño",
    "consulta en linea pagada",
    "citas de seguimiento a distancia",
    "¿hay forma de cobrar la consulta antes de la videollamada?",
    "pacientes del interior que no pueden venir a la consulta",
    "hago consultas por videollamada de whatsapp y despues no me pagan",
    "sesiones de psicología en línea con pago adelantado",
    "revisar resultados por video sin que el paciente tenga que venir",
    "el zoom gratis se me corta a los 40 minutos",
    "nutricionista: seguimiento a pacientes por video",
    "paciente que vive fuera del país quiere consulta",
    "cobrar con yappy antes de la consulta por video",
    "que el paciente entre a la llamada con un link sin bajar nada",
    "me dejan esperando en la videollamada y ni pagaron",
    "atender pasientes por video desde la casa",
    "cuánto cuesta una plataforma para consultas virtuales en mi consultorio",
    "con el tranque los pacientes llegan tarde, quiero darles consulta por video",
    "que las consultas por video no se crucen con las del consultorio",
  ],
  S05: [
    "historias clínicas en papel",
    "carpetas de pacientes",
    "llevo los expedientes en excel",
    "no encuentro el expediente del paciente",
    "fotos de antes y después de los pacientes regadas en mi celular",
    "la recepcionista puede ver todo el historial y no debería",
    "cuando el paciente vuelve no se que le recete la ultima bez",
    "el archivo de papel ya no cabe en el consultorio",
    "se me mojaron unas historias clinicas con la lluvia",
    "dos doctores ven al mismo paciente y cada uno tiene sus notas aparte",
    "anotar la evolución de cada sesión de fisioterapia",
    "resultados de laboratorio que me mandan por whatsapp y se pierden",
    "tengo los datos de los pacientes en un cuaderno, eso cumple la ley 81?",
    "dejar de escribir las historias a mano",
    "comparar las fotos de control de un paciente por fecha",
    "el peso y las medidas de cada paciente en hojas sueltas",
    "que solo el doctor vea el diagnóstico y la secretaria solo las citas",
    "buscar el historial de un paciente me toma 10 minutos",
    "cuanto cuesta tener las historias de los pacientes en la computadora",
  ],
  T01: [
    "solo tengo instagram",
    "no tengo pagina",
    "mi web se ve fea en el cel",
    "la gente me pide un link para ver mis trabajos y solo tengo facebook",
    "la página que me hizo mi sobrino ya ni abre",
    "cuanto cuesta que me hagan una pagina pa mi taller",
    "quiero un link donde vean mis servicios y me escriban directo al whatsapp",
    "me da pena dar mi facebook como si fuera la web de la empresa",
    "las empresas grandes me piden un sitio donde ver lo que hago antes de contratarme",
    "mi página tarda demasiado en abrir en el teléfono y la gente se sale",
    "la plantilla que tengo se ve igualita a la de todo el mundo",
    "¿hay algo pa q mi consultorio tenga su propia pagina?",
    "si me cierran el instagram me quedo sin donde mostrar lo que hago",
    "el que me hizo el sitio desaparecio y no puedo cambiar ni el telefono",
    "mi web tiene los precios de hace tres años y no se como cambiarlos",
    "algo serio en internet pa mi empresa de fumigación, no un perfil de facebook",
    "mi negocio no existe en internet fuera de las redes",
    "conoces a alguien q haga paginas?",
    "link pa mis trabajos",
  ],
  T02: [
    "todo en excel ya no da",
    "el excel compartido se daña cuando lo abren dos a la vez",
    "nadie sabe cuál es la versión buena del excel",
    "pago tres programas y ninguno hace lo que necesito",
    "ningun programa de los que venden sirve para como trabajamos",
    "los técnicos llaman a la oficina para saber a dónde les toca ir hoy",
    "toda la operacion vive en cuadernos y papelitos",
    "cada empleado tiene su propio excel y nada cuadra",
    "quiero un sistema propio pa mi empresa, no uno generico",
    "administro 12 apartamentos y llevo en una libreta quien vive, cuanto paga y cuando vence",
    "el sistema que compramos nos obliga a trabajar como ellos quieren",
    "en la lavanderia anotamos las ordenes en papel y se confunden las bolsas",
    "las notas de los estudiantes andan en el excel de cada profe",
    "si se va la secretaria nadie entiende sus hojas de calculo",
    "pasamos más tiempo arreglando el excel que trabajando",
    "que cada puesto vea solo lo suyo y no un excel que todos tocan",
    "cuanto cuesta hacer un programa para mi distribuidora",
    "llebo los mantenimientos de los aires en un excel que ya es un desastre",
    "todo en excel",
    "sistema pa mi empresa",
  ],
  T03: [
    "app pa mi negocio",
    "app que funcione sin internet",
    "mis clientes me preguntan si tengo app",
    "mis vendedores en el interior se quedan sin señal y no pueden anotar los pedidos",
    "que mi negocio salga en la play store",
    "cuanto cuesta una app para android y iphone",
    "en las fincas no hay señal y los muchachos anotan todo en papel",
    "quiero que mi gimnasio tenga su propia app con mi logo",
    "los inspectores llenan formularios en el campo donde no hay internet",
    "subir mi aplicacion al app store de apple",
    "la competencia ya tiene app y yo no",
    "una app para mis vendedores de ruta en chiriqui",
    "mi equipo en la calle necesita algo en el celular q funcione sin datos",
    "los tecnicos trabajan en sotanos sin señal y pierden lo que anotan",
    "la app tiene que funcionar en iphone y en android, ¿la hacen pa los dos?",
    "nesesito una aplicasion pa mi empresa",
    "mis clientes entran todos los dias y piden algo que se instale en el cel",
    "¿me conviene una app o me basta con la pagina?",
    "app sin señal",
    "app pa mis vendedores",
  ],
  T04: [
    "copiar y pegar todo el dia",
    "pasar datos a mano",
    "paso las noches copiando los pedidos del correo al excel",
    "todos los lunes armo el mismo reporte a mano",
    "la secretaria pasa la mañana metiendo al sistema lo que llega de los formularios",
    "las respuestas del formulario de google alguien las copia una x una",
    "hay una tarea repetida que nos come tres horas diarias",
    "quiero que esto se haga solo, siempre es lo mismo",
    "en la distribuidora alguien arma la hoja del reparto todas las noches a mano",
    "para la planilla de la quincena copio las horas de tres hojas distintas",
    "no quiero contratar a otra persona solo pa pasar datos",
    "renombrar y archivar los pdf que llegan al correo me quita la mañana",
    "¿hay algo para que la compu haga sola lo que hoy hacemos a mano?",
    "el mismo correo de bienvenida lo escribo para cada cliente nuevo",
    "¿se puede hacer que cuando llegue un pedido por correo se anote solo?",
    "pasar datos de una hoja a otra me tiene loco",
    "copio lo mismo en el excel, en el correo y en el whatsapp del jefe",
    "tareas repetidas en la ofisina que nadie quiere hacer",
    "copiar y pegar",
    "tareas repetidas",
  ],
  T05: [
    "mensajes sin contestar",
    "me escriben a las 11 de la noche preguntando si hay",
    "contesto lo mismo cincuenta veces al día",
    "no doy abasto con los mensajes de whatsapp",
    "pierdo ventas porque contesto tarde",
    "¿hay algo que conteste el whatsapp cuando estoy cerrado?",
    "todos preguntan a cuánto, dónde quedan y a qué hora abren",
    "un robot q conteste los mensajes del negocio",
    "la muchacha de la tienda se pasa el dia pegada al celular contestando lo mismo",
    "en la ferreteria me preguntan por whatsapp si hay tal tornillo y no tengo tiempo",
    "los domingos se me acumulan los mensajes y el lunes ya compraron en otro lado",
    "quiero que los clientes tengan respuesta aunque yo este durmiendo",
    "algo que conteste con mis precios y no se invente nada",
    "que conteste lo facil y me pase a mi lo complicado",
    "la recepcion del gimnasio no da con tantas preguntas de precios y horarios",
    "la gente escribe \"info\" y hay que mandarle todo cada vez",
    "respuestas automaticas que sirvan de verdad, no el mensaje de ausencia",
    "en el consultorio preguntan todo el dia cuanto cuesta la consulta y si aceptan seguro",
    "me escriben buco y no alcanzo a contestar a todos",
    "whatsapp que conteste solo",
  ],
  T06: [
    "proformas rapidas",
    "cotizar desde el celular en la visita al cliente",
    "hacer una proforma en word me toma una hora",
    "los vendedores cotizan con precios viejos",
    "cotizamos cosas que no hay en bodega",
    "cada vendedor manda la cotisacion con un formato distinto",
    "los vendedores dan descuentos sin preguntarme",
    "no encuentro la cotizacion que le mande al cliente el mes pasado",
    "calcular el itbms renglon por renglon a mano",
    "los contratistas me piden cotizacion de una lista larga y tardo un dia en mandarla",
    "me equivoque sumando una cotizacion y perdi plata",
    "en la ferreteria las cotizaciones se hacen en excel y siempre sale un error",
    "quiero aprobar los descuentos grandes antes de que salga la cotizacion",
    "el cliente pide precio de 40 productos y armarlo es un parto",
    "a cuanto le cotice a este cliente la otra vez?",
    "cotizacion con mi logo y ruc que se vea profesional",
    "mi vendedor cotizo 50 sacos de cemento y solo teniamos 10",
    "cotizaciones con mi logo",
  ],
  T07: [
    "adios impresora fiscal",
    "la DGI me obliga a facturar electronico?",
    "escribo cada factura dos veces, en mi sistema y en el portal del PAC",
    "que es un PAC y cual me conviene",
    "la impresora fiscal ya no me sirve, y ahora que hago",
    "mi contador dice que tengo que pasarme a factura electrónica",
    "facturar electronico desde el sistema que ya tengo",
    "que la factura le llegue al cliente por whatsapp o correo sin imprimirla",
    "como hago una nota de credito si el cliente devuelve algo",
    "me da miedo una multa de la DGI por no facturar bien",
    "el facturador gratuito de la DGI ya no me alcanza",
    "mis clientes empresas me piden factura electronica y no tengo",
    "cada venta la tengo que volver a teclear pa facturar",
    "hago 300 facturas al mes y no doy con el portal",
    "el PAC que tengo no se conecta con mi programa de ventas",
    "q nesesito pa facturar electronicamente en panama",
    "pasarme de la factura fiscal a la electronica sin cambiar de sistema",
    "cuanto cuesta conectar mi sistema con la facturacion de la dgi",
    "facturar sin impresora fiscal",
  ],
  T08: [
    "como van las ventas hoy",
    "graficas de mis ventas",
    "no se cuanto vendi esta semana hasta que me dice el contador",
    "¿hay algo para ver las ventas de mis dos locales desde el celular?",
    "cual vendedor esta vendiendo mas",
    "que productos se venden mas y cuales no se mueven",
    "vendí más o menos que el mes pasado?",
    "ver las ventas del dia sin llamar a la cajera",
    "estoy de viaje y no se como va la panaderia",
    "tengo los datos en el sistema pero no les entiendo nada",
    "un resumen de ventas que me llegue al correo los lunes",
    "comparar las ventas de esta quincena con la anterior",
    "el reporte del sistema es una lista larguisima que nadie lee",
    "me entero tarde de que un local bajo las ventas",
    "cuanto vendio cada sucursal ayer",
    "manejo tres farmacias y cada una me manda su cierre en una foto x whatsapp",
    "xq bajaron las ventas este mes? no tengo como verlo",
    "los numeros del negocio en una sola pantalla",
    "comparar ventas por mes",
  ],
  T09: [
    "capturas de yappy falsas",
    "cobrar con tarjeta sin maquinita",
    "quiero mandar un enlace para que me paguen",
    "el cliente dice que ya pagó y no me aparece",
    "clientes de afuera quieren pagar con tarjeta y no tengo como",
    "boton de pago pa mi pagina",
    "cobrar sin tener que dar mi numero de cuenta a todo el mundo",
    "stripe no funciona en panama, que uso?",
    "abrir yappy comercial pa mi negocio y conectarlo",
    "un cliente me jugo vivo con una captura editada",
    "que el pago se confirme solo sin revisar el banco",
    "vendo x whatsapp y no tengo como cobrar con tarjeta",
    "vendo tours en bocas y los gringos quieren pagar con tarjeta antes de venir",
    "me encargan tortas y despues no las recogen ni las pagan",
    "cuanto cobra yappy por cada pago",
    "me deben plata de trabajos y quiero mandarles algo pa que paguen ahi mismo",
    "soy fotografo y quiero que me paguen la sesion con tarjeta antes",
    "cobrar con un link",
  ],
  T10: [
    "internet de respaldo",
    "el wifi no llega al fondo del local",
    "se cae el internet y no puedo cobrar con tarjeta",
    "los clientes estan en la misma red que la caja",
    "en la terraza no hay señal de wifi",
    "el internet se pone lento cuando se llena el restaurante",
    "en el segundo piso del hostal no agarra el wifi",
    "todo el mundo tiene la clave del wifi de la caja",
    "las camaras se desconectan a cada rato porque el wifi no llega",
    "el modem que me dio la compañia no alcanza pa todo el local",
    "compre repetidores y el wifi sigue igual de malo",
    "¿como separo el wifi de los clientes del de la oficina?",
    "en la bodega de atras no llega el internet",
    "cuando se va el internet se para la caja y se arma la fila",
    "el wifi del gimnasio se cae cuando hay mucha gente",
    "en el colegio el wifi no llega a los salones",
    "la maquinita de las tarjetas se queda sin conexion",
    "cables x todos lados y el internet igual no sirve",
    "wifi no llega",
    "se cae el internet",
  ],
  T11: [
    "ver mi local desde el cel",
    "me robaron y las cámaras no estaban grabando",
    "mi tio tiene un chino y quiere ver las camaras desde el telefono",
    "cuanto cuesta poner camaras en un minisuper",
    "quiero vigilar la bodega desde la casa",
    "el dvr viejo no graba y no se ve en el telefono",
    "las camaras que tengo solo se ven en el monitor de la oficina",
    "se metieron de noche y no tengo como ver quien fue",
    "ver en vivo la tienda cuando estoy en otro lado",
    "el encargado quiere ver las camaras pero no le quiero dar mi clave",
    "buscar la grabacion de ayer a las 3 de la tarde",
    "cuantos dias guarda la grabacion?",
    "le rayaron el carro a un cliente donde parquean y no hay grabacion",
    "camaras para un taller con porton a la calle",
    "un cliente dice que se cayo en el local y no tengo como probar nada",
    "que mis dos socios puedan ver las camaras desde su telefono",
    "quiero revisar desde la playa que todo este bien en la farmacia",
    "sabes de alguien que instale camaras?",
    "camaras en el celular",
    "camaras pa mi negocio",
  ],
  T12: [
    "correo de empresa",
    "ventas@minegocio como se hace",
    "mis empleados cotizan desde su gmail personal",
    "da mala impresión escribirle a los clientes desde un hotmail",
    "cuando se va un empleado se lleva los correos de los clientes",
    "quiero un correo con el nombre de mi empresa",
    "los clientes creen que es estafa porque escribo desde gmail",
    "el correo de la empresa en el celular de cada vendedor",
    "el nombre de mi negocio .com.pa esta libre?",
    "me pidieron un correo corporativo pa poder ser proveedor",
    "tengo el .com pero no se como hacer los correos",
    "cada quien usa un correo distinto y los clientes no saben a cual escribir",
    "quiero administracion@ y ventas@ separados",
    "me da cosa poner mi gmail personal en las tarjetas de presentacion",
    "los correos de la empresa salen de yahoo y se ve poco serio",
    "nesesito correos pa 5 personas con el nombre de la empresa",
    "comprar el nombre de mi negocio para usarlo en el correo",
    "correo que no sea gmail",
  ],
  T13: [
    "no salgo en google maps",
    "como respondo las reseñas",
    "en google sale mi horario viejo",
    "me dejaron una reseña mala en google y no se que hacer",
    "la ubicacion de mi negocio en google esta mal y los clientes se pierden",
    "cuando buscan barberia cerca de mi no aparezco",
    "como hago pa que mis clientes me dejen estrellas en google",
    "alguien creo el perfil de mi negocio y no tengo acceso",
    "google dice que estoy cerrado y estoy abierto",
    "tengo 3 reseñas y la competencia tiene 200",
    "salir en el mapa cuando buscan ferreteria en la chorrera",
    "en google sale el telefono viejo del taller",
    "puedo borrar una reseña falsa?",
    "no tengo local, igual puedo salir en google maps?",
    "las fotos de mi restaurante en google las subieron clientes y se ven feas",
    "poner el horario de los feriados en google",
    "los turistas buscan hostales en el mapa y salen todos menos yo",
    "un cliente me puso una estrella por gusto",
    "reseñas en google",
    "salir en google maps",
  ],
  T14: [
    "inventario en libreta",
    "le pido al proveedor a ojo",
    "me entero que se acabo algo cuando el cliente lo pide",
    "no se cuanto tengo en la bodega",
    "le compro dos veces lo mismo al proveedor porque no sabia que habia",
    "¿hay algo que me avise cuando se este acabando un producto?",
    "tengo dos bodegas y no se que hay en cada una",
    "hacer los pedidos a los proveedores me toma toda la tarde",
    "sacan cosas de la bodega pa la tienda y nadie lo anota",
    "se acaba el alimento de perro que mas se vende y no me doy cuenta",
    "en la farmacia se nos acaban las medicinas que más piden",
    "pasar el codigo de barras al sacar algo de la bodega",
    "cuanto me queda de cada repuesto?",
    "registrar que material sale para cada obra",
    "ordenes de compra en papel que se pierden",
    "me quedo sin mercansia los fines de semana",
    "en la abarroteria siempre se acaba el arroz antes de que llegue el pedido",
    "cuanto entra y cuanto sale de cada producto, no tengo idea",
    "productos agotados sin aviso",
  ],
  T15: [
    "a quien llamo hoy",
    "mi lista de clientes es un desorden",
    "se me olvida llamar a los clientes que cotizaron",
    "los vendedores anotan los clientes en una libreta",
    "no se en que va cada venta",
    "cuando un vendedor se va se lleva la lista de clientes",
    "clientes que preguntan y nadie les da seguimiento",
    "tengo 30 cotizaciones mandadas y no se cuales siguen vivas",
    "perdi una venta grande porque nadie volvio a llamar",
    "cuantas ventas tiene abiertas cada vendedor",
    "los contactos de los clientes estan en el celular de cada vendedor",
    "no se que le vendimos a este cliente el año pasado",
    "se me olvida llamar a la gente pa renovar la poliza",
    "en la academia la gente pregunta por los cursos y nadie les vuelve a escribir",
    "cada vendedor maneja sus clientes en un excel diferente",
    "los clientes se enfrian porque tardamos en volver a escribirles",
    "gente que vino a preguntar al gimnasio y no se inscribio, nadie la llama",
    "quien atendio a este cliente la ultima vez?",
    "clientes sin seguimiento",
  ],
  T16: [
    "clientes preguntando en que va lo suyo",
    "los clientes llaman todo el dia a preguntar si ya esta su pedido",
    "me piden la factura otra vez porque la perdieron",
    "quiero que mis clientes vean en que va su trabajo sin llamarme",
    "en la imprenta nos preguntan cada hora si ya estan los volantes",
    "los clientes de la agencia de aduanas quieren saber en que va su carga",
    "los clientes de la oficina contable me piden copia de sus declaraciones a cada rato",
    "que los pacientes bajen sus resultados del laboratorio sin venir",
    "que cada cliente entre con su usuario y vea solo lo suyo",
    "los clientes me escriben pa pedir sus documentos y los busco en mil carpetas",
    "el cliente no sabe si su tramite ya esta listo",
    "¿hay algo para que mis clientes vean sus facturas y lo que me deben?",
    "mis clientes mayoristas quieren ver el estado de sus pedidos solos",
    "los clientes del bufete quieren ver los papeles de su caso sin venir",
    "el dueño de la remodelación quiere ver en qué va la obra y los papeles",
    "las empresas a las que les doy mantenimiento quieren ver sus reportes de cada visita",
    "en el estudio de diseño los clientes quieren ver sus pruebas y avances sin escribirnos",
    "clientes preguntando \"¿ya está?\"",
  ],
  T17: [
    "firmas a distancia",
    "imprimir, firmar, escanear y mandar, que fastidio",
    "el cliente vive en david y tiene que venir a firmar el contrato",
    "firmar contratos desde el celular",
    "los inquilinos tienen que venir a la oficina a firmar el contrato de alquiler",
    "el cliente se hace el vivo y dice que nunca aceptó las condiciones",
    "que el cliente firme el contrato antes de llevarse el equipo",
    "los papeles firmados se pierden en el archivo",
    "mandar un contrato por whatsapp y que lo firmen ahi mismo",
    "con el tranque nadie quiere venir hasta la oficina solo a firmar",
    "los empleados nuevos firman el contrato en papel y despues no aparece",
    "que los papas firmen el permiso de la gira desde el celular",
    "la firma por el celular vale legalmente en panama?",
    "saber quien firmo y a que hora",
    "clientes en el extranjero que tienen que firmar un contrato conmigo",
    "hoja de recibido conforme firmada por el cliente al entregar",
    "los clientes tardan semanas en devolverme el contrato firmado",
    "cuanto cuesta que mis clientes firmen en linea",
    "firmar sin imprimir",
  ],
  T18: [
    "contraseñas en una libreta",
    "clave123 en todas las cuentas",
    "si se daña el disco duro pierdo todo",
    "a un amigo le bloquearon todo con un virus y no quiero que me pase",
    "si se roban la compu pierdo toda la contabilidad",
    "cuando se va un empleado no se a que cuentas tiene acceso",
    "todos en la oficina usan la misma clave",
    "la clave de la DGI y la CSS la sabe todo el mundo",
    "copio todo a una usb cuando me acuerdo",
    "donde guardo una copia de los archivos fuera de la oficina?",
    "si se inunda la oficina pierdo los archivos de 10 años",
    "me hackearon el correo y les escribieron a mis clientes",
    "los archivos de la empresa solo estan en la compu de la contadora",
    "nunca he probado si la copia de seguridad sirve",
    "el exempleado todavia entra a las cuentas de la empresa",
    "me da miedo que me secuestren los archivos como a la otra empresa",
    "el disco externo esta en la misma oficina que la computadora",
    "perder todos los archivos",
  ],
  T19: [
    "la impresora no imprime",
    "tecnico por whatsapp",
    "la computadora esta lentisima",
    "no tengo a nadie de sistemas en la oficina",
    "cada vez que algo falla llamo a mi sobrino",
    "el correo no sale y tengo que mandar algo urgente",
    "necesito un tecnico que venga a la oficina",
    "la compu no prende",
    "se actualizo windows y ahora nada funciona",
    "quien me instala los programas en las compus nuevas",
    "el pelao que nos ayudaba con las computadoras se fue",
    "la impresora compartida dice desconectada para todo el mundo",
    "no se cuantas licencias de office tenemos ni a nombre de quien",
    "pago visitas carisimas cada vez que se traba algo",
    "conoces a alguien que sepa de compus pa una oficina?",
    "se puso la pantalla azul y no se que hacer",
    "el escaner no manda a la computadora",
    "esta vaina se traba cada 5 minutos y tengo que entregar hoy",
    "alguien que me arregle la compu sin tener que llevarla",
  ],
  T20: [
    "los sistemas no se hablan",
    "cuadrar yappy con pedidos",
    "la tienda en linea y el local tienen inventarios distintos",
    "las ventas de la sucursal de david no llegan al sistema de la principal",
    "el programa de la planilla y el de contabilidad no se pasan nada",
    "cada noche cuadro las existencias de la web y de la tienda",
    "vendi por la web algo que ya se habia vendido en el local",
    "los pagos del banco los paso a mano a quickbooks",
    "entra un pago y no se de que pedido es",
    "tengo shopify y un pos y no se conectan",
    "que los pagos de yappy entren solos al sistema contable",
    "la contadora vuelve a escribir todo lo que ya esta en el sistema de ventas",
    "uso cuatro programas y tengo que meter la misma venta en todos",
    "los pedidos de la tienda online no pasan solos al sistema de la oficina",
    "las cifras del banco y del sistema nunca cuadran",
    "que el estado de cuenta del banco se cruce solo con las facturas",
    "cada sistema dice una cosa distinta",
    "conectar mi programa con el banco, se puede?",
    "sistemas que no cuadran",
  ],
  T21: [
    "digitar facturas todo el dia",
    "fotos de facturas a excel",
    "paso las facturas de los proveedores a excel a mano",
    "tomarle foto a la factura y que se llene solo",
    "tengo una caja de facturas que pasar cada mes",
    "los clientes mandan ordenes de compra en pdf y alguien las transcribe",
    "sacar el ruc, el total y el itbms de cada factura sin teclear",
    "formularios llenados a mano que alguien tiene que teclear",
    "las facturas llegan x whatsapp, x correo y en papel y todo hay que pasarlo",
    "la administradora se pasa el sabado pasando facturas",
    "recibos de gastos de los vendedores en fotos arrugadas",
    "en la cooperativa las solicitudes llegan escaneadas y hay que copiar los datos a mano",
    "en el taller nadie pasa las facturas de repuestos al excel porque da pereza",
    "me equivoco copiando los montos de las facturas",
    "la letra de los recibos a mano, eso se puede leer solo?",
    "pa declarar el itbms sumo a mano cientos de facturas de compra",
    "que la compu lea los pdf y saque los datos",
    "las notas de entrega de los proveedores las pasamos a mano al sistema",
    "teclear facturas de proveedores",
    "recibos a excel",
  ],
  T22: [
    "aprender a usar chatgpt",
    "taller de IA pa mi oficina",
    "mi equipo no sabe usar chatgpt",
    "quiero que mis empleados aprendan a usar la inteligencia artificial",
    "me da miedo que pongan datos de clientes en chatgpt",
    "curso de chatgpt para empresas en panama",
    "como uso la IA para resumir contratos largos",
    "los pelaos de la oficina usan chatgpt pero les sale todo raro",
    "en el despacho queremos usar la IA sin meter la pata con los expedientes",
    "que se puede subir y que no a chatgpt",
    "todo el mundo habla de la IA y en mi negocio nadie la usa",
    "enseñarle a la secretaria a usar chatgpt pa las cartas",
    "mi gente tarda una hora en cada correo y no sabe usar chatgpt",
    "mis vendedores copian lo que dice chatgpt sin revisar",
    "plantillas de chatgpt pa las tareas de la oficina",
    "clase practica de IA con ejemplos de mi negocio",
    "pago chatgpt plus y nadie en la oficina lo usa",
    "chatgpt pa empleados",
  ],
  V01: [
    "en el autolavado la gente espera sin saber cuanto le falta",
    "avisarle al cliente por whatsapp que su carro ya esta listo",
    "cuantos carros tengo adelante",
    "los sabados el lavado se llena y la gente se va",
    "llamo uno por uno pa decir que el carro esta listo",
    "un juega vivo se metio en la fila del lavado",
    "que el cliente saque turno desde el celular pa lavar el carro",
    "que se vaya a la panaderia y le aviso cuando este el carro",
    "en el taller me llaman a cada rato a preguntar si ya esta el carro",
    "turno pa lavar la moto",
    "un qr en la entrada del autolavado pa sacar turno",
    "los carros esperando se parquean en la calle y tapan",
    "cuanto cuesta un sistema de turnos pa autolavado",
    "gritar el nombre del cliente cuando sale su carro",
    "detailing: el cliente no sabe a que hora volver por su carro",
    "el carro listo y el dueño ni enterado",
    "fila en el lavado",
    "turno pa el lavado",
  ],
  V02: [
    "el cliente dice que el golpe se lo hicimos nosotros",
    "presupuestos aprobados de palabra y despues no quieren pagar",
    "no me acuerdo que le hicimos a ese carro la vez pasada",
    "tomar fotos del carro cuando entra al taller",
    "el dueño dice que nunca autorizo cambiar las pastillas",
    "las ordenes del taller en papel se pierden",
    "mandarle el presupuesto al cliente pa que lo apruebe por whatsapp",
    "chapisteria: siempre hay pleito por lo que se acordo cobrar",
    "cuanto cuesta un programa pa el taller mecanico",
    "buscar por placa que se le hizo al carro",
    "el cliente reclama que le cobramos mas de lo que le dijimos",
    "la empresa quiere el historial de reparaciones de cada pick-up",
    "hoja de recepcion del carro con fotos",
    "taller de motos sin registro de los trabajos",
    "en que va la reparacion de cada carro",
    "rayones que nadie anoto",
    "el mecanico no sabe que aprobo el cliente",
    "historial del carro",
  ],
  V03: [
    "los clientes reservan y no llegan a la barberia",
    "se me cruzan las citas de los barberos",
    "cobrar un adelanto pa apartar la cita",
    "llevo la agenda del salon en una libreta",
    "me escriben a toda hora pa sacar sita de corte",
    "que el cliente escoja su barbero",
    "recordarle a las clientas la cita de uñas un dia antes",
    "dos clientas a la misma hora con la misma estilista",
    "cancelan a ultima hora y se pierde el espacio",
    "spa: cobrar deposito por yappy antes del masaje",
    "cada barbero quiere ver su agenda en el celular",
    "un tinte de 3 horas se me monta con otras citas",
    "cuanto cuesta algo pa que me agenden los cortes por internet",
    "los que llegan sin cita y los que tienen cita se pelean el turno",
    "citas barberia",
    "manicurista con clientas que cancelan el mismo dia",
    "deposito pa la cita",
  ],
};
