// Una página por tipo de negocio (/soluciones/<slug>/). Cada problema se responde con servicios del catálogo.
// foto: hueco de assets/fotos (lo llena herramientas con créditos en datos/creditos-fotos.mjs).
// demo: clave de datos/demos.mjs que se muestra destacada en la página.

export const SOLUCIONES = [
  {
    sector: 'restaurantes',
    slug: 'restaurantes',
    h1: 'Menos espera en las mesas y comandas que no se pierden',
    singular: 'restaurante',
    icono: 'fork-knife',
    foto: 'sector-restaurantes',
    titulo: 'Tecnología para restaurantes y cafés',
    bajada: 'Que el cliente pida y pague desde la mesa, que la cocina vea cada comanda a tiempo y que tú veas el salón entero desde la caja.',
    demo: 'mesa',
    problemas: [
      { problema: 'Los clientes esperan para pedir, para otra ronda y para pagar.', respuesta: 'Un QR en cada mesa: piden, llaman al mesero y pagan desde su teléfono, con la propina que ellos eligen.', servicios: ['R02', 'R01'] },
      { problema: 'Las comandas en papel se pierden o se leen mal.', respuesta: 'Cada pedido en la tableta o la pantalla de la cocina, por estación y con el tiempo que lleva esperando.', servicios: ['R05'] },
      { problema: 'No sabes qué mesa lleva cuánto ni cuál pidió la cuenta.', respuesta: 'El plano del salón en la caja con el estado de cada mesa y su cuenta abierta, lista para cobrar y facturar.', servicios: ['R04', 'R11', 'T07'] },
      { problema: 'Pagas comisión por cada pedido a domicilio.', respuesta: 'Tu propia app o página de pedidos, para tu restaurante, tus sucursales o un grupo de restaurantes, con tus motorizados y pago con Yappy o tarjeta.', servicios: ['R12', 'R07', 'T09'] },
      { problema: 'Pasas el día copiando pedidos de WhatsApp a la cocina.', respuesta: 'Un asistente toma el pedido por WhatsApp y la comanda sale sola en la cocina.', servicios: ['R13', 'R05'] },
    ],
  },
  {
    sector: 'comercio',
    slug: 'tiendas',
    h1: 'Que la caja cuadre, el inventario también, y que los clientes vuelvan',
    singular: 'tienda',
    icono: 'storefront',
    foto: 'sector-comercio',
    titulo: 'Tecnología para tiendas, minisúper y comercios',
    bajada: 'Vender también por internet y por WhatsApp, cerrar la caja por turno y contar la mercancía sin pasar la noche anotando.',
    demo: null,
    problemas: [
      { problema: 'La caja no cuadra al final del día.', respuesta: 'Un punto de venta con cierre de caja por turno y por cajero, y el inventario que se descuenta solo con cada venta.', servicios: ['R11', 'T14'] },
      { problema: 'Contar el inventario toma días y nunca cuadra.', respuesta: 'Un sistema de inventario con entradas, salidas y existencias al día, y un aviso cuando algo se está acabando.', servicios: ['T14'] },
      { problema: 'Vendes por WhatsApp a mano, uno por uno.', respuesta: 'Catálogo y pedidos por WhatsApp, o tu propia tienda en línea con Yappy y tarjeta.', servicios: ['C11', 'C06', 'T09'] },
      { problema: 'Los clientes compran una vez y no vuelven.', respuesta: 'Sellos o puntos en el teléfono del cliente, sin tarjeta de cartón, y un mensaje cuando lleva tiempo sin volver.', servicios: ['C08'] },
    ],
  },
  {
    sector: 'salud',
    slug: 'clinicas',
    h1: 'Pacientes que llegan a su cita y una recepción que no vive pegada al teléfono',
    singular: 'clínica',
    icono: 'stethoscope',
    foto: 'sector-salud',
    titulo: 'Tecnología para clínicas y consultorios',
    bajada: 'Recordatorios por WhatsApp que el paciente confirma con un toque, una agenda sin citas encimadas y la lista de a quién llamar.',
    demo: 'reservas',
    problemas: [
      { problema: 'Los pacientes no llegan y el hueco se pierde.', respuesta: 'Recordatorio por WhatsApp 2 o 1 día antes, con botón para confirmar, y reintentos hasta tener respuesta.', servicios: ['S01'] },
      { problema: 'La recepción pasa el día al teléfono agendando.', respuesta: 'Una página donde el paciente pide su cita solo, con los horarios libres de cada profesional.', servicios: ['S01', 'T05'] },
      { problema: 'La sala de espera es un desorden.', respuesta: 'Pantalla de turnos que llama al siguiente paciente por su número.', servicios: ['S02'] },
      { problema: 'El expediente vive en papel o en hojas sueltas.', respuesta: 'Expediente digital del paciente, con permisos por persona y el consentimiento que pide la Ley 81.', servicios: ['S05'] },
      { problema: 'Pacientes que viven lejos o solo necesitan un control.', respuesta: 'Videoconsulta con cobro previo desde la misma agenda.', servicios: ['S04'] },
    ],
  },
  {
    sector: 'hospedaje',
    slug: 'hospedaje',
    h1: 'Reservas directas sin comisión, y un aviso antes de vender dos veces la misma noche',
    singular: 'alojamiento',
    icono: 'bed',
    foto: 'sector-hospedaje',
    titulo: 'Tecnología para cabañas, hostales y hoteles pequeños',
    bajada: 'Tu propia página de reservas con Yappy y tarjeta, un vigilante que avisa cuando Booking o Airbnb dejan de sincronizar, y el registro del huésped en línea antes de que llegue.',
    demo: 'reservas',
    problemas: [
      { problema: 'Pagas comisión por reservas que podrían ser directas.', respuesta: 'Motor de reservas en tu página, con depósito en línea y varias unidades en una reserva.', servicios: ['H01', 'T09'] },
      { problema: 'Una doble reserva porque un calendario dejó de sincronizar.', respuesta: 'Calendario sincronizado con los canales y un vigilante que avisa y cierra la venta si uno se cae.', servicios: ['H02'] },
      { problema: 'El registro del huésped se llena en papel cuando llega.', respuesta: 'Registro en línea: el huésped llena sus datos, sube la foto del documento y firma las normas de la casa antes de llegar.', servicios: ['H04'] },
    ],
  },
  {
    sector: 'inmuebles',
    slug: 'bienes-raices',
    h1: 'Tus propiedades en tu propio sitio y ningún interesado sin respuesta',
    singular: 'inmobiliaria',
    icono: 'buildings',
    foto: 'sector-inmuebles',
    titulo: 'Tecnología para agentes de bienes raíces',
    bajada: 'Tu propio sitio de propiedades, un agente de WhatsApp que contesta a las 11 de la noche y el seguimiento de cada interesado hasta la firma.',
    demo: null,
    problemas: [
      { problema: 'Visitas con gente que no iba en serio.', respuesta: 'Un agente de WhatsApp que contesta, pregunta presupuesto y fecha, y agenda solo a los interesados.', servicios: ['B04'] },
      { problema: 'Tus propiedades dependen de portales de terceros.', respuesta: 'Tu propio sitio de propiedades, con la ficha de cada una, filtros por zona y precio, y contacto directo a WhatsApp.', servicios: ['B05'] },
      { problema: 'Los interesados se enfrían porque nadie les da seguimiento.', respuesta: 'Cada interesado con su historial, en qué etapa va y qué toca hacer hoy, con un recordatorio para no dejarlo enfriar.', servicios: ['T15'] },
      { problema: 'Firmar un contrato obliga a cuadrar una cita.', respuesta: 'Contratos y formularios que el cliente firma desde el teléfono, con registro de quién firmó y cuándo.', servicios: ['T17'] },
    ],
  },
  {
    sector: 'educacion',
    slug: 'escuelas',
    h1: 'Mensualidades que se pagan a tiempo y circulares que llegan a la casa',
    singular: 'escuela',
    icono: 'graduation-cap',
    foto: 'sector-educacion',
    titulo: 'Tecnología para escuelas y academias',
    bajada: 'Matrícula y mensualidades en línea, el estado de cuenta de cada estudiante y los avisos a los padres por WhatsApp.',
    demo: null,
    problemas: [
      { problema: 'Cobrar mensualidades es perseguir pagos.', respuesta: 'Matrícula y cobro en línea con Yappy o tarjeta, recordatorio de pago y estado de cuenta por estudiante.', servicios: ['E01'] },
      { problema: 'Las circulares no llegan a la casa.', respuesta: 'Avisos y recordatorios a los padres por WhatsApp.', servicios: ['E03'] },
    ],
  },
  {
    sector: 'servicios',
    slug: 'talleres-y-salones',
    h1: 'Citas que no se cruzan y clientes que saben cuánto les falta',
    singular: 'taller o salón',
    icono: 'car',
    foto: 'sector-servicios',
    titulo: 'Tecnología para talleres, autolavados y salones',
    bajada: 'Turnos en línea, un aviso por WhatsApp cuando el carro o el servicio está listo, y presupuestos aprobados por escrito.',
    demo: 'reservas',
    problemas: [
      { problema: 'El cliente espera sin saber cuánto le falta.', respuesta: 'Turnos en línea con su lugar en la fila y aviso por WhatsApp cuando está listo.', servicios: ['V01'] },
      { problema: 'Presupuestos aprobados de palabra que luego se discuten.', respuesta: 'Órdenes de trabajo con fotos del vehículo y aprobación del cliente por WhatsApp.', servicios: ['V02'] },
      { problema: 'Citas que se cruzan en la barbería o el salón.', respuesta: 'Agenda por profesional con recordatorio y depósito en línea.', servicios: ['V03'] },
    ],
  },
  {
    sector: 'todos',
    slug: 'cualquier-negocio',
    h1: 'Que te encuentren en Google y que el trabajo repetido lo haga el sistema',
    singular: 'negocio',
    icono: 'briefcase',
    foto: 'sector-todos',
    titulo: 'Software y automatización para cualquier negocio',
    bajada: 'Página web, apps, sistemas a medida y automatizaciones para lo que hoy se hace en Excel, en papel o copiando y pegando.',
    demo: null,
    problemas: [
      { problema: 'El negocio no aparece cuando lo buscan.', respuesta: 'Página web, perfil de Google con tu ubicación y reseñas, y correo con tu dominio.', servicios: ['T01', 'T13', 'T12'] },
      { problema: 'Todo vive en Excel y nadie sabe cuál es la versión buena.', respuesta: 'Software a medida para cómo trabaja tu negocio: inventario, clientes, cotizaciones.', servicios: ['T02', 'T14', 'T15', 'T06'] },
      { problema: 'Alguien copia y pega datos todo el día.', respuesta: 'Automatizaciones e integraciones entre tus sistemas, y lectura de facturas con IA.', servicios: ['T04', 'T20', 'T21'] },
      { problema: 'Las mismas preguntas por WhatsApp a toda hora.', respuesta: 'Un asistente con IA que contesta con tu información y te pasa lo que no sabe.', servicios: ['T05'] },
      { problema: 'Se cae la computadora y se pierde todo.', respuesta: 'Respaldo automático en la nube y contraseñas en orden, para que una computadora dañada no te cueste el trabajo.', servicios: ['T18'] },
    ],
  },
];
