// Una página por tipo de negocio (/soluciones/<slug>/). Cada problema se responde con servicios del catálogo.
// foto: hueco de assets/fotos (lo llena herramientas con créditos en datos/creditos-fotos.mjs).
// demo: clave de datos/demos.mjs que se muestra destacada en la página.

export const SOLUCIONES = [
  {
    sector: 'restaurantes',
    slug: 'restaurantes',
    singular: 'restaurante',
    icono: 'fork-knife',
    foto: 'sector-restaurantes',
    titulo: 'Tecnología para restaurantes y cafés',
    bajada: 'Que el cliente pida y pague desde la mesa, que la cocina vea cada comanda a tiempo y que tú veas el salón entero desde la caja.',
    demo: 'mesa',
    problemas: [
      { problema: 'Los clientes esperan para pedir, para otra ronda y para pagar.', respuesta: 'Un QR o una etiqueta NFC en cada mesa: piden, llaman al mesero y pagan desde su teléfono, con la propina que ellos eligen.', servicios: ['R01', 'R02', 'R03'] },
      { problema: 'Las comandas en papel se pierden o se leen mal.', respuesta: 'Pantalla en la cocina con cada pedido por estación y el tiempo que lleva esperando.', servicios: ['R05'] },
      { problema: 'No sabes qué mesa lleva cuánto ni cuál pidió la cuenta.', respuesta: 'El plano del salón en la caja con el estado de cada mesa y su cuenta abierta, lista para cobrar y facturar.', servicios: ['R04', 'R11', 'T07'] },
      { problema: 'Pagas comisión por cada pedido a domicilio.', respuesta: 'Tu propia app o página de pedidos, para tu restaurante, tus sucursales o un grupo de restaurantes, con tus motorizados y pago con Yappy o tarjeta.', servicios: ['R12', 'R07', 'T09'] },
      { problema: 'Pasas el día copiando pedidos de WhatsApp a la cocina.', respuesta: 'Un asistente toma el pedido por WhatsApp y la comanda sale sola en la cocina.', servicios: ['R13', 'R05'] },
      { problema: 'Se daña la mercancía cuando falla una nevera de noche.', respuesta: 'Sensores de temperatura que te avisan al WhatsApp antes de perderla.', servicios: ['R10'] },
    ],
  },
  {
    sector: 'comercio',
    slug: 'tiendas',
    singular: 'tienda',
    icono: 'storefront',
    foto: 'sector-comercio',
    titulo: 'Tecnología para tiendas y comercios',
    bajada: 'Vender también por internet, saber cuánta gente entra y cuánta compra, y contar la mercancía sin pasar la noche anotando.',
    demo: 'camara',
    problemas: [
      { problema: 'No sabes cuántas personas entran ni cuántas terminan comprando.', respuesta: 'Un contador en la puerta que, junto con tus ventas, te da la tasa de conversión por hora y por día.', servicios: ['C01', 'C02'] },
      { problema: 'Se forman filas en caja y la gente se va.', respuesta: 'La cámara avisa al encargado cuando la fila pasa de cierto número.', servicios: ['C03'] },
      { problema: 'Contar el inventario toma días y nunca cuadra.', respuesta: 'Inventario por escaneo con RFID o con la cámara del teléfono, comparado contra tu sistema.', servicios: ['C04', 'T14'] },
      { problema: 'Vendes por WhatsApp a mano, uno por uno.', respuesta: 'Catálogo y pedidos por WhatsApp, o tu propia tienda en línea con Yappy y tarjeta.', servicios: ['C11', 'C06', 'T09'] },
      { problema: 'Hay pérdidas y no sabes dónde.', respuesta: 'Cámaras que marcan los momentos que vale la pena revisar, sin ver horas de video.', servicios: ['C05', 'T11'] },
    ],
  },
  {
    sector: 'salud',
    slug: 'clinicas',
    singular: 'clínica',
    icono: 'stethoscope',
    foto: 'sector-salud',
    titulo: 'Tecnología para clínicas y consultorios',
    bajada: 'Menos pacientes que no llegan, una agenda sin citas encimadas y la recepción libre de llamar uno por uno.',
    demo: 'reservas',
    problemas: [
      { problema: 'Los pacientes no llegan y el hueco se pierde.', respuesta: 'Recordatorio por WhatsApp 2 o 1 día antes, con botón para confirmar, y reintentos hasta tener respuesta.', servicios: ['S01'] },
      { problema: 'La recepción pasa el día al teléfono agendando.', respuesta: 'Una página donde el paciente pide su cita solo, con los horarios libres de cada profesional.', servicios: ['S01', 'T05'] },
      { problema: 'La sala de espera es un desorden.', respuesta: 'Pantalla de turnos que llama al siguiente paciente por su número.', servicios: ['S02'] },
      { problema: 'El expediente vive en papel o en hojas sueltas.', respuesta: 'Expediente digital del paciente, con permisos por persona y el consentimiento que pide la Ley 81.', servicios: ['S05'] },
      { problema: 'Pacientes que viven lejos o solo necesitan un control.', respuesta: 'Videoconsulta con cobro previo desde la misma agenda.', servicios: ['S04'] },
    ],
  },
  {
    sector: 'hospedaje',
    slug: 'hospedaje',
    singular: 'alojamiento',
    icono: 'bed',
    foto: 'sector-hospedaje',
    titulo: 'Tecnología para cabañas, hostales y hoteles pequeños',
    bajada: 'Vender en tu propia página sin comisión, sin dobles reservas con Booking o Airbnb, y con el huésped entrando solo con su código.',
    demo: 'reservas',
    problemas: [
      { problema: 'Pagas comisión por reservas que podrían ser directas.', respuesta: 'Motor de reservas en tu página, con depósito en línea y varias unidades en una reserva.', servicios: ['H01', 'T09'] },
      { problema: 'Una doble reserva porque un calendario dejó de sincronizar.', respuesta: 'Calendario sincronizado con los canales y un vigilante que avisa y cierra la venta si uno se cae.', servicios: ['H02'] },
      { problema: 'Esperar al huésped para entregar llaves.', respuesta: 'Cerraduras con un código por reserva y registro del huésped en línea antes de llegar.', servicios: ['H03', 'H04'] },
      { problema: 'El aire acondicionado prendido en una cabaña vacía.', respuesta: 'Luces, aire y consumo de cada unidad desde el teléfono.', servicios: ['H06', 'H05'] },
    ],
  },
  {
    sector: 'inmuebles',
    slug: 'bienes-raices',
    singular: 'inmobiliaria',
    icono: 'buildings',
    foto: 'sector-inmuebles',
    titulo: 'Tecnología para agentes de bienes raíces',
    bajada: 'Que el comprador recorra la propiedad desde su teléfono antes de visitarla, y que nadie se quede sin respuesta a las 11 de la noche.',
    demo: 'recorrido-360',
    problemas: [
      { problema: 'Las fotos no transmiten cómo es el espacio.', respuesta: 'Recorrido 360 de cada ambiente, o en 3D caminando como en un videojuego, para enlazar desde tu anuncio.', servicios: ['B01', 'B02'] },
      { problema: 'Visitas con gente que no iba en serio.', respuesta: 'Un agente de WhatsApp que contesta, pregunta presupuesto y fecha, y agenda solo a los interesados.', servicios: ['B04'] },
      { problema: 'Tus propiedades dependen de portales de terceros.', respuesta: 'Tu propio sitio de propiedades, con fichas, planos y recorridos.', servicios: ['B05', 'B03'] },
      { problema: 'Terrenos y proyectos difíciles de mostrar.', respuesta: 'Tomas aéreas con dron y mapa del terreno.', servicios: ['B06'] },
    ],
  },
  {
    sector: 'operacion',
    slug: 'industria-y-oficinas',
    singular: 'empresa',
    icono: 'factory',
    foto: 'sector-operacion',
    titulo: 'Tecnología para bodegas, plantas y oficinas',
    bajada: 'Saber qué pasa en la planta sin estar ahí: motores, tanques, consumo, quién entra y cuánto se produjo.',
    demo: 'sensores',
    problemas: [
      { problema: 'Un motor o una bomba se daña sin aviso y para todo.', respuesta: 'Sensores de vibración y temperatura que avisan antes de la falla.', servicios: ['I07', 'I01'] },
      { problema: 'Nadie sabe cuánto se produjo hasta el cierre.', respuesta: 'Contador de producción en línea y básculas conectadas al sistema.', servicios: ['I06', 'I08'] },
      { problema: 'Entra y sale gente sin registro.', respuesta: 'Control de acceso con QR o tarjeta, y lectura de placas en el portón.', servicios: ['I04', 'I03'] },
      { problema: 'Los camiones salen y no sabes dónde están.', respuesta: 'GPS por vehículo con historial de rutas.', servicios: ['I02'] },
      { problema: 'Accidentes por no usar el equipo de seguridad.', respuesta: 'Cámaras que avisan cuando alguien entra sin casco o chaleco.', servicios: ['I05'] },
    ],
  },
  {
    sector: 'educacion',
    slug: 'escuelas',
    singular: 'escuela',
    icono: 'graduation-cap',
    foto: 'sector-educacion',
    titulo: 'Tecnología para escuelas y academias',
    bajada: 'Matrícula y mensualidades en línea, asistencia sin lista de papel y los avisos a los padres por WhatsApp.',
    demo: null,
    problemas: [
      { problema: 'Cobrar mensualidades es perseguir pagos.', respuesta: 'Matrícula y cobro en línea con Yappy o tarjeta, recordatorio de pago y estado de cuenta por estudiante.', servicios: ['E01'] },
      { problema: 'La asistencia se pasa en papel y se pierde.', respuesta: 'Asistencia con QR o tarjeta, con aviso a los padres si el estudiante no llegó.', servicios: ['E02'] },
      { problema: 'Las circulares no llegan a la casa.', respuesta: 'Avisos y recordatorios a los padres por WhatsApp.', servicios: ['E03'] },
    ],
  },
  {
    sector: 'servicios',
    slug: 'talleres-y-salones',
    singular: 'taller o salón',
    icono: 'car',
    foto: 'sector-servicios',
    titulo: 'Tecnología para talleres, autolavados y salones',
    bajada: 'Que el cliente saque turno, sepa cuánto le falta y reciba un mensaje cuando su carro o su cita esté lista.',
    demo: 'reservas',
    problemas: [
      { problema: 'El cliente espera sin saber cuánto le falta.', respuesta: 'Turnos en línea con su lugar en la fila y aviso por WhatsApp cuando está listo.', servicios: ['V01'] },
      { problema: 'Presupuestos aprobados de palabra que luego se discuten.', respuesta: 'Órdenes de trabajo con fotos del vehículo y aprobación del cliente por WhatsApp.', servicios: ['V02'] },
      { problema: 'Citas que se cruzan en la barbería o el salón.', respuesta: 'Agenda por profesional con recordatorio y seña en línea.', servicios: ['V03'] },
    ],
  },
  {
    sector: 'todos',
    slug: 'cualquier-negocio',
    singular: 'negocio',
    icono: 'briefcase',
    foto: 'sector-todos',
    titulo: 'Software y automatización para cualquier negocio',
    bajada: 'Página web, apps, sistemas a medida y automatizaciones para lo que hoy se hace en Excel, en papel o copiando y pegando.',
    demo: null,
    problemas: [
      { problema: 'El negocio no aparece cuando lo buscan.', respuesta: 'Página web, perfil de Google con tu ubicación y reseñas, y correo con tu dominio.', servicios: ['T01', 'T13', 'T12'] },
      { problema: 'Todo vive en Excel y nadie sabe cuál es la versión buena.', respuesta: 'Software a medida para cómo trabaja tu negocio: inventario, clientes, cotizaciones.', servicios: ['T02', 'T14', 'T15', 'T06'] },
      { problema: 'Alguien copia y pega datos todo el día.', respuesta: 'Automatizaciones e integraciones entre tus sistemas, y lectura de facturas con IA.', servicios: ['T04', 'T20', 'T21'] },
      { problema: 'Las mismas preguntas por WhatsApp a toda hora.', respuesta: 'Un asistente con IA que contesta con tu información y te pasa lo que no sabe.', servicios: ['T05'] },
      { problema: 'Se cae la computadora y se pierde todo.', respuesta: 'Respaldo, seguridad y soporte técnico para tu oficina.', servicios: ['T18', 'T19', 'T10'] },
    ],
  },
];
